### ISSUE TITLE
Filewatcher.projectChanged throwing error before project starts

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#1009]
**Description:**
If I create a project, the `projectChanged` function is throwing error just before the app starts. Though there is no issue with the app starting or build affecting it, not sure what might be causing this:

```
[06/11/19 16:10:26 myspr] [INFO] Build completed for 4bb21420-00af-11ea-8d51-9982ecc43880
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is .classpath projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is .cw-settings projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is .gitignore projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is .project projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is Dockerfile projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is Dockerfile-tools projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is README.md projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is bin/.project projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart/springjavatemplate/Chart.yaml projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart/springjavatemplate/bindings.yaml projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart/springjavatemplate/templates/basedeployment.yaml projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart/springjavatemplate/templates/deployment.yaml projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart/springjavatemplate/templates/hpa.yaml projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart/springjavatemplate/templates/istio.yaml projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart/springjavatemplate/templates/service.yaml projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart/springjavatemplate/values.yaml projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is pom.xml projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src/main/java/application/Info.java projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src/main/java/application/SBApplication.java projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src/main/java/application/rest/HealthEndpoint.java projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src/main/java/application/rest/v1/Example.java projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src/main/resources/application-local.properties projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src/main/resources/application.properties projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src/main/resources/public/index.html projectRoot is /root/app
[06/11/19 16:10:29 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src/test/java/application/HealthEndpointTest.java projectRoot is /root/app
[06/11/19 16:10:29 FileWatcher.js] [ERROR] Error: project update 400 Bad request. projectID, timestamp, chunk, chunk_total and eventArray are required.
    at FileWatcher.projectFileChanged (/portal/modules/FileWatcher.js:395:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[06/11/19 16:10:34 ProjectList.js] [INFO] Project myspr started (project ID: 4bb21420-00af-11ea-8d51-9982ecc43880)
[06/11/19 16:10:34 myspr] [INFO] pingInTransitApplications: Application state for project 4bb21420-00af-11ea-8d51-9982ecc43880 has changed from starting to started
[06/11/19 16:10:34 myspr] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "4bb21420-00af-11ea-8d51-9982ecc43880",
  "appStatus": "started",
  "detailedAppStatus": " "
}
```

**Comment by GeekArthur** [comment]
I saw the same error
```
[06/11/19 16:10:29 FileWatcher.js] [ERROR] Error: project update 400 Bad request. projectID, timestamp, chunk, chunk_total and eventArray are required.
    at FileWatcher.projectFileChanged (/portal/modules/FileWatcher.js:395:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Seems like errors are from the caller since missing required parameters

**Comment by tobespc** [comment]
umm, interesting, looks like it could be a syncing issue possibly ...  Will investigate

**Comment by tobespc** [comment]
The error is being thrown from projectEventsController.ts becuase we are passing a timestamp value of '0' in but the check for !timestamp is incorrect when applied to a number.  We could remove the !timestamp check or change it to be something like 'timestamp != null'

export async function updateProjectForNewChange(projectID: string, timestamp: number,  chunkNum: number, chunk_total: number, eventArray: IFileChangeEvent[]): Promise<IUpdateProjectSuccess | IUpdateProjectFailure> {
    if (!projectID || !timestamp || !eventArray || !chunkNum || !chunk_total) {
        return { "statusCode": 400, "error": {"msg": "Bad request. projectID, timestamp, chunk, chunk_total and eventArray are required." }};
    }

passing to iterative-dev for comment

**Comment by ssh24** [comment]
Shouldn't timestamp be a **number** either ways? I think portal should parse it as a number and then call turbine using that number.

**Comment by tobespc** [comment]
we do pass you a number, but if that number is 0 or 1, your check fails

**Comment by ssh24** [comment]
I am looking at it. Please assign this to me.

**Comment by ssh24** [comment]
**Verified**
