### ISSUE TITLE
UnhandledPromiseRejectionWarning on docker copy of after enabling a project

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#1029]
**Description:**
I had a disabled project and when I tried enabling it back I get the following error:
```
(node:101) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/mylib/lib/chart/javamicroprofiletemplate/Chart.yaml :/home/default/app/lib/chart/javamicroprofiletemplate/Chart.yaml
must specify at least one container source

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
(node:101) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/mylib/lib/README.md :/home/default/app/lib/README.md
must specify at least one container source

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
(node:101) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/mylib/lib/Dockerfile-tools :/home/default/app/lib/Dockerfile-tools
must specify at least one container source
```

It looks like when portal copies the source over, it is missing the docker container id of the application. Looks like it is being done even before the application container is up and thus the container id is empty and the copy fails.

**Comment by tobespc** [comment]
@james-wallis please take a look

**Comment by james-wallis** [comment]
I'll pick this up

**Comment by james-wallis** [comment]
@ssh24 I've tried and failed to recreate this issue.
Could you please pull master for all Codewind products and see if the issue persists please?

If it does still occur, steps which describe how to reproduce the product would help me to test it.
For example:
* Environment
* Method of running Codewind (VS_Code, Eclipse, cwctl)
* Version of Codewind
* Type of project
* What you did between disabling and enabling the project i.e. stopped and started codewind.

**Comment by ssh24** [comment]
@james-wallis I am unable to see this now anymore as well. Not sure what caused it to show up yesterday.

**Comment by ssh24** [comment]
Actually, I just noticed the issue again but this time on windows:
```
Error: No such container:path: undefined:/home/default/app/src/main/liberty/config

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:65) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 73)
[08/11/19 20:47:12 saklib] [INFO] cw-settings file changed.
[08/11/19 20:47:12 saklib] [INFO] Updating container for liberty project /codewind-workspace/saklib
[08/11/19 20:47:12 FileWatcher.js] [DEBUG] Received filewatcher module response:
[08/11/19 20:47:12 FileWatcher.js] [DEBUG] {"statusCode":202}
[08/11/19 20:47:12 saklib] [INFO] The log name for a3d2ffb0-0268-11ea-bc65-e5ab01f015cd is cw-a3d2ffb0-0268-11ea-bc65-e5ab01f015cd-3e337ade6db34918755542804af33d9c46110501
[08/11/19 20:47:12 saklib] [INFO] Container name: cw-saklib-a3d2ffb0-0268-11ea-bc65-e5ab01f015cd
[08/11/19 20:47:12 saklib] [INFO] Log name: cw-a3d2ffb0-0268-11ea-bc65-e5ab01f015cd-3e337ade6db34918755542804af33d9c46110501
[08/11/19 20:47:12 saklib] [INFO] forceAction: undefined
[08/11/19 20:47:12 saklib] [TRACE] Triggering log file event for: application messages log

[08/11/19 20:47:12 server.js] [TRACE] GET /internal/api/v1/projects/a3d2ffb0-0268-11ea-bc65-e5ab01f015cd/logs/app called with
 req.body {}
[08/11/19 20:47:12 /portal/routes/projects/internal.route.js] [DEBUG] Internal API: get new logs
[08/11/19 20:47:12 User.js] [INFO] Check for new log files for project a3d2ffb0-0268-11ea-bc65-e5ab01f015cd
[08/11/19 20:47:12 FileWatcher.js] [INFO] Check for new app log files for project a3d2ffb0-0268-11ea-bc65-e5ab01f015cd
[08/11/19 20:47:12 Turbine] [INFO] Fetching logs for project a3d2ffb0-0268-11ea-bc65-e5ab01f015cd
[08/11/19 20:47:12 Turbine] [TRACE] The projectInfo has been updated for deploymentRegistry: {"projectID":"a3d2ffb0-0268-11ea-bc65-e5ab01f015cd","projectType":"liberty","location":"/codewind-workspace/saklib","autoBuildEnabled":true,"startMode":"run","appPorts":["9080"],"language":"java","debugPort":"7777","ignoredPaths":["/.project","/Dockerfile-tools","/target","/mc-target","/cli-config.yml","/README.md","/Jenkinsfile","/.cfignore","/load-test*","*/node_modules*","*/.git/*","*/.DS_Store","*/*.swp","*/*.swx","*/4913","*/.dockerignore","*/.gitignore","*/*~","/.settings","/localm2cache.zip","/libertyrepocache.zip","/chart"],"isHttps":false,"buildRequest":false,"sentProjectInfo":false}
[08/11/19 20:47:12 saklib] [INFO] Checking for user Maven settings
[08/11/19 20:47:12 saklib] [INFO] executeBuildScript with args:  {/file-watcher/scripts/liberty-container.sh /codewind-workspace/saklib /codewind-workspace a3d2ffb0-0268-11ea-bc65-e5ab01f015cd update cw-saklib-a3d2ffb0-0268-11ea-bc65-e5ab01f015cd true cw-a3d2ffb0-0268-11ea-bc65-e5ab01f015cd-3e337ade6db34918755542804af33d9c46110501 run 7777 NONE saklib-a3d2ffb0-0268-11ea-bc65-e5ab01f015cd undefined}, In K8 environment: undefined
[08/11/19 20:47:12 saklib] [INFO] Now tracking running process 1944 for project a3d2ffb0-0268-11ea-bc65-e5ab01f015cd
[08/11/19 20:47:12 saklib] [INFO] The debug port is already set to: 7777
(node:65) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/saklib/src/main/webapp/WEB-INF/beans.xml undefined:/home/default/app/src/main/webapp/WEB-INF/beans.xml
Error: No such container:path: undefined:/home/default/app/src/main/webapp/WEB-INF

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:65) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 74)
(node:65) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/saklib/src/main/resources/index.html undefined:/home/default/app/src/main/resources/index.html
Error: No such container:path: undefined:/home/default/app/src/main/resources
```

I created a fresh liberty project and saw this

**Comment by mattcolegate** [comment]
@ssh24 can you give us more details to recreate please? Ideally:
*  IDE you were using and version of the plugins
*  sha of the PDE image you were using
*  Exact steps to recreate the issue - were you creating a new project and saw it in the logs during creation? Did the project come up? Did the project fail to come up show as disabled? Did you then recreate the project?
*  Can you also post the whole log rather than a snippet - sometimes something going wrong earlier in the process can lead to a more serious, more noticable failure like the kind you're seeing later in the log

**Comment by ssh24** [comment]
I have attached the full log here 
[pfe.log](https://github.com/eclipse/codewind/files/3831741/pfe.log)


- I was using the latest version of the IDE Plugin (pulled in latest this morning)
- PFE image sha: 6180c017fa6684b653ee1a3f0501b9844b54a44b
- The project does build and come up but you will see in the logs, after enabling it floods it with that message before the build starts.

**Comment by mattcolegate** [comment]
Thanks @ssh24, just one more question - Eclipse or VSCode for the IDE? (or che?)

**Comment by mattcolegate** [comment]
Hi @ssh24, the pfe.log file you attached doesn't contain the text `Error: No such container:path:`. Can you please verify you've uploaded the correct log file? Also any other pertinent log files, like the maven build or application log?

**Comment by ssh24** [comment]
[pfe.log](https://github.com/eclipse/codewind/files/3831982/pfe.log)

@mattcolegate For some reason the `UnhandledPromiseRejectionWarning` error did not get redirected to the file. I have uploaded it again

**Comment by ssh24** [comment]
Also the IDE I used was VSCode

**Comment by stalleyj** [comment]
@ssh24 Can we close this as we are unable to recreate the issue with the latest code ?

**Comment by tobespc** [comment]
closing as unable to recreate.  Will reopen should this happen again
