### ISSUE TITLE
A newly created class in a new package does not exist in the app container

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#1112]
**Codewind version:** 0.6.0
**OS:** Mac
**IDE extension version:** 0.6.0
**IDE version:** VSCode or Eclipse 2019.09
**Kubernetes cluster:** Tested locally
**Description:** If you start with a newly created Spring Boot project, create a new Class file in a new package, the maven build is successful.  However, the class is NOT in the application container.  It however is in PFE.

**Steps to reproduce:**
1. Create codewind Spring project (Can be Java MP as well)
2. Create a new class in a new package (Use the Eclipse New Class wizard if desired)
--> Maven build is successful, but the class does not exist in the application container (It's essentially building the original contents from the project template)

**Workaround:** 
WIthout manually updating the container, no.

This is a stop-ship for 0.6.0.

**Comment by rajivnathan** [comment]
Assigning to portal as this appears to be an issue with syncing

**Comment by maysunfaisal** [comment]
### When I change an existing class:
```
  timeStamp: 1573677749706 }
[13/11/19 20:44:21 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src/main/java/application/rest/v1/Example.java projectRoot is /root/app
[13/11/19 20:44:21 dockerFunctions.js] [DEBUG] [docker cp command] docker cp /codewind-workspace/maysunsp1/src/main/java/application/rest/v1/Example.java 417c23643cd65205792e53fc443512e1b05a61dc5a3bc5f86f304c3533f02faf:/root/app/src/main/java/application/rest/v1/Example.java
[13/11/19 20:44:21 User.js] [DEBUG] Project 5a92a180-0654-11ea-842c-1d634f5af189 file change list received on 1573677749706. chunk number 1 with total chunk 1 for this timestamp.
[13/11/19 20:44:21 FileWatcher.js] [DEBUG] Portal's event listener: projectStatusChanged
[13/11/19 20:44:21 FileWatcher.js] [DEBUG] Portal's event listener: {"projectID":"5a92a180-0654-11ea-842c-1d634f5af189","buildRequired":true}
[13/11/19 20:44:21 FileWatcher.js] [DEBUG] projectStatusChanged: unknown (project 5a92a180-0654-11ea-842c-1d634f5af189)
[13/11/19 20:44:21 FileWatcher.js] [TRACE] projectStatusChanged: unknown (project: {
  "projectID": "5a92a180-0654-11ea-842c-1d634f5af189",
  "buildRequired": true
})
[13/11/19 20:44:21 FileWatcher.js] [DEBUG] Received filewatcher module response: 
[13/11/19 20:44:21 FileWatcher.js] [DEBUG] {"statusCode":202}
[13/11/19 20:44:21 maysunsp1] [INFO] Project 5a92a180-0654-11ea-842c-1d634f5af189 file changed
[13/11/19 20:44:21 maysunsp1] [INFO] Detected other file changes, Codewind will build the project
[13/11/19 20:44:21 maysunsp1] [INFO] File change detected. Project will re-build.
[13/11/19 20:44:21 maysunsp1] [INFO] Auto build disabled so build will not be started
[13/11/19 20:44:21 maysunsp1] [INFO] Updating project build required state to true
[13/11/19 20:44:21 maysunsp1] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "5a92a180-0654-11ea-842c-1d634f5af189",
  "buildRequired": true
}
```

### However if i have a new class in a new package:
```
[13/11/19 20:45:30 maysunsp1] [INFO] Updating project build required state to true
(node:93) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/maysunsp1/src/main/java/maysun/Test.java 417c23643cd65205792e53fc443512e1b05a61dc5a3bc5f86f304c3533f02faf:/root/app/src/main/java/maysun/Test.java
Error: No such container:path: 417c23643cd65205792e53fc443512e1b05a61dc5a3bc5f86f304c3533f02faf:/root/app/src/main/java/maysun

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:93) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
(node:93) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/maysunsp1/src/main/java/maysun/Test.java 417c23643cd65205792e53fc443512e1b05a61dc5a3bc5f86f304c3533f02faf:/root/app/src/main/java/maysun/Test.java
Error: No such container:path: 417c23643cd65205792e53fc443512e1b05a61dc5a3bc5f86f304c3533f02faf:/root/app/src/main/java/maysun

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:93) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
```

The change is not present in the app container because of the wrong docker cp cmd. Need to make sure docker cp is acc to documentation here https://docs.docker.com/engine/reference/commandline/cp/#parent-command. It lists the various combinations of SRC and DEST file and dir.

**Comment by keithchong** [comment]
@maysunfaisal , reproducible using a Java MicroProfile project

**Comment by jcockbain96** [comment]
Picking this up @tobespc

**Comment by tobespc** [comment]
The issue is scoped to a new directory being created rather than just a new file.  If the new file is in an existing directory, then all is good.  If a new folder is also added, that is what causes the problem

**Comment by jcockbain96** [comment]
I see this for all project types, whenever do the `docker cp` with a file beneath new directories. 

We are invoking the copy here (https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/projects/remoteBind.route.js#L249), which errors when the parents dirs don't exist at the `dest_path`. 

Looking through the documentation sent by @maysunfaisal, it seems `docker cp` won't make parent dirs if they don't exist on the destination path (when a file path is sent). 

So our syncing logic should send the path to the directory that's been created, at the highest level which is changed, and `docker cp` will copy its contents.

**Comment by tobespc** [comment]
@jcockbain96 Can you put a PR against 0.6.0 as well please

**Comment by malincoln** [comment]
@keithchong pls verify and get Steven to close if satisfied.  Thanks

**Comment by keithchong** [comment]
@sghung, @malincoln I see the new package (folder) and class now in the app.  (The project built successfully as well.)  Closing.
