### ISSUE TITLE
Gatekeeper server won't start

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1180]
after `cwctl install remote`,
```
[ /tim/programs/codewind ] 07 (master) $ kw po
kubectl get po @ 15:07:34
NAME                                             READY   STATUS             RESTARTS   AGE
codewind-gatekeeper-k34uy7if-86d688b784-xc4mv    0/1     CrashLoopBackOff   4          2m10s
codewind-keycloak-k34uy7if-94b4d8d5c-gg6c5       1/1     Running            0          2m56s
codewind-performance-k34uy7if-6cf566f659-f7p7h   1/1     Running            0          2m10s
codewind-pfe-k34uy7if-6d64b969d9-9s4tj           1/1     Running            0          2m11s
^C
[ /tim/programs/codewind ] 07 (master) $ k logs -f po/codewind-gatekeeper-k34uy7if-86d688b784-xc4mv

> gatekeeper@1.0.0 start /usr/src/app
> node server.js

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'express'
Require stack:
- /usr/src/app/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/server.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/server.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatekeeper@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatekeeper@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-11-18T20_07_08_581Z-debug.log
[ /tim/programs/codewind ] 07 (master) $
```

The Gatekeeper container fails to start, it appears to be because `npm install` is not included in [its dockerfile](https://github.com/eclipse/codewind/blob/master/src/gatekeeper/Dockerfile)?

**Comment by markcor11** [comment]
PR added to address this : https://github.com/eclipse/codewind/pull/1190

/pipeline verify

**Comment by tetchel** [comment]
verified
