### ISSUE TITLE
Keycloak in crashloopbackoff when installing onto ROKS cluster

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1319]
I tried to remote install codewind into the `codewind-ide` ROKS cluster.  Keycloak never successfully started, it continually went into crashloopbackoff.  When I `kubectl describe` the pod, there is a warning about an unbound PVC
```
% kubectl -n codewind-jsp describe pod codewind-keycloak-k3kmwu32-5847648b66-4lf8g
Name:           codewind-keycloak-k3kmwu32-5847648b66-4lf8g
Namespace:      codewind-jsp
Priority:       0
Node:           10.166.106.19/10.166.106.19
Start Time:     Fri, 29 Nov 2019 16:06:10 -0500
Labels:         app=codewind-keycloak
                codewindWorkspace=k3kmwu32
                pod-template-hash=1403204622
Annotations:    openshift.io/scc: privileged
Status:         Running
IP:             172.30.89.65
IPs:            <none>
Controlled By:  ReplicaSet/codewind-keycloak-k3kmwu32-5847648b66
Containers:
  codewind-keycloak:
    Container ID:   cri-o://b27982f549f6e9f87b5057e911ba4161ac549cfed7db63f3b93201199abd50a3
    Image:          eclipse/codewind-keycloak-amd64:latest
    Image ID:       docker.io/eclipse/codewind-keycloak-amd64@sha256:3da8ad224ed0a8ea9bed7aef0a25e6334891bd00088aa750f96a6ae78b966896
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 29 Nov 2019 16:12:37 -0500
      Finished:     Fri, 29 Nov 2019 16:12:42 -0500
    Ready:          False
    Restart Count:  6
    Environment:
      KEYCLOAK_USER:             <set to the key 'keycloak-admin-user' in secret 'secret-keycloak-user-k3kmwu32'>      Optional: false
      KEYCLOAK_PASSWORD:         <set to the key 'keycloak-admin-password' in secret 'secret-keycloak-user-k3kmwu32'>  Optional: false
      PROXY_ADDRESS_FORWARDING:  true
    Mounts:
      /opt/jboss/keycloak/standalone/data from keycloak-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from codewind-k3kmwu32-token-6l555 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  keycloak-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  codewind-keycloak-pvc-k3kmwu32
    ReadOnly:   false
  codewind-k3kmwu32-token-6l555:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  codewind-k3kmwu32-token-6l555
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  node-role.kubernetes.io/compute=true
Tolerations:     <none>
Events:
  Type     Reason            Age                    From                    Message
  ----     ------            ----                   ----                    -------
  Warning  FailedScheduling  6m57s (x18 over 9m2s)  default-scheduler       pod has unbound PersistentVolumeClaims
  Warning  FailedScheduling  6m57s                  default-scheduler       could not find v1.PersistentVolume "pvc-c19147ac-12eb-11ea-820d-7a45def663f5"
  Normal   Scheduled         6m48s                  default-scheduler       Successfully assigned codewind-jsp/codewind-keycloak-k3kmwu32-5847648b66-4lf8g to 10.166.106.19
  Normal   Started           5m41s (x4 over 6m43s)  kubelet, 10.166.106.19  Started container
  Normal   Pulling           4m56s (x5 over 6m46s)  kubelet, 10.166.106.19  pulling image "eclipse/codewind-keycloak-amd64:latest"
  Normal   Pulled            4m56s (x5 over 6m44s)  kubelet, 10.166.106.19  Successfully pulled image "eclipse/codewind-keycloak-amd64:latest"
  Normal   Created           4m55s (x5 over 6m43s)  kubelet, 10.166.106.19  Created container
  Warning  BackOff           102s (x21 over 6m29s)  kubelet, 10.166.106.19  Back-off restarting failed container
```
When I log into the cluster's web console and look at the logs for the pod, I see the following
```
Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
--
  | -b 0.0.0.0
  | =========================================================================
  |  
  | Using Embedded H2 database
  |  
  | =========================================================================
  |  
  | =========================================================================
  |  
  | JBoss Bootstrap Environment
  |  
  | JBOSS_HOME: /opt/jboss/keycloak
  |  
  | JAVA: java
  |  
  | JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED
  |  
  | =========================================================================
  |  
  | 21:28:18,447 INFO  [org.jboss.modules] (main) JBoss Modules version 1.9.1.Final
  | java.lang.IllegalStateException: WFLYSRV0126: Could not create server content directory: /opt/jboss/keycloak/standalone/data/content
  | at org.jboss.as.server@10.0.0.Final//org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:482)
  | at org.jboss.as.server@10.0.0.Final//org.jboss.as.server.Main.determineEnvironment(Main.java:388)
  | at org.jboss.as.server@10.0.0.Final//org.jboss.as.server.Main.main(Main.java:96)
  | at org.jboss.modules.Module.run(Module.java:352)
  | at org.jboss.modules.Module.run(Module.java:320)
  | at org.jboss.modules.Main.main(Main.java:593)
  | 21:28:19,201 FATAL [org.jboss.as.server] (main) WFLYSRV0239: Aborting with exit code 1
```

**Comment by johnmcollier** [comment]
@jopit I spoke with Mark about this today, https://github.com/eclipse/codewind-installer/pull/252 should fix it.

**Comment by jgwest** [comment]
@tobespc: GitHub didn't allow me to assign the following users: markcor11

Note that only org members, repo collaborators and people who have commented on this issue/PR can be assigned.

**Comment by markcor11** [comment]
PR https://github.com/eclipse/codewind-installer/pull/252 has landed

/pipeline verify

**Comment by jopit** [comment]
Verified.
