### ISSUE TITLE
[Eclipse IDE] Request to disable log stream after project deleted causes exception

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1398]
This does not affect the function but the code is sending an API request to disable the log stream for a project when it gets the deletion event.  Since the project is gone this is causing an exception to be logged:
```
!ENTRY org.eclipse.codewind.core 4 0 2019-12-05 14:54:14.775
!MESSAGE [ERROR SocketConsole.dispose:76] Error closing console output stream for: node1 - docker.build.log
!STACK 0
java.io.IOException: Received bad response code 404 for uri http://127.0.0.1:10000/api/v1/projects/698d7c10-171a-11ea-a18c-57b302a87e0d/logs/build/docker.build.log with error message Not Found
	at org.eclipse.codewind.core.internal.connection.CodewindConnection.checkResult(CodewindConnection.java:805)
	at org.eclipse.codewind.core.internal.connection.CodewindConnection.requestDisableLogStream(CodewindConnection.java:618)
	at org.eclipse.codewind.core.internal.console.SocketConsole.dispose(SocketConsole.java:73)
	at org.eclipse.ui.console.AbstractConsole.destroy(AbstractConsole.java:267)
	at org.eclipse.ui.console.AbstractConsole$Lifecycle.consolesRemoved(AbstractConsole.java:77)
	at org.eclipse.ui.internal.console.ConsoleManager$ConsoleNotifier.run(ConsoleManager.java:157)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.console.ConsoleManager$ConsoleNotifier.notify(ConsoleManager.java:175)
	at org.eclipse.ui.internal.console.ConsoleManager.fireUpdate(ConsoleManager.java:254)
	at org.eclipse.ui.internal.console.ConsoleManager.removeConsoles(ConsoleManager.java:236)
	at org.eclipse.codewind.core.internal.CodewindEclipseApplication.dispose(CodewindEclipseApplication.java:238)
	at org.eclipse.codewind.core.internal.connection.CodewindConnection.removeApp(CodewindConnection.java:358)
	at org.eclipse.codewind.core.internal.connection.CodewindSocket.onProjectDeletion(CodewindSocket.java:489)
	at org.eclipse.codewind.core.internal.connection.CodewindSocket.access$12(CodewindSocket.java:482)
	at org.eclipse.codewind.core.internal.connection.CodewindSocket$13.call(CodewindSocket.java:260)
```

**Comment by eharris369** [comment]
Fixed by: https://github.com/eclipse/codewind-eclipse/pull/525
