### ISSUE TITLE
[Eclipse IDE] Protocol version error when connect to Codewind on OpenShift

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1417]
Getting the following exception when trying to connect to Codewind on OpenShift.  The SSLContext should be created with TLSv1.2.

javax.net.ssl.SSLException: Received fatal alert: protocol_version
        at com.ibm.jsse2.k.a(k.java:32)
        at com.ibm.jsse2.k.a(k.java:37)
        at com.ibm.jsse2.av.b(av.java:549)
        at com.ibm.jsse2.av.a(av.java:715)
        at com.ibm.jsse2.av.i(av.java:574)
        at com.ibm.jsse2.av.a(av.java:280)
        at com.ibm.jsse2.av.startHandshake(av.java:431)
        at com.ibm.net.ssl.www2.protocol.https.c.afterConnect(c.java:167)
        at com.ibm.net.ssl.www2.protocol.https.d.connect(d.java:62)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1576)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1504)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:491)
        at com.ibm.net.ssl.www2.protocol.https.b.getResponseCode(b.java:56)
        at org.eclipse.codewind.core.internal.HttpUtil$HttpResult.<init>(HttpUtil.java:74)
        at org.eclipse.codewind.core.internal.HttpUtil.sendRequest(HttpUtil.java:217)
        at org.eclipse.codewind.core.internal.HttpUtil.get(HttpUtil.java:150)
        at org.eclipse.codewind.core.internal.connection.CodewindConnection.requestCodewindReady(CodewindConnection.java        at org.eclipse.codewind.core.internal.connection.CodewindConnection.waitForReady(CodewindConnection.java:391)
        at org.eclipse.codewind.core.internal.connection.CodewindConnection.connect(CodewindConnection.java:86)
        at org.eclipse.codewind.ui.internal.wizards.CodewindConnectionComposite.createConnection(CodewindConnectionCompo        at org.eclipse.codewind.ui.internal.wizards.NewCodewindConnectionPage.createConnection(NewCodewindConnectionPage        at org.eclipse.codewind.ui.internal.wizards.NewCodewindConnectionWizard$1.run(NewCodewindConnectionWizard.java:6        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by malincoln** [comment]
@eharris369 does anyone else need to verify and close?

**Comment by eharris369** [comment]
@malincoln I don't know of anyone else that ran into it.  The 0.7.0 branch must have been created just before I delivered the fix so I had to create another PR for 0.7.0: https://github.com/eclipse/codewind-eclipse/pull/464

**Comment by malincoln** [comment]
@eharris369 okay so you should be able to close now.

**Comment by eharris369** [comment]
This is fixed in both 0.7.0 and master.
