### ISSUE TITLE
Keycloak startup errors when installing remote codewind via cwctl

### ISSUE THREAD

**Issue by lentheivendra** [eclipse/codewind#1420]
**Codewind version:** latest/master
**OS:** Windows client, also seen with Mac client
**Kubernetes cluster:** OKD 3.11

After setting up a OKD 3.11 cluster with root and privileged access, when installing codewind remote via:
`cwctl.exe --insecure install remote --namespace codewind --kadminuser admin --kadminpass admin --krealm codewind --kclient codewind --kdevuser developer --kdevpass developer --ingress aa.bb.cc.dd.nip.io` where aa.bb.cc.dd.nip.io is the cluster's ingress domain, keycloak fails to start with errors related to mysql database connectivity.

Snippets from the keycloak pod log (full log attached as file):

```
[keycloakpodlog.txt](https://github.com/eclipse/codewind/files/3934011/keycloakpodlog.txt)

Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication()
        ...
Caused by: java.lang.RuntimeException: Failed to connect to database
        ...
Caused by: java.sql.SQLException: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/KeycloakDS
        ...
Caused by: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/KeycloakDS
        ...
Caused by: javax.resource.ResourceException: IJ031084: Unable to create connection
         ...
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
        ...
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at com.mysql.jdbc@5.1.46//com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
        at com.mysql.jdbc@5.1.46//com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301)
```

**Comment by markcor11** [comment]
Cwctl deploys keycloak using the embedded H2 database stored on a persistent volume rather than an optional remote MySQL or Postgres database.  Do you happen to have the kubectl describe output for the Keycloak pod ?

**Comment by johnmcollier** [comment]
@lentheivendra @jingfuwang Please try using the following for the ingress domain on OKD:
- `<namespace>.<ip>.nip.io`, where `namespace` is the namespace you're installing Codewind in. I suspect the OKD router is rejecting your routes as invalid.

**Comment by johnmcollier** [comment]
I'm unable to reproduce on OCP4 or OpenShift 3.11 on IBM Cloud, this seems to be restricted to OKD 3.11, hmm

**Comment by markcor11** [comment]
I wonder if storage is available, I have a check for that in a branch but haven’t delivered it yet...

**Comment by GeekArthur** [comment]
@markcor11 I can confirm storage is available
```
Jingfus-MacBook-Pro:0.7.0 jingfuwang$ k get pv
NAME              CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                     STORAGECLASS   REASON    AGE
che-data-volume   8Gi        RWO,RWX        Recycle          Available                                                                      51d
che-workspace     8Gi        RWO            Recycle          Bound       che/codewind-keycloak-pvc-k3uln1lv                                 64d
che-workspace2    8Gi        RWO,RWX        Recycle          Available                                                                      52d
che-workspace3    8Gi        RWO,RWX        Recycle          Available                                                                      100d
che-workspace4    8Gi        RWO            Recycle          Bound       codewind/codewind-keycloak-pvc-k3uq4elc                            46d
che-workspace5    8Gi        RWO            Recycle          Bound       che/postgres-data                                                  64d
Jingfus-MacBook-Pro:0.7.0 jingfuwang$ k get pvc
NAME                             STATUS    VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
codewind-keycloak-pvc-k3uq4elc   Bound     che-workspace4   8Gi        RWO                           7m
```

**Comment by GeekArthur** [comment]
More specifically it fails on container starting stage
```
Warning  BackOff    1m (x33 over 10m)  kubelet, jing-okd-worker2  Back-off restarting failed container
```
All other stages are good such as pulling image, persistent volume claim, etc

Also the same `cwctl` works on ROKS cluster but doesn't work on OKD cluster, so seems like the issue is OKD specific. I paste the whole keycloak pod logs below.

[keycloak.log](https://github.com/eclipse/codewind/files/3934316/keycloak.log)

**Comment by GeekArthur** [comment]
FWIW, below is describe keycloak po
```
Jingfus-MacBook-Pro:0.7.0 jingfuwang$ k describe po codewind-keycloak-k3uq4elc-78ddb99854-d4qbv
Name:               codewind-keycloak-k3uq4elc-78ddb99854-d4qbv
Namespace:          codewind
Priority:           0
PriorityClassName:  <none>
Node:               jing-okd-worker2/9.37.138.214
Start Time:         Fri, 06 Dec 2019 17:31:30 -0500
Labels:             app=codewind-keycloak
                    codewindWorkspace=k3uq4elc
                    pod-template-hash=3488655410
Annotations:        openshift.io/scc=privileged
Status:             Running
IP:                 10.131.1.137
Controlled By:      ReplicaSet/codewind-keycloak-k3uq4elc-78ddb99854
Containers:
  codewind-keycloak:
    Container ID:   docker://2bc4b5aff7ec1d3c40d5bcd2618ac870c8c933e0048e8e68935ad22a4977bd72
    Image:          eclipse/codewind-keycloak-amd64:latest
    Image ID:       docker-pullable://docker.io/eclipse/codewind-keycloak-amd64@sha256:ade182d1e18d0634836e98b0e335db8146aeaaa4532f65f598c64f4a4edc932f
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 06 Dec 2019 18:02:15 -0500
      Finished:     Fri, 06 Dec 2019 18:02:40 -0500
    Ready:          False
    Restart Count:  10
    Environment:
      KEYCLOAK_USER:             <set to the key 'keycloak-admin-user' in secret 'secret-keycloak-user-k3uq4elc'>      Optional: false
      KEYCLOAK_PASSWORD:         <set to the key 'keycloak-admin-password' in secret 'secret-keycloak-user-k3uq4elc'>  Optional: false
      PROXY_ADDRESS_FORWARDING:  true
    Mounts:
      /opt/jboss/keycloak/standalone/data from keycloak-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from keycloak-k3uq4elc-token-p8xmc (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  keycloak-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  codewind-keycloak-pvc-k3uq4elc
    ReadOnly:   false
  keycloak-k3uq4elc-token-p8xmc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  keycloak-k3uq4elc-token-p8xmc
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  node-role.kubernetes.io/compute=true
Tolerations:     <none>
Events:
  Type     Reason     Age                 From                       Message
  ----     ------     ----                ----                       -------
  Normal   Scheduled  33m                 default-scheduler          Successfully assigned codewind/codewind-keycloak-k3uq4elc-78ddb99854-d4qbv to jing-okd-worker2
  Normal   Created    31m (x4 over 33m)   kubelet, jing-okd-worker2  Created container
  Normal   Started    31m (x4 over 33m)   kubelet, jing-okd-worker2  Started container
  Normal   Pulled     29m (x5 over 33m)   kubelet, jing-okd-worker2  Successfully pulled image "eclipse/codewind-keycloak-amd64:latest"
  Normal   Pulling    7m (x10 over 33m)   kubelet, jing-okd-worker2  pulling image "eclipse/codewind-keycloak-amd64:latest"
  Warning  BackOff    2m (x118 over 32m)  kubelet, jing-okd-worker2  Back-off restarting failed container
```

**Comment by markcor11** [comment]
I see from the logs that Keycloak tries to load the H2 then the MySQL Jdbc driver,  could you try setting the env var DB_VENDOR=h2 in the deployment descriptor. If that works we can (and should) set it by default during deploy

**Comment by GeekArthur** [comment]
@markcor11 That works, perfect, thanks Mark! We can set `h2` by default to tolerate this issue.

**Comment by lentheivendra** [comment]
Confirmed fix to cwctl solves the issue.
