### ISSUE TITLE
Hybrid: Bad 500 response code getting build logs

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1466]
Using Eclipse, I created a remote go project, which built and ran successfully.  I then made a change and the build failed.  I then tried to get the build logs for the project, but there was a 500 error from the REST API

```
!ENTRY org.eclipse.codewind.core 4 0 2019-12-10 13:24:15.629
!MESSAGE [ERROR HttpUtil$HttpResult.<init>:89] Received bad response code 500 from https://codewind-gatekeeper-k40553fz.apps.refold.os.fyre.ibm.com/api/v1/projects/78c39da0-1b79-11ea-a005-ff0d2d6aa1f4/logs/build/docker.build.log - Error:
{}

!ENTRY org.eclipse.codewind.core 4 0 2019-12-10 13:24:15.630
!MESSAGE [ERROR SocketConsole.<init>:49] Error opening console output stream for: go1 - docker.build.log
!STACK 0
java.io.IOException: Received bad response code 500 for uri https://codewind-gatekeeper-k40553fz.apps.refold.os.fyre.ibm.com/api/v1/projects/78c39da0-1b79-11ea-a005-ff0d2d6aa1f4/logs/build/docker.build.log with error message {}
	at org.eclipse.codewind.core.internal.connection.CodewindConnection.checkResult(CodewindConnection.java:822)
	at org.eclipse.codewind.core.internal.connection.CodewindConnection.requestEnableLogStream(CodewindConnection.java:603)
	at org.eclipse.codewind.core.internal.console.SocketConsole.<init>(SocketConsole.java:47)
	at org.eclipse.codewind.core.internal.console.CodewindConsoleFactory.createLogFileConsole(CodewindConsoleFactory.java:30)
	at org.eclipse.codewind.ui.internal.actions.LogFileAction.run(LogFileAction.java:50)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4406)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4193)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3810)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

```

**Comment by markcor11** [comment]
1. Built Eclipse plugin from 0.7.0 branch 
2. Built Codewind PFE from 0.7.0 branch and deployed a new remote
3. Lauched Eclipse from Run-Configuration
4. Created a Connection to Codewind Remote
5. Created a Go APP
6. Launched it
7. Updated it
8. Watched it build by viewing the docker.build.log file 
9. Saw the logs stream : 

![Screenshot 2019-12-11 at 14 57 44](https://user-images.githubusercontent.com/28102564/70632399-a6bd9a00-1c26-11ea-8526-ae0ad6ee55b1.png)

**Comment by tetchel** [comment]
Even if we can't reproduce, we should see why PFE sent an empty error message

**Comment by markcor11** [comment]
Please could you provide the corresponding PFE logs from the time this problem occurs.

**Comment by markcor11** [comment]
The error 500 is a catch all error for an unexpected condition.  The main phases of this route are 

1. retrieving the project details,
2. fetching the project log types,
3. streaming the requested logs over the uiSocket.

There are places I can add increased debug and improve some of the error handling although I'd still like to know if this is happening on more than one of your remote deployments and if it consistently fails with the 0.7.0 branch.

**Comment by tetchel** [comment]
I meant is that instead of `res.sendStatus(500)` in the catch block, we should `res.status(500).send(err.message);` so we can see the actual error on the client side, but i agree pfe logs are needed.

**Comment by malincoln** [comment]
Per discussion, downgrading to "hot" and continue investigation.  Gather logs when it reoccurs.

**Comment by tobespc** [comment]
closing but will reopen should this occur again
