### ISSUE TITLE
NPE in Eclipse file watcher for removed resource

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1487]
After I remove a project from Codewind checking the box to delete the project contents I see the following in the console log.  It looks like it is trying to get the location for a deleted resource.

java.lang.NullPointerException
	at org.eclipse.codewind.filewatchers.eclipse.CodewindResourceChangeListener$CodewindResourceDeltaVisitor.visit(CodewindResourceChangeListener.java:124)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
	at org.eclipse.codewind.filewatchers.eclipse.CodewindResourceChangeListener.resourceChanged(CodewindResourceChangeListener.java:56)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:158)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:379)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:782)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:322)
	at org.eclipse.codewind.core.internal.CodewindEclipseApplication$3.run(CodewindEclipseApplication.java:343)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by jgwest** [comment]
Thanks Erin... a regression, likely due to https://github.com/eclipse/codewind-eclipse/pull/436 , PRs incoming...

**Comment by eharris369** [comment]
Verified that the exception no longer occurs.
