### ISSUE TITLE
[Eclipse IDE] Filewatcher unable to connect to remote PFE via WebSockets, when using IBM JVM

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1498]
An exception keeps showing up in the log file for the Eclipse file watcher when connected to a remote instance of Codewind running on OpenShift:
```
java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: No appropriate protocol, may be no appropriate cipher suite specified or protocols are deactivated
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:368)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1926)
	at org.eclipse.codewind.filewatchers.core.internal.WebSocketManagerThread.establishOrReestablishConnection(WebSocketManagerThread.java:252)
	at org.eclipse.codewind.filewatchers.core.internal.WebSocketManagerThread.run(WebSocketManagerThread.java:133)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol, may be no appropriate cipher suite specified or protocols are deactivated
	at com.ibm.jsse2.D.c(D.java:352)
	at com.ibm.jsse2.as.g(as.java:383)
	at com.ibm.jsse2.as.c(as.java:607)
	at com.ibm.jsse2.as.wrap(as.java:172)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:18)
	at org.eclipse.jetty.io.ssl.SslConnection.wrap(SslConnection.java:412)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:1047)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.process(HttpSenderOverHTTP.java:249)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:62)
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:212)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:85)
	at org.eclipse.jetty.client.HttpChannel.send(HttpChannel.java:128)
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:201)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:242)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:121)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:38)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:362)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:320)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:310)
	at org.eclipse.jetty.client.HttpDestination.succeeded(HttpDestination.java:244)
	at org.eclipse.jetty.client.AbstractConnectionPool.proceed(AbstractConnectionPool.java:153)
	at org.eclipse.jetty.client.AbstractConnectionPool$1.succeeded(AbstractConnectionPool.java:131)
	at org.eclipse.jetty.client.AbstractConnectionPool$1.succeeded(AbstractConnectionPool.java:123)
	at org.eclipse.jetty.util.Promise$Wrapper.succeeded(Promise.java:130)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onOpen(HttpConnectionOverHTTP.java:129)
	at org.eclipse.jetty.io.ssl.SslConnection.onOpen(SslConnection.java:360)
	at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:324)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:276)
	at org.eclipse.jetty.io.ManagedSelector.access$1800(ManagedSelector.java:62)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:933)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by eharris369** [comment]
[filewatcherd-1.log](https://github.com/eclipse/codewind/files/3956227/filewatcherd-1.log)

**Comment by jgwest** [comment]
This issue is specific to IBM JDK's cipher suite names, and [is described here](https://github.com/eclipse/jetty.project/issues/2921).

**Comment by jgwest** [comment]
/pipeline verify

I will verify on Erin's behalf on Friday once this is in the build.

**Comment by jgwest** [comment]
Verified as fixed on latest Eclipse driver, using IBM Java. 
/close
