### ISSUE TITLE
[Latest] Cannot open any webview on Che

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1567]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
Cannot open Image Registry Manager on master latest

Theia Log:
```
root INFO [hosted-plugin: 51] [DBUG: 16:53:14.343 Requester.js:443]: Doing GET request to https://localhost:9090/api/v1/registrysecrets
root INFO [hosted-plugin: 51] [DBUG: 16:53:14.359 Requester.js:443]: Doing GET request to https://localhost:9090/api/v1/imagepushregistry
root INFO [hosted-plugin: 51] [DBUG: 16:53:14.371 Requester.js:135]: No image push registry is set
root ERROR [hosted-plugin: 51] [ERRO: 16:53:14.466 WebviewWrapper.js:76]: Error with wizard page Image Registries: TypeError: this.webPanel.webview.asWebviewUri is not a function
    at Object.getStylesheet (/tmp/vscode-unpacked/eclipse.codewind-plugin.latest.jynfjokxmh.codewind-theia.vsix/extension/out/command/webview/WebviewWrapper.js:57:46)
    at Object.getManageRegistriesPage [as default] (/tmp/vscode-unpacked/eclipse.codewind-plugin.latest.jynfjokxmh.codewind-theia.vsix/extension/out/command/webview/pages/RegistriesPage.js:29:43)
    at RegistriesPageWrapper.<anonymous> (/tmp/vscode-unpacked/eclipse.codewind-plugin.latest.jynfjokxmh.codewind-theia.vsix/extension/out/command/webview/RegistriesPageWrapper.js:136:50)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/vscode-unpacked/eclipse.codewind-plugin.latest.jynfjokxmh.codewind-theia.vsix/extension/out/command/webview/RegistriesPageWrapper.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

![Screen Shot 2019-12-17 at 11 53 20 AM](https://user-images.githubusercontent.com/31771087/71016962-e15e8100-20c3-11ea-9f96-b2912f628d6d.png)

Please confirm this for local remote UI as well

**Comment by maysunfaisal** [comment]
cc: @ssh24
