### ISSUE TITLE
New project remove cwctl command is not working for remote

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1660]
The new cwctl project remove command is not working for remote.  I created a go project on a remote connection to OpenShift and tried to delete it but nothing happened.  Local projects can be successfully removed using the new command. If I switch back to using the REST API to remove the remote project then it does get removed properly. I am using the Eclipse IDE on Windows 10.

The command used is:
```
C:\Users\ERINHarris\.codewind\0.7.0\cwctl.exe --insecure project remove --id 31bf73e0-3229-11ea-a4e0-8596530ab35c
```

The exit value is 0 and the error and output streams are empty but the project is not deleted.  Doing `oc logs --tail 0 -f pod/codewind-pfe-k4ydlq4y-75f64cf965-4tlvx -n cweh` just before requesting the remove does not log anything whereas doing the same for local (`docker logs --tail 0 -f codewind-pfe`) shows:
```
[03/01/20 22:40:35 go2] [INFO] removeProject: Kill running processes and remove container...
[03/01/20 22:40:35 go2] [INFO] Project ID:        f5688650-2e79-11ea-a573-91259047069a
[03/01/20 22:40:35 go2] [INFO] Project Location:  /codewind-workspace/go2
[03/01/20 22:40:35 go2] [INFO] Project Type:      docker
[03/01/20 22:40:35 go2] [INFO] Project Container: cw-go2-f5688650-2e79-11ea-a573-91259047069a
[03/01/20 22:40:35 go2] [INFO] Removing container
[03/01/20 22:40:36 go2] [INFO] Removing docker image
[03/01/20 22:40:36 go2] [INFO] Extension absolute path is: undefined
[03/01/20 22:40:36 go2] [INFO] Project info cache is {}
[03/01/20 22:40:36 go2] [INFO] Successfully deleted f5688650-2e79-11ea-a573-91259047069a
[03/01/20 22:40:36 Turbine] [INFO] Removing project logs directory
[03/01/20 22:40:36 Turbine] [INFO] Log directory removed from: /codewind-workspace/.logs/go2-f5688650-2e79-11ea-a573-91259047069a
[03/01/20 22:40:36 Turbine] [INFO] f5688650-2e79-11ea-a573-91259047069a: Emitting event
 message: projectDeletion
 data: {
  "operationId": "f7284ce4427067a2e91a8239cea206e8",
  "projectID": "f5688650-2e79-11ea-a573-91259047069a",
  "status": "success"
}
[03/01/20 22:40:36 User.js] [INFO] Removing project directory at /codewind-workspace/go2
```

**Comment by tetchel** [comment]
blocks https://github.com/eclipse/codewind/issues/1565

**Comment by stalleyj** [comment]
I've recreated this issue and can see the following error in the PFE log

[09/01/20 14:34:31 /portal/routes/projects/remoteBind.route.js] [ERROR] TypeError: Cannot read property 'forEach' of null
    at getPathsToDelete (/portal/routes/projects/remoteBind.route.js:285:16)
    at router.post (/portal/routes/projects/remoteBind.route.js:229:43)

**Comment by james-wallis** [comment]
I'll check this in the CLI

**Comment by james-wallis** [comment]
PR open for this https://github.com/eclipse/codewind-installer/pull/324

**Comment by james-wallis** [comment]
The PR for this has just been merged, @eharris369 can you verify and close please.

**Comment by eharris369** [comment]
Verified that this is working now.
