### ISSUE TITLE
Global menu item for new codewind project does not work

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1722]
The global menu item for new codewind project is not working - getting NPE:

```
java.lang.NullPointerException
	at org.eclipse.codewind.ui.internal.wizards.NewCodewindProjectWizard.addPages(NewCodewindProjectWizard.java:71)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:632)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:119)
```

**Comment by eharris369** [comment]
Fixed by: https://github.com/eclipse/codewind-eclipse/pull/513 (master), https://github.com/eclipse/codewind-eclipse/pull/515 (0.8.0)
