### ISSUE TITLE
SVT: Codewind projects are not working

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1768]
**Codewind version:** 0.8.0
**OS:** Mac OS Mojave 10.14.6, Ubuntu 18.04, and VM with Windows 10

**IDE extension version:** 0.8.0
**IDE version:** 1.41.1

**Description:** @DavidG1011 and I noticed that Codewind projects are not working. Codewind style projects are being disabled and Appsody projects fail to start due to the following error:

`Running development environment...
[Error] The current directory is not a valid appsody project. Run 'appsody init <stack>' to create one. Run 'appsody list' to see the available stacks.`

<img width="1553" alt="Screen Shot 2020-01-15 at 11 52 46 AM" src="https://user-images.githubusercontent.com/49531960/72453792-abc5ba00-378d-11ea-9467-785eb5dd7091.png">

@jagraj

**Comment by DavidG1011** [comment]
Seeing this as well with Che 7.5.1. on OKD 4.2:
![image](https://user-images.githubusercontent.com/30476587/72454797-90f44500-378f-11ea-83d5-d1dfdb3c8141.png)

**Comment by tetchel** [comment]
Post PFE logs

**Comment by sujeilyfonseca** [comment]
[codewind-pfe.txt](https://github.com/eclipse/codewind/files/4066254/codewind-pfe.txt)

**Comment by makandre** [comment]
I think we need this build of PFE: https://ci.eclipse.org/codewind/view/Codewind/job/Codewind/job/codewind/job/0.8.0/26/ to match the change that went in for `cwctl`

(It was a fix for #1749)

**Comment by tetchel** [comment]
I believe it's these errors.

```
[15/01/20 16:35:43 /portal/routes/projects/remoteBind.route.js] [ERROR] SyntaxError: Unexpected token F in JSON at position 0
    at JSON.parse (<anonymous>)
    at uploadFile (/portal/routes/projects/remoteBind.route.js:178:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[15/01/20 16:35:43 /portal/routes/projects/remoteBind.route.js] [ERROR] SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at uploadFile (/portal/routes/projects/remoteBind.route.js:178:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[15/01/20 16:35:43 /portal/routes/projects/remoteBind.route.js] [ERROR] SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at uploadFile (/portal/routes/projects/remoteBind.route.js:178:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[15/01/20 16:35:43 /portal/routes/projects/remoteBind.route.js] [ERROR] SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at uploadFile (/portal/routes/projects/remoteBind.route.js:178:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[15/01/20 16:35:43 /portal/routes/projects/remoteBind.route.js] [ERROR] SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at uploadFile (/portal/routes/projects/remoteBind.route.js:178:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[15/01/20 16:35:43 /portal/routes/projects/remoteBind.route.js] [ERROR] SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at uploadFile (/portal/routes/projects/remoteBind.route.js:178:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[15/01/20 16:35:43 /portal/routes/projects/remoteBind.route.js] [ERROR] SyntaxError: Unexpected token p in JSON at position 0
    at JSON.parse (<anonymous>)
    at uploadFile (/portal/routes/projects/remoteBind.route.js:178:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Looks like some changes to the JSON stringifying/parsing went in this morning.

https://github.com/eclipse/codewind/pull/1754
https://github.com/eclipse/codewind-installer/pull/331

**Comment by tetchel** [comment]
i see, the Codewind build failed

```
09:40:52    1) Template API tests
09:40:52         PATCH /api/v1/batch/templates/repositories
09:40:52           should disable an existing repo and return 207 and the expected operations info:
09:40:52       Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_0.8.0/test/src/API/templates/templates.test.js)
```
I'll restart it and hope this is a timing issue, but the timeout for that test should likely be increased.

**Comment by tetchel** [comment]
The 0.8 build is green again, try now.

https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/0.8.0/

**Comment by sujeilyfonseca** [comment]
I tested this problem again with the latest version, and I can confirm that it works now:

<img width="1672" alt="Screen Shot 2020-01-15 at 1 22 34 PM" src="https://user-images.githubusercontent.com/49531960/72461725-99537c80-379d-11ea-86e6-684a53894ff8.png">

<img width="1597" alt="Screen Shot 2020-01-15 at 1 49 33 PM" src="https://user-images.githubusercontent.com/49531960/72461882-e3d4f900-379d-11ea-83b7-23f9e9ec2ac7.png">
