### ISSUE TITLE
Investigate what stops working when codewind loses internet access

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#1836]
First, ensure codewind is installed and a project is created. Then remove internet access and start playing around with codewind. Try creating projects, modifying existing projects, playing with functionality and recording down all problems here.

**Comment by sghung** [comment]
Travis' investigation:
- Cannot create projects
- Only GO can build projects
- Need to test appsody as well

**Comment by travis1111** [comment]
### Codewine projects

1. Go: works

2. lagom: modified code, save, auto build kicks in:

```sh
Build Failed - Creating image for build failed
The container failed to start for project lagom
Cause: Build image stage failed for lagom
Error: Build image stage failed for lagom
   at containerBuildAndRun (/file-watcher/server/dist/projects/projectUtil.js:1432:19)
```

3. microprofile:

```sh
Build Failed - Creating image for build failed
 executeBuildScript : 383 | | The command /file-watcher/scripts/liberty-container.sh /codewind-workspace/microprofile,/codewind-workspace,fdfb6a30-3dec-11ea-bc58-43a5703f883b,create,cw-microprofile-fdfb6a30-3dec-11ea-bc58-43a5703f883b,true,cw-fdfb6a30-3dec-11ea-bc58-43a5703f883b-89c9f70c8c86438bc98822a3bf61b31c2ac8d270,run,7777,NONE,microprofile-fdfb6a30-3dec-11ea-bc58-43a5703f883b,, failed with exit code 3
```

4. node js: 

```sh
Build Failed - Creating image for build failed
 { Error: Command failed: docker cp /codewind-workspace/nodejs/. :/app
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
must specify at least one container source
    at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/portal/node_modules/express/lib/response.js:170:12)
    at handleErrors (/portal/middleware/errorHandler.js:8:26)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/portal/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/portal/node_modules/express/lib/router/index.js:315:13)
    at /portal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
    at next (/portal/node_modules/express/lib/router/index.js:275:10)

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'docker cp /codewind-workspace/nodejs/. :/app',
  stdout: '',
  stderr: 'must specify at least one container source\n' }
```


5. Open liberty:

```sh
Build Failed - Creating image for build failed
Error output:
Touching container build log file: /codewind-workspace/.logs/open-liberty-2e2da160-3dec-11ea-bc58-43a5703f883b/docker.build.log
> Triggering log file event for: container build log
Running docker container build command: docker build --label builtBy=codewind -t cw-openliberty-2e2da160-3dec-11ea-bc58-43a5703f883b /codewind-workspace/open-liberty |& tee /codewind-workspace/.logs/open-liberty-2e2da160-3dec-11ea-bc58-43a5703f883b/docker.build.log
OKSending build context to Docker daemon  588.3kB
Step 1/14 : FROM maven:3.5.4-jdk-8-alpine AS builder
 ---> fb4bb0d89941
Step 2/14 : COPY pom.xml .
 ---> Using cache
 ---> e60e187dda38
Step 3/14 : COPY src src/
 ---> Using cache
 ---> 0a7f89b06f2d
Step 4/14 : RUN mvn install -DskipTests
 ---> Running in ac75b2f4ce66
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/net/wasdev/wlp/maven/parent/liberty-maven-app-parent/2.6.1/liberty-maven-app-parent-2.6.1.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM io.openliberty.samples:io.openliberty.sample.getting.started:1.0-SNAPSHOT (/pom.xml) points at io.openliberty.samples:io.openliberty.sample.getting.started instead of net.wasdev.wlp.maven.parent:liberty-maven-app-parent, please verify your project structure @ line 12, column 11
[FATAL] Non-resolvable parent POM for io.openliberty.samples:io.openliberty.sample.getting.started:1.0-SNAPSHOT: Could not transfer artifact net.wasdev.wlp.maven.parent:liberty-maven-app-parent:pom:2.6.1 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name does not resolve and 'parent.relativePath' points at wrong local POM @ line 12, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.openliberty.samples:io.openliberty.sample.getting.started:1.0-SNAPSHOT (/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.openliberty.samples:io.openliberty.sample.getting.started:1.0-SNAPSHOT: Could not transfer artifact net.wasdev.wlp.maven.parent:liberty-maven-app-parent:pom:2.6.1 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name does not resolve and 'parent.relativePath' points at wrong local POM @ line 12, column 11: Unknown host repo.maven.apache.org: Name does not resolve -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
The command '/bin/sh -c mvn install -DskipTests' returned a non-zero code: 1
```

6. Python:

```sh
Build Failed - Creating image for build failed

Error output:
Touching container build log file: /codewind-workspace/.logs/python-3454cb90-3dec-11ea-bc58-43a5703f883b/docker.build.log
Triggering log file event for: container build log
Running docker container build command: docker build --label builtBy=codewind -t cw-python-3454cb90-3dec-11ea-bc58-43a5703f883b /codewind-workspace/python |& tee /codewind-workspace/.logs/python-3454cb90-3dec-11ea-bc58-43a5703f883b/docker.build.log
OKSending build context to Docker daemon  12.29kB
Step 1/8 : FROM python:3.7-alpine
 ---> b2c276538711
Step 2/8 : ADD . /code
 ---> Using cache
 ---> c8f078997cae
Step 3/8 : WORKDIR /code
 ---> Using cache
 ---> b3d330ef432b
Step 4/8 : RUN chmod 644 /code/app.py
 ---> Using cache
 ---> 70e02f0f4238
Step 5/8 : RUN pip install flask
 ---> Running in fa35384a17f9
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbbffd5fed0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /simple/flask/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbbff69b490>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /simple/flask/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbbff699ed0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /simple/flask/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbbff699bd0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /simple/flask/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbbffd79190>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /simple/flask/
ERROR: Could not find a version that satisfies the requirement flask (from versions: none)
ERROR: No matching distribution found for flask
The command '/bin/sh -c pip install flask' returned a non-zero code: 1
```

7. Spring boot:

```sh
Build Failed - Maven build failed

[25/01/20 15:12:34 /portal/routes/projects/remoteBind.route.js] [ERROR] { Error: Command failed: docker cp /codewind-workspace/springboot/. :/root/app
must specify at least one container source

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'docker cp /codewind-workspace/springboot/. :/root/app',
  stdout: '',
  stderr: 'must specify at least one container source\n' }
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
[25/01/20 15:12:34 /portal/middleware/errorHandler.js] [ERROR] { error:
    at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
   { name: 'Error [ERR_HTTP_HEADERS_SENT]',
    at ServerResponse.send (/portal/node_modules/express/lib/response.js:170:12)
    at handleErrors (/portal/middleware/errorHandler.js:8:26)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/portal/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/portal/node_modules/express/lib/router/index.js:315:13)
     message: 'Cannot set headers after they are sent to the client' } }
    at /portal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
    at next (/portal/node_modules/express/lib/router/index.js:275:10)
```

8. swift:

```sh
Build Failed - Creating image for build failed

[27/01/20 15:16:36 /portal/routes/projects/remoteBind.route.js] [ERROR] { Error: Command failed: docker cp /codewind-workspace/swift/. :/swift-project
must specify at least one container source

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'docker cp /codewind-workspace/swift/. :/swift-project',
  stdout: '',
  stderr: 'must specify at least one container source\n' }
[27/01/20 15:16:36 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'Error [ERR_HTTP_HEADERS_SENT]',
     message: 'Cannot set headers after they are sent to the client' } }
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/portal/node_modules/express/lib/response.js:170:12)
    at handleErrors (/portal/middleware/errorHandler.js:8:26)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/portal/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/portal/node_modules/express/lib/router/index.js:315:13)
    at /portal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
    at next (/portal/node_modules/express/lib/router/index.js:275:10)
```

### Appsody projects

All 12 templates cannot build.  Same symptom:

![image](https://user-images.githubusercontent.com/35569780/73462567-05131900-434a-11ea-9c74-e7ec155e7578.png)

But application endpoint / health endpoint not accessible via browser.

**Comment by sghung** [comment]
TODO: setup meeting with Elson and Travis to discuss cache options

**Comment by sghung** [comment]
Had meeting with Elson and Rajiv. Our team doing more brainstorming before meeting again.

**Comment by sghung** [comment]
The work Travis had looked into is completed, closing
