### ISSUE TITLE
Circular structure error in LoadRunner

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#1979]
**Codewind version:**
latest
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
When running load against a project I had also displayed all the logs for I got the following stack trace in the pfe container logs:
```
[03/02/20 11:53:50 /portal/routes/projects/loadtest.route.js] [ERROR] TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at LoadRunner.runLoad (/portal/modules/LoadRunner.js:169:42)
    at User.runLoad (/portal/modules/User.js:180:49)
```
This is probably because we removed the `toJSON` function from Project.js. We may need to re-implement this but make more obvious in the code that it is the mechanism by which we filter out fields we don't want to persist.

We removed toJSON in:
https://github.com/eclipse/codewind/pull/1941 

**Steps to reproduce:**
- Create a project.
- Select show all logs.
- Open the performance dashboard and start a load run.

**Workaround:** 
Disable all logs before starting the load run.

**Comment by hhellyer** [comment]
I've verified that I can now run load against a project that has logging enabled on master. 
#1994 should be fixed but this should still be validated by the raiser.
