### ISSUE TITLE
SVT:Project list gone from codewind che workspace 

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1994]
**Codewind version:** 0.9.0 , latest
**OS:**

**Che version:** 7.5.1
**IDE extension version:**  0.9.0, latest
**IDE version:** 7,5,1
**Kubernetes cluster:**
OCP 4.3

**Description:**
I created bunch of default projects in my OCP 4.3 cluster. After few mins of building my projects and I lost project list from the codewind che workspace. 

```
root INFO [hosted-plugin: 374] [INFO: 19:19:22.724 CWEnvironment.js:36]: Massaged ENV data { version: 'x.x.dev',
  socketNamespace: 'default',
  tektonStatus: { status: false, message: 'not-installed', url: '' } }
root INFO [hosted-plugin: 374] [INFO: 19:19:22.725 MCSocket.js.MCSocket():178]: Creating MCSocket for URI https://localhost:9090/default
root INFO [hosted-plugin: 374] [DBUG: 19:19:22.725 MCSocket.js.MCSocket():187]: MCSocket @ https://localhost:9090/default does not require authorization
root INFO [hosted-plugin: 374] [INFO: 19:19:22.735 Connection.js:150]: In theia; no filewatcher required
root INFO [hosted-plugin: 374] [DBUG: 19:19:22.736 Connection.js:101]: Updating projects list after ready
[DBUG: 19:19:22.736 Requester.js:474]: Doing GET request to https://localhost:9090/api/v1/projects
root ERROR [hosted-plugin: 374] [ERRO: 19:19:22.758 Connection.js:105]: Error updating projects list after ready { StatusCodeError: 500 - {}
    at new StatusCodeError (/tmp/vscode-unpacked/eclipse.codewind-theia.latest.tviwtzrjzr.codewind-theia.vsix/extension/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/vscode-unpacked/eclipse.codewind-theia.latest.tviwtzrjzr.codewind-theia.vsix/extension/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/vscode-unpacked/eclipse.codewind-theia.latest.tviwtzrjzr.codewind-theia.vsix/extension/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/vscode-unpacked/eclipse.codewind-theia.latest.tviwtzrjzr.codewind-theia.vsix/extension/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/tmp/vscode-unpacked/eclipse.codewind-theia.latest.tviwtzrjzr.codewind-theia.vsix/extension/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/tmp/vscode-unpacked/eclipse.codewind-theia.latest.tviwtzrjzr.codewind-theia.vsix/extension/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - {}',
  error: {},
```

**Steps to reproduce:**
1. Install latest codewind on OCP 4.3 cluster.
2. Create bunch of default project for each template.
3. After few minutes of building my applications then I lost projects from the list and it shows nothing in the list.

![image](https://user-images.githubusercontent.com/713849/73683483-4f6d0080-4690-11ea-9f0f-d10968a1f34c.png)

logs --
[pfe.txt](https://github.com/eclipse/codewind/files/4149737/pfe.txt)
[theia.txt](https://github.com/eclipse/codewind/files/4149738/theia.txt)

**Workaround:**

**Comment by tetchel** [comment]
The server didn't send the 500 error's message but I'm guessing the error is the one at line 2075, since it's for the `projects` route. It's the circular JSON problem seen in #1875. 

```
[91m[03/02/20 18:48:54 /portal/routes/projects/projects.route.js] [ERROR][39m TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (/portal/node_modules/express/lib/response.js:1122:12)
    at ServerResponse.json (/portal/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/portal/node_modules/express/lib/response.js:158:21)
    at router.get (/portal/routes/projects/projects.route.js:45:21)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/portal/node_modules/express/lib/router/layer.js:95:5)
    at next (/portal/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/portal/node_modules/express/lib/router/route.js:112:3)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
```

**Comment by sujeilyfonseca** [comment]
**Codewind version:** Latest
**OS:** Mac OS Mojave 10.14.6

**IDE extension version:** 0.9.0
**IDE version:** Code 1.41.1

I consider this can be a similar problem. I obtained an unhandled 500 error when using a remote connection in VS Code. My projects suddenly disappeared, and Codewind couldn’t refresh the connection:

<img width="1675" alt="Screen Shot 2020-02-03 at 12 19 47 PM" src="https://user-images.githubusercontent.com/49531960/73684785-df13ae80-4692-11ea-9fb5-e754d6c78fb9.png">

<img width="1668" alt="Screen Shot 2020-02-03 at 11 58 42 AM" src="https://user-images.githubusercontent.com/49531960/73684825-f5ba0580-4692-11ea-98b6-d5df74977df2.png">

[codewind-pfe.txt](https://github.com/eclipse/codewind/files/4149799/codewind-pfe.txt)
[codewind.log](https://github.com/eclipse/codewind/files/4149826/codewind.log)

**Comment by hhellyer** [comment]
I think this was probably already fixed under: https://github.com/eclipse/codewind/pull/1981 which was merged this morning. Could you update to the latest and confirm you still see it?

**Comment by malincoln** [comment]
@jagraj pls verify and close. Thanks

**Comment by jagraj** [comment]
Looking good with 1981 fix, I no longer see this problem with the latest drivers. Closing this issue for now. I will reopen if we still see this problem in our 0.9.0 test effort.
