### ISSUE TITLE
Can't install hybrid Codewind on CodeReady Containers

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#2045]
**Codewind version:** latest
**Kubernetes cluster:** CodeReady Containers (CRC) 1.5.0 / OCP 4.2

**Description:**
CodeReady Containers (CRC) is Red Hat's local OpenShift 4.x offering. I've been trying to install hybrid Codewind on it with no luck.

First, installing Keycloak and PFE into the same namespace (with `oc adm policy` commands issued), caused Keycloak to never come up (logs attached)
```
johns-mbp-3:latest johncollier$ ./cwctl --insecure install remote \
>     --namespace codewind \
>     --kadminuser admin \
>     --kadminpass admin \
>     --krealm codewind \
>     --kclient codewind \
>     --kdevuser developer \
>     --kdevpass developer \
>     --ingress codewind.apps-crc.testing
INFO[0000] Checking namespace codewind exists           
INFO[0000] Using namespace : codewind                   
INFO[0000] Container images :                           
INFO[0000] eclipse/codewind-pfe-amd64:latest            
INFO[0000] eclipse/codewind-performance-amd64:latest    
INFO[0000] eclipse/codewind-keycloak-amd64:latest       
INFO[0000] eclipse/codewind-gatekeeper-amd64:latest     
INFO[0000] Running on openshift: true                   
INFO[0000] Using ingress domain: codewind.apps-crc.testing 
INFO[0000] Creating service account definition 'codewind-k69p0kpd' 
INFO[0000] Creating service account definition 'keycloak-k69p0kpd' 
INFO[0000] Creating codewind-keycloak-k69p0kpd.codewind.apps-crc.testing server Key 
INFO[0000] Creating codewind-keycloak-k69p0kpd.codewind.apps-crc.testing server certificate 
INFO[0000] Creating Codewind Keycloak PVC               
INFO[0000] Deploying Codewind Keycloak Secrets          
INFO[0000] Deploying Codewind Keycloak TLS Secrets      
INFO[0000] Waiting for pod: codewind-keycloak-k69p0kpd  
INFO[0000] codewind-keycloak-k69p0kpd, phase: Pending   
INFO[0000] codewind-keycloak-k69p0kpd, phase: Pending ContainersNotReady  
INFO[0007] codewind-keycloak-k69p0kpd, phase: Pending ContainersNotReady  
INFO[0009] codewind-keycloak-k69p0kpd, phase: Running   
INFO[0009] Waiting for Keycloak to start                
................................
```

```
johns-mbp-3:latest johncollier$ oc logs codewind-keycloak-k69p0kpd-888446668-pmmcj
Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
-b 0.0.0.0
=========================================================================

  Using Embedded H2 database

=========================================================================

=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss/keycloak

  JAVA: java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED

=========================================================================

19:17:40,686 INFO  [org.jboss.modules] (main) JBoss Modules version 1.9.1.Final
java.lang.IllegalStateException: WFLYSRV0126: Could not create server content directory: /opt/jboss/keycloak/standalone/data/content
	at org.jboss.as.server@10.0.0.Final//org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:482)
	at org.jboss.as.server@10.0.0.Final//org.jboss.as.server.Main.determineEnvironment(Main.java:388)
	at org.jboss.as.server@10.0.0.Final//org.jboss.as.server.Main.main(Main.java:96)
	at org.jboss.modules.Module.run(Module.java:352)
	at org.jboss.modules.Module.run(Module.java:320)
	at org.jboss.modules.Main.main(Main.java:593)
19:17:41,473 FATAL [org.jboss.as.server] (main) WFLYSRV0239: Aborting with exit code 1
```

I suspected this may have been related to the `oc adm` commands I ran, so I tried installing Keycloak in its own namespace, also to no luck:
```
johns-mbp-3:latest johncollier$ ./cwctl --insecure install remote \
>     --namespace keycloak \
>     --kadminuser admin \
>     --kadminpass admin \
>     --krealm codewind \
>     --kclient codewind \
>     --kdevuser developer \
>     --kdevpass developer \
>     --ingress keycloak.apps-crc.testing \
>     --konly
```

This time, Keycloak **does** start (and I can access its route perfectly), but cwctl never detects this and the install eventually times out. 

**Steps to reproduce:**
1. Install CodeReady Containers: https://github.com/code-ready/crc
2. Download `cwctl`
3. Run the `oc adm policy` commands in the codewind namespace
4. Install keycloak into the `keycloak namespace:
   ```
   ./cwctl --insecure install remote \
    --namespace keycloak \
    --kadminuser admin \
    --kadminpass admin \
    --krealm codewind \
    --kclient codewind \
    --kdevuser developer \
    --kdevpass developer \
    --ingress keycloak.apps-crc.testing \
    --konly
   ```
5. The install will hang on waiting for keycloak to come up. Despite this, keycloak will have come up fine, and its logs won't show any errors.

**Workaround:**

**Comment by johnmcollier** [comment]
@markcor11 FYI

**Comment by markcor11** [comment]
I was able to successfully deploy Codewind and Keycloak into CodeReady containers when Keycloak and Codewind were in different namespaces :

![image](https://user-images.githubusercontent.com/28102564/74338987-153fe500-4d9b-11ea-9303-70f51cc6e6e3.png)

I did need to create the Codewind namespace before running the two OC adm commands and apply them JUST to the Codewind namespace not the Keycloak namespace: 

```
oc adm policy add-scc-to-group privileged system:serviceaccounts:{codewindNamespace}
and
oc adm policy add-scc-to-group anyuid system:serviceaccounts:{codewindNamespace}
```

This requirement of separate namespaces for Keycloak and Codewind came out of a similar issue seen in ROKS with respect to storage permissions for the Keycloak container.

**Comment by markcor11** [comment]
I think this can be closed now.  Docs have been updated and we have an alternative method of installing codewind using the new Operator.

/close
