### ISSUE TITLE
SVT: [IntelliJ] If Codewind is uninstalled for the first time, users will continue to see the "Uninstall" option if they right-click on the local tree

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2240]
**Codewind version:** 0.9.0
**OS:** VM with Windows 10

**IDE extension version:** 0.9.0
**IDE version:**
<img width="319" alt="Screen Shot 2020-02-13 at 12 45 49 PM" src="https://user-images.githubusercontent.com/49531960/74462840-decb9e00-4e5e-11ea-94e6-d09bc4f0d973.png">

**Description:** If Codewind is uninstalled for the first time, users will continue to see the "Uninstall" option if they right-click on the local tree. If they click "Uninstall" again, they will receive an error. After that, Codewind seems to be uninstalled in the IDE, although it was uninstalled the first time.

![Screen Shot 2020-02-17 at 4 17 07 PM](https://user-images.githubusercontent.com/49531960/74687022-3a6c9300-51a1-11ea-962f-6674f8c4dbc4.png)

![Screen Shot 2020-02-17 at 4 17 14 PM](https://user-images.githubusercontent.com/49531960/74687028-3c365680-51a1-11ea-9b0a-32e6a05524fa.png)

![Screen Shot 2020-02-17 at 4 17 25 PM](https://user-images.githubusercontent.com/49531960/74687032-3d678380-51a1-11ea-8bb7-1f87409edb88.png)

![Screen Shot 2020-02-17 at 4 19 49 PM](https://user-images.githubusercontent.com/49531960/74687094-69830480-51a1-11ea-9c9c-988823d62ba4.png)

```
2020-02-17 16:16:20,394 [2334142]   INFO - .connection.CodewindConnection - Disconnecting connection: CodewindConnection @ name=Local baseUrl=http://127.0.0.1:10000/ conid=local 
2020-02-17 16:16:20,653 [2334401]   INFO - wind.intellij.core.cli.CLIUtil - C:\Users\Administrator\.codewind\0.9.0\cwctl.exe stop-all 
2020-02-17 16:16:49,212 [2362960]   INFO - wind.intellij.core.cli.CLIUtil - C:\Users\Administrator\.codewind\0.9.0\cwctl.exe --json status 
2020-02-17 16:16:49,737 [2363485]   INFO - .connection.CodewindConnection - Disconnecting connection: CodewindConnection @ name=Local baseUrl=http://127.0.0.1:10000/ conid=local 
2020-02-17 16:16:49,738 [2363486]   INFO - wind.intellij.core.cli.CLIUtil - C:\Users\Administrator\.codewind\0.9.0\cwctl.exe remove -t 0.9.0 
2020-02-17 16:16:57,269 [2371017]   INFO - wind.intellij.core.cli.CLIUtil - C:\Users\Administrator\.codewind\0.9.0\cwctl.exe --json status 
2020-02-17 16:16:57,794 [2371542]   INFO - .connection.CodewindConnection - Disconnecting connection: CodewindConnection @ name=Local baseUrl=unknown conid=local 
2020-02-17 16:17:15,550 [2389298]   INFO - .connection.CodewindConnection - Disconnecting connection: CodewindConnection @ name=Local baseUrl=unknown conid=local 
2020-02-17 16:17:15,802 [2389550]   INFO - wind.intellij.core.cli.CLIUtil - C:\Users\Administrator\.codewind\0.9.0\cwctl.exe stop-all 
2020-02-17 16:17:19,838 [2393586]   INFO - wind.intellij.core.cli.CLIUtil - C:\Users\Administrator\.codewind\0.9.0\cwctl.exe --json status 
2020-02-17 16:17:20,364 [2394112]   INFO - .connection.CodewindConnection - Disconnecting connection: CodewindConnection @ name=Local baseUrl=unknown conid=local 
2020-02-17 16:17:20,366 [2394114]   WARN - j.ui.tasks.CodewindProcessTask - An error occurred starting Codewind:  
java.lang.NullPointerException
	at org.eclipse.codewind.intellij.core.cli.InstallStatus.getVersionList(InstallStatus.java:157)
	at org.eclipse.codewind.intellij.core.cli.InstallStatus.getInstalledVersions(InstallStatus.java:147)
	at org.eclipse.codewind.intellij.ui.tasks.UninstallCodewindTask.runProcess(UninstallCodewindTask.java:43)
	at org.eclipse.codewind.intellij.ui.tasks.CodewindProcessTask.run(CodewindProcessTask.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-02-17 16:17:32,872 [2406620]   INFO - j.ide.actions.RevealFileAction - 
Exit code 1 
```

@jagraj

**Comment by jopit** [comment]
The fix for https://github.com/eclipse/codewind/issues/2275 will also fix this issue.

**Comment by jopit** [comment]
Fixed via PR https://github.com/eclipse/codewind-intellij/pull/66

**Comment by malincoln** [comment]
@sujeilyfonseca pls verify and close. Thanks

**Comment by sujeilyfonseca** [comment]
I've verified this issue with the latest Codewind 0.10.0, and I no longer reproduce the problem.

<img width="683" alt="Screen Shot 2020-03-12 at 3 01 19 PM" src="https://user-images.githubusercontent.com/49531960/76557721-6e6e6780-6472-11ea-8ead-425753d339fe.png">
