### ISSUE TITLE
Error in codewind-checluster.yaml when trying to install che

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2287]
**Codewind version:** 0.9
**OS:**.  CHE

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

When following the instructions to install eclipse che https://www.eclipse.org/codewind/mdt-che-installinfo.html.  I get the following error when running 

_chectl server:start --platform=openshift --installer=operator --che-operator-cr-yaml=codewind-checluster.yaml --che-operator-image=quay.io/eclipse/che-operator:7.5.1_

 ```
   ✖ Create Eclipse Che Cluster eclipse-che in namespace che
      →                                          ^
YAMLException: end of the stream or a document separator is expected at line 114, column 71:
     ... r-bar top-0 left-0" style="width: 0%;"></span>
                                         ^
    at generateError (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readDocument (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:1539:5)
    at loadDocuments (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at load (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at Object.safeLoad (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:1618:10)
    at KubeHelper.safeLoadFromYamlFile (/usr/local/lib/chectl/lib/api/kube.js:1448:21)
    at KubeHelper.<anonymous> (/usr/local/lib/chectl/lib/api/kube.js:1036:31)
    at Generator.next (<anonymous>)
    at /usr/local/lib/chectl/node_modules/tslib/tslib.js:110:75
```

**Steps` to reproduce:**

follow the eclipse che install instructions on codewind.dev

**Workaround:**

**Comment by johnmcollier** [comment]
@AndyRWatson Are you making sure to download the CheCluster yaml first to your machine?

**Comment by AndyRWatson** [comment]
Yep @johnmcollier if I dont have the file I dont get that far in the script.   I have tried again and same error,   I have copied the url from codewind.dev and downlaoded via curl 

```  Andys-MacBook-Pro:che2 watsona$ curl https://github.com/eclipse/codewind-che-plugin/blob/0.9.0/setup/install_che/che-operator/codewind-checluster.yaml --output ./codewind-checluster.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  103k    0  103k    0     0   124k      0 --:--:-- --:--:-- --:--:--  123k
Andys-MacBook-Pro:che2 watsona$ chectl server:start --platform=openshift --installer=operator --che-operator-cr-yaml=codewind-checluster.yaml --che-operator-image=quay.io/eclipse/che-operator:7.5.1
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
Eclipse Che logs will be available in '/var/folders/p9/2448l1q97r5g3psm4c4cl8080000gn/T/chectl-logs/1582346603290'
  ✔ Start following logs
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
 ›   Warning: Eclipse Che will be deployed in Multi-User mode since Configured 'operator' installer which support only such.
  ❯ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...It already exists.
    ✔ Create ServiceAccount che-operator in namespace che...It already exists.
    ✔ Create Role che-operator in namespace che...It already exists.
    ✔ Create ClusterRole che-operator...It already exists.
    ✔ Create RoleBinding che-operator in namespace che...It already exists.
    ✔ Create ClusterRoleBinding che-operator...It already exists.
    ✔ Create CRD checlusters.org.eclipse.che...It already exists.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace che...It already exists.
    ✖ Create Eclipse Che Cluster eclipse-che in namespace che
      →                                          ^
YAMLException: end of the stream or a document separator is expected at line 114, column 71:
     ... r-bar top-0 left-0" style="width: 0%;"></span>
                                         ^
    at generateError (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readDocument (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:1539:5)
    at loadDocuments (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at load (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at Object.safeLoad (/usr/local/lib/chectl/node_modules/js-yaml/lib/js-yaml/loader.js:1618:10)
    at KubeHelper.safeLoadFromYamlFile (/usr/local/lib/chectl/lib/api/kube.js:1448:21)
    at KubeHelper.<anonymous> (/usr/local/lib/chectl/lib/api/kube.js:1036:31)
    at Generator.next (<anonymous>)
    at /usr/local/lib/chectl/node_modules/tslib/tslib.js:110:75 ```

**Comment by AndyRWatson** [comment]
also looking at the docs we dont really explain how to get the file.   I curl'd out of choice but would a user necessarily know to do that ?   

Reading the instructions it say 

```Download the [codewind-checluster.yaml](https://github.com/eclipse/codewind-che-plugin/blob/0.9.0/setup/install_che/che-operator/codewind-checluster.yaml) file. ```

which is the github page and assumes I know how to download the raw file.  If I clicked download linked file (safari) or save link as (mozilla) I end up with the file with a .html file extension.

**Comment by johnmcollier** [comment]
@AndyRWatson Yeah, you’re right we should be linking to the raw yaml.

We should also probably make the download instructions more clear.

**Comment by sishida** [comment]
@AndyRWatson, @johnmcollier, Hi, team, It looks like the doc page has been updated since this issue was opened.

From [Installing Eclipse Che for Codewind](https://www.eclipse.org/codewind/che-installinfo.html), you can click the link in "After you install chectl, download the codewind-checluster.yaml file.", which takes you here: https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.12.0/setup/install_che/che-operator/codewind-checluster.yaml

Do we want any further changes to the [Installing Eclipse Che for Codewind](https://www.eclipse.org/codewind/che-installinfo.html) file? Or could we close this issue? Thank you! :)

**Comment by AndyRWatson** [comment]
Happy to close as fixed @sishida
