### ISSUE TITLE
Can't set image registry on Kubernetes

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#2304]
**Codewind version:**
master (possibly 0.8.0 as well)
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**
Open shift via Code Ready. (crc)
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"4320e48", GitTreeState:"clean", BuildDate:"2020-01-21T19:50:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Description:**
I was unable to set an image registrty, the PFE logs showed:
```
[25/02/20 11:39:07 User.js] [ERROR] { Error: secrets "codewind-k71teu90-docker-registries" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
    at _request (/portal/node_modules/kubernetes-client/lib/backends/request.js:189:25)
    at Request.request [as _callback] (/portal/node_modules/kubernetes-client/lib/backends/request.js:148:14)
    at Request.self.callback (/portal/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/portal/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/portal/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12) code: 403, statusCode: 403 }
[25/02/20 11:39:07 User.js] [ERROR] Failed to create the Codewind Secret
[25/02/20 11:39:07 /portal/routes/registrySecrets.route.js] [ERROR] { RegistrySecretsError: Failed to create the Codewind Secret
for address docker.io
    at User.setupRegistrySecret (/portal/modules/User.js:785:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'RegistrySecretsError',
  code: 'SECRET_CREATE_FAILED',
  info:
   { name: 'RegistrySecretsError',
     code: 'SECRET_CREATE_FAILED',
     message: 'Failed to create the Codewind Secret for address docker.io' } }
```

**Steps to reproduce:**
Connect the VSCode plugin to the remote kubernetes instance of Codewind.
Attempt to setup an Image registry. (docker.io)

**Workaround:** 
I reverted this line, pushed an image with that change to dockerhub and edited my deployment to use that image instead:
https://github.com/eclipse/codewind/commit/ee48edcceddae513116def7402a18b130e55a955#diff-196bc19c851941ec243f92f82a372914R827

**Comment by tobespc** [comment]
I see this on my openshift 4.3 machines

```[25/02/20 12:58:44 User.js] [ERROR] { Error: secrets "codewind-k71ulry2-docker-registries" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
    at _request (/portal/node_modules/kubernetes-client/lib/backends/request.js:189:25)
    at Request.request [as _callback] (/portal/node_modules/kubernetes-client/lib/backends/request.js:148:14)
    at Request.self.callback (/portal/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/portal/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/portal/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12) code: 403, statusCode: 403 }
[25/02/20 12:58:44 User.js] [ERROR] Failed to create the Codewind Secret
[25/02/20 12:58:44 User.js] [ERROR] Reverting changes to the Docker Config
[25/02/20 12:58:44 User.js] [INFO] Creating a Secret and patching the Service Account
[25/02/20 12:58:44 User.js] [INFO] The Docker config file exists, reading contents
[25/02/20 12:58:44 User.js] [ERROR] { Error: secrets "codewind-k71ulry2-docker-registries" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
    at _request (/portal/node_modules/kubernetes-client/lib/backends/request.js:189:25)
    at Request.request [as _callback] (/portal/node_modules/kubernetes-client/lib/backends/request.js:148:14)
    at Request.self.callback (/portal/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/portal/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/portal/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12) code: 403, statusCode: 403 }
[25/02/20 12:58:44 User.js] [ERROR] Failed to create the Codewind Secret
[25/02/20 12:58:44 /portal/routes/registrySecrets.route.js] [ERROR] { RegistrySecretsError: Failed to create the Codewind Secret
for address docker.io
    at User.setupRegistrySecret (/portal/modules/User.js:785:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'RegistrySecretsError',
  code: 'SECRET_CREATE_FAILED',
  info:
   { name: 'RegistrySecretsError',
     code: 'SECRET_CREATE_FAILED',
     message: 'Failed to create the Codewind Secret for address docker.io' } }
[25/02/20 12:58:44 User.js] [INFO] Docker Config file present, returning the Docker Registry List
[25/02/20 12:58:45 User.js] [INFO] Checking PFE & workspace settings image push registry
[25/02/20 12:58:45 User.js] [INFO] Registry address or registry namespace not found in the workspace settings file
[25/02/20 12:58:45 User.js] [INFO] Workspace settings image push registry status: false
```

**Comment by johnmcollier** [comment]
This is because https://github.com/eclipse/codewind/pull/2295 was merged without merging https://github.com/eclipse/codewind-installer/pull/381 and https://github.com/eclipse/codewind-che-plugin/pull/148 first.

I probably should have added a note to https://github.com/eclipse/codewind/pull/2295 to mention not to merge it, my bad.

**Comment by sujeilyfonseca** [comment]
I see this error with my OKD 3.11 and 4.2 clusters. My tests agains latest were failing to create image registries:

![Screen Shot 2020-02-25 at 4 23 16 PM](https://user-images.githubusercontent.com/49531960/75289158-b3946780-57eb-11ea-97ac-355372660c43.png)

```
[25/02/20 21:22:57 User.js] [ERROR] { Error: secrets "codewind-workspaceo0mcccmh1hyaugx4-docker-registries" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>
    at _request (/portal/node_modules/kubernetes-client/lib/backends/request.js:189:25)
    at Request.request [as _callback] (/portal/node_modules/kubernetes-client/lib/backends/request.js:148:14)
    at Request.self.callback (/portal/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/portal/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/portal/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12) code: 403, statusCode: 403 }
[25/02/20 21:22:57 User.js] [ERROR] Failed to create the Codewind Secret
[25/02/20 21:22:57 User.js] [ERROR] Reverting changes to the Docker Config
[25/02/20 21:22:57 User.js] [INFO] Creating a Secret and patching the Service Account
[25/02/20 21:22:57 User.js] [INFO] The Docker config file exists, reading contents
[25/02/20 21:22:57 User.js] [ERROR] { Error: secrets "codewind-workspaceo0mcccmh1hyaugx4-docker-registries" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>
    at _request (/portal/node_modules/kubernetes-client/lib/backends/request.js:189:25)
    at Request.request [as _callback] (/portal/node_modules/kubernetes-client/lib/backends/request.js:148:14)
    at Request.self.callback (/portal/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/portal/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/portal/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12) code: 403, statusCode: 403 }
[25/02/20 21:22:57 User.js] [ERROR] Failed to create the Codewind Secret
[25/02/20 21:22:57 /portal/routes/registrySecrets.route.js] [ERROR] { RegistrySecretsError: Failed to create the Codewind Secret
for address docker.io
    at User.setupRegistrySecret (/portal/modules/User.js:784:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'RegistrySecretsError',
  code: 'SECRET_CREATE_FAILED',
  info:
   { name: 'RegistrySecretsError',
     code: 'SECRET_CREATE_FAILED',
     message: 'Failed to create the Codewind Secret for address docker.io' } }
```

**Comment by sujeilyfonseca** [comment]
After applying the latest cluster role:

`kubectl apply -f https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/setup/install_che/codewind-clusterrole.yaml`

I no longer see this problem with the latest Codewind.
