### ISSUE TITLE
[Eclipse IDE] App overview still displays if stop/disconnect Codewind

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2424]
Any application overview pages still display after stopping local Codewind or disconnecting from a remote Codewind. This might be ok since the loss of connection could be temporary and it would not be nice to close all of the user's overview pages but the Refresh button throws an NPE if clicked. If Refresh clicked, could pop up a dialog to say the connection is not available and ask them if they want to close the overview page.
```
java.lang.NullPointerException
	at org.eclipse.codewind.ui.internal.editors.ApplicationOverviewEditorPart$3.widgetSelected(ApplicationOverviewEditorPart.java:263)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3986)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3585)
        ...
```

**Comment by eharris369** [comment]
The best thing to do here would be to display the message composite similar to when Eclipse is starting and the connections have not been re-established yet (see the ApplicationOverviewEditorPart update method). Another issue is that applications aren't updated if the connection is lost because it gets the applications from the connection. Changes were made to the UpdateHandler class for #2169 which will make this easier to fix.
