### ISSUE TITLE
Remove project error when removing a project that is in debug mode

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#2450]
**Codewind version:** 0.9.0
**OS:** Mac OS

**IDE extension version:** Eclipse codewind 0.9.0 / latest, IntelliJ as well
**IDE version:** Any supported Eclipse version, latest IntelliJ

**Description:**
Local. Try removing a Codewind MicroProfile project that is running in debug mode.  You will get an error message:

An error occurred trying to remove the XYZ project from Codewind.
Project unbind failed with status code 202

**Comment by tetchel** [comment]
this is the same issue as https://github.com/eclipse/codewind/issues/2193#issuecomment-595232320 and should have been fixed this morning

**Comment by keithchong** [comment]
Codewind for Eclipse trace:
java.io.IOException: Project unbind failed with status code 202
	at org.eclipse.codewind.core.internal.cli.CLIUtil.checkResult(CLIUtil.java:198)
	at org.eclipse.codewind.core.internal.cli.ProjectUtil.removeProject(ProjectUtil.java:114)
	at org.eclipse.codewind.ui.internal.actions.UnbindProjectAction$2.run(UnbindProjectAction.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by keithchong** [comment]
Confirmed. It is fixed in master.
