### ISSUE TITLE
'Deployment Registry route tests' are failing on PR builds

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#252]
I've had to comment these tests out as they are failing on PR builds now that Jenkins runs our test suite. They need to be investigated for the failure reason and enabled again when fixed

**Comment by maysunfaisal** [comment]
@tobespc Hi, how can I access the logs?

**Comment by tobespc** [comment]
if you click on the build link when the PR goes up, you can see the jenkins build and get the logs from there.  For info, this is one that shows the failure
https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/PR-59/36/consoleFull

```
13:43:31    1) Deployment Registry route tests
13:43:31         GET /api/v1/registry
13:43:31           should return false with a bad JSON in ${workspace_location}/.config/settings.json:
13:43:31  
13:43:31        AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
13:43:31        + expected - actual
13:43:31  
13:43:31        -500
13:43:31        +200
13:43:31        
13:43:31        at Context.<anonymous> (src/registry.test.js:123:29)
13:43:31        at process._tickCallback (internal/process/next_tick.js:68:7)
13:43:31  
13:43:31  
```
