### ISSUE TITLE
[Eclipse IDE] NPE in ProjectSelectionPage.validate when user types in path

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2592]
The following NPE occurs when the user is typing in the path for the project in the Project Selection page of the Add Existing Project wizard. The NPE only appears in the workspace .log file.

java.lang.NullPointerException
        at org.eclipse.core.runtime.Path.<init>(Path.java:209)
        at org.eclipse.core.internal.resources.WorkspaceRoot.getProject(WorkspaceRoot.java:148)
        at org.eclipse.codewind.ui.internal.wizards.ProjectSelectionPage.validate(ProjectSelectionPage.java:306)
        at org.eclipse.codewind.ui.internal.wizards.ProjectSelectionPage.access$4(ProjectSelectionPage.java:276)
        at org.eclipse.codewind.ui.internal.wizards.ProjectSelectionPage$6.modifyText(ProjectSelectionPage.java:194)

**Comment by eharris369** [comment]
Fixed by PR: https://github.com/eclipse/codewind-eclipse/pull/684
