### ISSUE TITLE
SVT : lots of this message : The Tekton dashboard URL is not valid:

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#261]
@mmulholl commented on [Thu Aug 22 2019](https://github.com/eclipse/codewind-eclipse/issues/226)

Running SWTBot tests for teh eclipse plugin I get this exception in the console log every time a new window is opened which is a lot. Probably being reported by eclispe but is there anything we can do? 

!ENTRY org.eclipse.codewind.core 4 0 2019-08-22 10:47:57.707
!MESSAGE [ERROR ConnectionEnv.getTektonDashboardURL:80] The Tekton dashboard URL is not valid: not-installed
!STACK 0
java.net.MalformedURLException: no protocol: not-installed
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.eclipse.codewind.core.internal.connection.ConnectionEnv.getTektonDashboardURL(ConnectionEnv.java:78)
	at org.eclipse.codewind.core.internal.connection.CodewindConnection.getTektonDashboardURL(CodewindConnection.java:827)
	at org.eclipse.codewind.ui.internal.actions.OpenTektonDashboardAction.showAction(OpenTektonDashboardAction.java:93)
	at org.eclipse.codewind.ui.internal.actions.CodewindApplicationActionProvider.fillContextMenu(CodewindApplicationActionProvider.java:76)
	at org.eclipse.ui.navigator.NavigatorActionService$2.run(NavigatorActionService.java:228)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.navigator.NavigatorActionService.addCommonActionProviderMenu(NavigatorActionService.java:222)
	at org.eclipse.ui.navigator.NavigatorActionService.fillContextMenu(NavigatorActionService.java:177)
	at org.eclipse.ui.navigator.CommonNavigatorManager.fillContextMenu(CommonNavigatorManager.java:258)
	at org.eclipse.ui.navigator.CommonNavigatorManager.lambda$1(CommonNavigatorManager.java:270)
	at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:341)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:471)
	at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:466)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:498)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)

**Comment by tetchel** [comment]
I changed the backend to respond with `not-installed` if it cannot access the tekton namespace. you should not see this in the local case, though, it should always be "" there. 🤔 

https://eclipse.github.io/codewind/#/paths/~1api~1v1~1environment/get
