### ISSUE TITLE
Non-docker Projects failed to sync files if previous build failed

### ISSUE THREAD

**Issue by yangcao77** [eclipse/codewind#2630]
**Codewind version:**
latest master branch
**OS:**
MacOs

**Che version:**
**IDE extension version:** 
latest master branch of vsCode extension
**IDE version:**
**Kubernetes cluster:**

**Description:**
For any non-docker projects, if a previous build has failed. Any change won't be synced; and therefore, no autobuild will get triggered. 

```
[07/04/20 18:01:11 /portal/routes/projects/remoteBind.route.js] [INFO] Project testnode syncing with build container, projectRoot is /app
[07/04/20 18:01:11 /portal/routes/projects/remoteBind.route.js] [ERROR] { Error: Command failed: docker cp /codewind-workspace/testnode/. 66da0d8ca77f840ef71b715aa83ddc67f6bf927e2d835bb5723281a515396808:/app
Error: No such container:path: 66da0d8ca77f840ef71b715aa83ddc67f6bf927e2d835bb5723281a515396808:/

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'docker cp /codewind-workspace/testnode/. 66da0d8ca77f840ef71b715aa83ddc67f6bf927e2d835bb5723281a515396808:/app',
  stdout: '',
  stderr:
   'Error: No such container:path: 66da0d8ca77f840ef71b715aa83ddc67f6bf927e2d835bb5723281a515396808:/\n' }
[07/04/20 18:01:11 /portal/routes/projects/remoteBind.route.js] [INFO] Project testnode syncing with build container, projectRoot is /app
[07/04/20 18:01:11 /portal/routes/projects/remoteBind.route.js] [ERROR] { Error: Command failed: docker cp /codewind-workspace/testnode/. 66da0d8ca77f840ef71b715aa83ddc67f6bf927e2d835bb5723281a515396808:/app
Error: No such container:path: 66da0d8ca77f840ef71b715aa83ddc67f6bf927e2d835bb5723281a515396808:/

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'docker cp /codewind-workspace/testnode/. 66da0d8ca77f840ef71b715aa83ddc67f6bf927e2d835bb5723281a515396808:/app',
  stdout: '',
  stderr:
   'Error: No such container:path: 66da0d8ca77f840ef71b715aa83ddc67f6bf927e2d835bb5723281a515396808:/\n' }

```

**Steps to reproduce:**
1. Create a nodejs project
2. Wait till it's up and running
3. Modify the Dockerfile to make it fail to build
4. Redo the change to Dockerfile. 
Check the  pfe logs, would see errors I posted above.

**Workaround:** 

Manual click build button
disable and re-enable the project

**Comment by tobespc** [comment]
ok, thanks, will take a look

**Comment by hhellyer** [comment]
I have raised https://github.com/eclipse/codewind/pull/2632 to resolve this, it handles the exception and continues so that file change notifications are sent correctly. It also catches the case where the container hasn't started and the `containerId` is `undefined`.
