### ISSUE TITLE
SVT: [VS Code] Failed to remove WebSphere Liberty MicroProfile projects in local and remote/hybrid scenarios

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2661]
**Codewind version:** 0.11.0
**OS:** VM with Windows 10

**IDE extension version:** 0.11.0
**IDE version:** Code 1.43.2

**Description:** Failed to remove WebSphere Liberty MicroProfile projects in local and remote/hybrid scenarios

_Remote:_ 

Failed to remove cw-remote-microprofile-011: Error running cwctl.exe project remove: open C:\Users\Administrator/.codewind/config/connections/3e7e6040-7aaa-11ea-a9a3-69f31742b3f7.json: The system cannot find the file specified.

![Screen Shot 2020-04-09 at 5 59 10 PM](https://user-images.githubusercontent.com/49531960/78944803-c063d680-7a8c-11ea-85a2-06bd9a94eff0.png)

```
[32m[09/04/20 21:59:13 User.js] [INFO][39m Removing project directory at /codewind-workspace/cw-remote-microprofile-011
[32m[09/04/20 21:59:14 Turbine] [INFO][39m No dangling images were found.
```

</br>

```
Directory: C:\Users\Administrator\.codewind\config\connections


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         4/9/2020  12:20 PM             49 08627680-7a7e-11ea-8878-4bef987a1b88.json
-a----         4/9/2020  12:20 PM             49 12a172e0-7a7e-11ea-8878-4bef987a1b88.json
-a----         4/9/2020  12:23 PM             49 695c5c30-7a7e-11ea-8878-4bef987a1b88.json
-a----         4/9/2020   5:13 PM             49 8f977570-7a7d-11ea-a737-e56bc29a21ae.json
-a----         4/9/2020  12:19 PM             49 eb43c810-7a7d-11ea-8878-4bef987a1b88.json
-a----         4/9/2020  12:19 PM             49 f25440d0-7a7d-11ea-8878-4bef987a1b88.json
-a----         4/9/2020  12:20 PM             49 fb708f20-7a7d-11ea-8878-4bef987a1b88.json
```

_Local:_

Failed to remove cw-local-default-microprofile-011: Error running cwctl.exe project remove: Project unbind failed with status code 409

![Screen Shot 2020-04-09 at 6 07 40 PM](https://user-images.githubusercontent.com/49531960/78945464-5b10e500-7a8e-11ea-8c0c-b42ba2ef9c29.png)

```
[09/04/20 22:07:00 cw-local-default-microprofile-011] [INFO] operationId: 5b9caeee2577c4bd3d9fb2b46d8b654e
[09/04/20 22:07:00 cw-local-default-microprofile-011] [INFO] containerDelete: Kill running processes and remove container...
[09/04/20 22:07:00 cw-local-default-microprofile-011] [INFO] Project ID:        eb43c810-7a7d-11ea-8878-4bef987a1b88
[09/04/20 22:07:00 cw-local-default-microprofile-011] [INFO] Project Location:  /codewind-workspace/cw-local-default-microprofile-011
[09/04/20 22:07:00 cw-local-default-microprofile-011] [INFO] Project Type:      liberty
[09/04/20 22:07:00 cw-local-default-microprofile-011] [INFO] Project Container: cw-cwlocaldefaultmicroprofile011-eb43c810-7a7d-11ea-8878-4bef987a1b88
[09/04/20 22:07:00 cw-local-default-microprofile-011] [INFO] projectInfo.deploymentRegistry: undefined
[09/04/20 22:07:01 /portal/routes/projects/remoteBind.route.js] [INFO] Removing locally deleted directories from project: cw-local-default-microprofile-011, ID: eb43c810-7a7d-11ea-8878-4bef987a1b88 - chart, src
[09/04/20 22:07:02 /portal/routes/projects/remoteBind.route.js] [INFO] Removing locally deleted files from project: cw-local-default-microprofile-011, ID: eb43c810-7a7d-11ea-8878-4bef987a1b88 - .cw-settings, Dockerfile, Dockerfile-build, Dockerfile-tools, README.md, pom.xml
[09/04/20 22:07:02 /portal/routes/projects/remoteBind.route.js] [WARN] { [Error: ENOENT: no such file or directory, stat '/codewind-workspace/cw-local-default-microprofile-011/pom.xml']
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path:
   '/codewind-workspace/cw-local-default-microprofile-011/pom.xml' }
[09/04/20 22:07:03 /portal/routes/projects/remoteBind.route.js] [ERROR] { Error: Command failed: docker exec 64235820853f91d97dce17f58b9c595e901ffcf53ecf8483c8e7723bf6083b9f rm -rf /home/default/app/.cw-settings
Error response from daemon: Container 64235820853f91d97dce17f58b9c595e901ffcf53ecf8483c8e7723bf6083b9f is not running

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'docker exec 64235820853f91d97dce17f58b9c595e901ffcf53ecf8483c8e7723bf6083b9f rm -rf /home/default/app/.cw-settings',
  stdout: '',
  stderr:
   'Error response from daemon: Container 64235820853f91d97dce17f58b9c595e901ffcf53ecf8483c8e7723bf6083b9f is not running\n' }
[09/04/20 22:07:11 cw-local-default-microprofile-011] [INFO] Project info cache is {"/file-watcher/fwdata/projects/f25440d0-7a7d-11ea-8878-4bef987a1b88/f25440d0-7a7d-11ea-8878-4bef987a1b88.json":"{\"projectID\":\"f25440d0-7a7d-11ea-8878-4bef987a1b88\",\"projectType\":\"spring\",\"location\":\"/codewind-workspace/cw-local-default-spring-011\",\"autoBuildEnabled\":true,\"startMode\":\"run\",\"appPorts\":[\"8080\"],\"language\":\"java\",\"debugPort\":\"7777\",\"ignoredPaths\":[\"*/.idea/*\",\"*.iml\",\"/.project\",\"/load-test*\",\"*/*.swp\",\"*/*.swx\",\"*/.gitignore\",\"*/node_modules*\",\"*/4913\",\"*/.git/*\",\"*/.DS_Store\",\"*/.dockerignore\",\"*/*~\",\"/.settings\",\"/.classpath\",\"/.options\",\"/.vscode/*\",\"/target\",\"/Dockerfile-tools\",\"/cli-config.yml\",\"/README.md\",\"/Jenkinsfile\",\"/.m2\",\"/localm2cache.zip\"],\"statusPingTimeout\":30,\"isHttps\":false,\"buildRequest\":false,\"sentProjectInfo\":true}"}
[09/04/20 22:07:11 cw-local-default-microprofile-011] [INFO] Successfully deleted eb43c810-7a7d-11ea-8878-4bef987a1b88
[09/04/20 22:07:11 Turbine] [INFO] Removing project logs directory
[09/04/20 22:07:11 Turbine] [INFO] Log directory removed from: /codewind-workspace/.logs/cw-local-default-microprofile-011-eb43c810-7a7d-11ea-8878-4bef987a1b88
[09/04/20 22:07:11 Turbine] [INFO] eb43c810-7a7d-11ea-8878-4bef987a1b88: Emitting event
 message: projectDeletion
 data: {
  "operationId": "5b9caeee2577c4bd3d9fb2b46d8b654e",
  "projectID": "eb43c810-7a7d-11ea-8878-4bef987a1b88",
  "status": "success"
}
[09/04/20 22:07:11 User.js] [INFO] Removing project directory at /codewind-workspace/cw-local-default-microprofile-011
```

</br>

**Logs:**
[remote-codewind-pfe.txt](https://github.com/eclipse/codewind/files/4458894/remote-codewind-pfe.txt)
[local-codewind-pfe.txt](https://github.com/eclipse/codewind/files/4458895/local-codewind-pfe.txt)

@jagraj

**Comment by tetchel** [comment]
Your log contains the same error as https://github.com/eclipse/codewind/issues/2630

I think this is a different issue though. I'm not sure what would cause the missing connection.json or the 409 status, so I guess Portal should take a look first.

**Comment by stalleyj** [comment]
So the log would suggest that there have been 2 requests to delete the project. The 409 error is returned to the second request with message "Delete for project ** already requested". Depending on the timing, the second request may receive the error for missing connection.json as this is the first thing cwctl retrieves. @sujeilyfonseca Can you describe the steps you go through to get this error ? Can you recreate every time ?

@tetchel I'm not sure how we could handle 2 requests to delete the project better, we could change the 409 error return possibly, thoughts ?

**Comment by tetchel** [comment]
Sujeily, is the same project (directory) bound to two different Codewind instances here? Maybe that is why PFE is confused (though I have never seen this issue with that scenario).

Julie, the 409 error itself is fine; it seems the problem is that the project is stuck in the 'deleting' state so subsequent requests fail.

**Comment by sujeilyfonseca** [comment]
@stalleyj - I can reproduce the scenario most of the time. I usually create some projects, and after my test ends, delete them. I can also reproduce the problem by creating one or two projects in local and hybrid scenarios, don't do anything else, and attempt to delete the projects.

I was consistently getting the same error messages. However, I attempted the scenario again today, and I got failures following the same procedures, but now I see a different message. 

<img width="1678" alt="Screen Shot 2020-04-20 at 11 43 16 AM" src="https://user-images.githubusercontent.com/49531960/79771047-3de4dd80-82fc-11ea-976e-14a173baa4cc.png">

Perhaps, maybe there is a standard message now for multiple scenarios, as I saw the same error message, but with different reproduction steps: https://github.com/eclipse/codewind/issues/2456

</br>

@tetchel - In my scenario, I only used one Codewind instance, using a VS Code IDE.

**Comment by tetchel** [comment]
There are two codewind instances in the screenshot, the local one and the remote one

**Comment by sujeilyfonseca** [comment]
Sorry, I misunderstood you. Yes, I have local and remote, but the same project is not bound to both. One WebSphere Liberty MicroProfile project was created locally, and a different one was created in the remote instance. You can also see that I used different names in the original screenshot.

**Comment by stalleyj** [comment]
The error message being seen about a missing 'connections.json' file for the project occurs when a project remove is requested but the async part fails. We are then left in a stuck state so I have implemented a recovery to this which would require a pfe restart to complete the deletion of the project.

**Comment by stalleyj** [comment]
This issue is a duplicate of https://github.com/eclipse/codewind/issues/2456 as the initial problem with delete is the same. I'm going to pass this one to Docs team to add info to the troubleshooting guide regarding how to recover from failed delete @micgibso

**Comment by micgibso** [comment]
Duplicate of an issue that's been closed in the interim. 
@tetchel Did your fix for #2456 resolve this too? @sujeilyfonseca Is this still an issue?

**Comment by tetchel** [comment]
I don't know if this is a dupe of 2456; the missing connection.json is a different issue. but if this issue isn't seen during windows testing then it is likely fixed.

**Comment by sujeilyfonseca** [comment]
I'll proceed to verify if this is still a problem.

**Comment by sujeilyfonseca** [comment]
Thank you so much for working to resolve this issue!

So far, I have not been able to reproduce the original problem using the latest Codewind 0.13.0. Therefore, I will proceed to close this issue.
