### ISSUE TITLE
Project creation fails in che due to 'no templates found'

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2723]
Codewind version: 0.11.0

@pdfruth reported consistently seeing a problem in CRW che where he couldn't create a project. Restarting the workspace fixes the problem but then it comes back.

The logs say:
```
[DBUG: 04:17:45.260 ]: Doing JSON GET request to https://localhost:9090/api/v1/templates
Extension-Host:[ERRO: 04:17:45.264 ]: Error creating new project:  { GotError: Cannot read property 'startsWith' of undefined
    at O (/tmp/vscode-unpacked/eclipse.codewind-theia.0.11.0.okshthcphc.codewind-che.vsix/extension/node_modules/got/dist/source/request-as-event-emitter.js:200:27)
    at urlToOptions (internal/url.js:1259:28)
    at Object.request (https.js:279:15)
    at Object.requestSymbol (/default-theia-plugins/vscode-builtin-npm/extension/dist/main.js:1:39537)
    at O (/tmp/vscode-unpacked/eclipse.codewind-theia.0.11.0.okshthcphc.codewind-che.vsix/extension/node_modules/got/dist/source/request-as-event-emitter.js:197:51) name: 'RequestError' }
```

This means the server is sending no response body, while the VS Code plugin expects a JSON array from /templates.

In the PFE logs he sees:
```
[21/04/20 12:48:40 /portal/routes/templates.route.js] [WARN] No templates found
```

It looks like PFE is hitting [this LOC](https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/templates.route.js#L32)

which should either be sending an error message (if 'no templates' is considered an error?) or an empty array if it is not an error. It should definitely not be sending a 204 status with no body.

But the real question here is, why are there no templates?

```
[21/04/20 12:19:06 /portal/routes/projects/loadtest.route.js] [INFO] LoadTest route: loadInProgress= undefined
[21/04/20 12:19:06 User.js] [INFO] runLoad: project 5e1c34d0-8384-11ea-8650-6f7ebcb5f49a loadInProgress was =undefined
[21/04/20 12:19:06 User.js] [INFO] runLoad: project 5e1c34d0-8384-11ea-8650-6f7ebcb5f49a loadInProgress now =true
[21/04/20 12:19:06 User.js] [INFO] Requesting load on project: 5e1c34d0-8384-11ea-8650-6f7ebcb5f49a config: {"method":"GET","path":"/","requestsPerSecond":"1","concurrency":"1","maxSeconds":"30","url":"http://172.30.95.30:7777/"}
[21/04/20 12:19:06 /portal/modules/LoadRunner.js] [INFO] Fetching project metrics features
[21/04/20 12:19:06 /portal/modules/LoadRunner.js] [INFO] Connection options:  {"host":"172.30.95.30","port":7777,"path":"/javametrics/api/v1/collections/features","method":"GET"}
[21/04/20 12:19:06 /portal/modules/LoadRunner.js] [ERROR] Unable to get project metrics features: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"172.30.95.30","port":7777}
[21/04/20 12:19:06 /portal/modules/LoadRunner.js] [INFO] createCollection: ID:5e1c34d0-8384-11ea-8650-6f7ebcb5f49a, Host:172.30.95.30, Port:7777, Path:/javametrics/api/v1/collections
[21/04/20 12:19:06 /portal/modules/LoadRunner.js] [ERROR] createCollection: Error in function createCollection
[21/04/20 12:19:06 /portal/modules/LoadRunner.js] [ERROR] { Error: connect ECONNREFUSED 172.30.95.30:7777
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.30.95.30',
  port: 7777 }
[21/04/20 12:19:06 /portal/modules/LoadRunner.js] [INFO] Load run on project 5e1c34d0-8384-11ea-8650-6f7ebcb5f49a started
[21/04/20 12:19:36 /portal/modules/LoadRunner.js] [INFO] Load run on project 5e1c34d0-8384-11ea-8650-6f7ebcb5f49a completed
[21/04/20 12:19:36 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/ta-repo/load-test/20200421121906
[21/04/20 12:19:36 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/ta-repo/load-test/20200421121906
[21/04/20 12:19:36 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/ta-repo/load-test/20200421121906
[21/04/20 12:19:36 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/ta-repo/load-test/20200421121906
[21/04/20 12:21:59 Templates.js] [INFO] Repository list updated.
[21/04/20 12:22:04 Templates.js] [INFO] Repository list updated.
[21/04/20 12:22:18 Templates.js] [INFO] Repository list updated.
[21/04/20 12:22:20 Templates.js] [INFO] Repository list updated.
[21/04/20 12:22:26 Templates.js] [INFO] Repository list updated.
[21/04/20 12:22:29 Templates.js] [INFO] Repository list updated.
[21/04/20 12:23:14 User.js] [INFO] Checking PFE & workspace settings image push registry
[21/04/20 12:23:14 User.js] [INFO] Registry address or registry namespace not found in the workspace settings file
[21/04/20 12:23:14 User.js] [INFO] Workspace settings image push registry status: false
[21/04/20 12:23:50 Templates.js] [INFO] Repository list updated.
[21/04/20 12:27:58 /portal/modules/FileWatcher.js] [INFO] ff000e40-831f-11ea-8650-6f7ebcb5f49a update start time: 1587472078315
[21/04/20 12:27:58 /portal/routes/projects/remoteBind.route.js] [INFO] Total time to sync project app-nodejs-express to build container is 0.138 seconds
[21/04/20 12:27:58 app-nodejs-express] [INFO] Project ff000e40-831f-11ea-8650-6f7ebcb5f49a file changed
[21/04/20 12:27:58 app-nodejs-express] [INFO] This project file changes will be ignored by Turbine. The project extension will decide if it needs to be rebuilt.
[21/04/20 12:28:04 Turbine] [INFO] Fetching logs for project ff000e40-831f-11ea-8650-6f7ebcb5f49a
[21/04/20 12:28:04 app-nodejs-express] [INFO] buildlog path:
 []
[21/04/20 12:28:04 app-nodejs-express] [INFO] applog path:
[{"origin":"workspace","files":["/codewind-workspace/.logs/app-nodejs-express-ff000e40-831f-11ea-8650-6f7ebcb5f49a/appsody.log"]}]
[21/04/20 12:28:59 /portal/modules/FileWatcher.js] [INFO] ff000e40-831f-11ea-8650-6f7ebcb5f49a update start time: 1587472139501
[21/04/20 12:28:59 /portal/routes/projects/remoteBind.route.js] [INFO] Total time to sync project app-nodejs-express to build container is 0.124 seconds
[21/04/20 12:28:59 app-nodejs-express] [INFO] Project ff000e40-831f-11ea-8650-6f7ebcb5f49a file changed
[21/04/20 12:28:59 app-nodejs-express] [INFO] This project file changes will be ignored by Turbine. The project extension will decide if it needs to be rebuilt.
[21/04/20 12:29:21 /portal/routes/templates.route.js] [WARN] No templates found
[21/04/20 12:34:21 /portal/routes/templates.route.js] [WARN] No templates found
[21/04/20 12:35:57 /portal/routes/templates.route.js] [WARN] No templates found
[21/04/20 12:44:56 /portal/routes/templates.route.js] [WARN] No templates found
[21/04/20 12:48:40 /portal/routes/templates.route.js] [WARN] No templates found
[21/04/20 12:57:42 /portal/routes/templates.route.js] [WARN] No templates found
```

**Comment by johnmcollier** [comment]
Should this be tagged hot if folks are seeing it in 0.11.0?

**Comment by tetchel** [comment]
gathered more info from the user, there are actually no templates enabled.

I'll leave this open because I will change the 'no templates' response (i'll likely change it myself), but this bug isn't so bad.

**Comment by tetchel** [comment]
erin pointed out I can just use cwctl to get the templates which would resolve this so no action from portal needed
