### ISSUE TITLE
Error: starting Codewind in test stage on 's8p2d-ubuntu1804' docker-build agent

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind#2865]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
There is a test failure appeared only on Eclipse provisioned 'docker-build' agent - https://ci.eclipse.org/codewind/computer/s8p2d-ubuntu1804/
It doesn't occur in other 'docker-build' agents. 

A sample failed test: 
https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/29/console

11:25:48  Creating codewind-performance ... 
11:25:48  [1A[2K
Creating codewind-performance ... [32mdone[0m
[1BCreating codewind-pfe         ... 
11:25:48  [1A[2K
Creating codewind-pfe         ... [32mdone[0m
[1BWaiting for Codewind to start
11:28:07  ....................................................2020/04/30 15:28:06 Codewind containers are taking a while to start. Please check the container logs and/or restart Codewind
11:28:07  
11:28:07  
11:28:07  [0;31mFAILED TO START CONTAINERS [0m
11:28:07  Error starting Codewind
.
.
.
11:28:09  (node:107) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
11:28:09  [91m[30/04/20 15:26:58 server.js] [ERROR][39m { Error: Cannot find module 'is-mergeable-object'
11:28:09      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
11:28:09      at Function.Module._load (internal/modules/cjs/loader.js:562:25)
11:28:09      at Module.require (internal/modules/cjs/loader.js:692:17)
11:28:09      at require (internal/modules/cjs/helpers.js:25:18)
11:28:09      at Object.<anonymous> (/file-watcher/server/node_modules/deepmerge/index.js:1:32)
11:28:09      at Module._compile (internal/modules/cjs/loader.js:778:30)
11:28:09      at Module.replacementCompile (/root/.npm/_npx/38/lib/node_modules/nyc/node_modules/append-transform/index.js:60:13)
11:28:09      at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
11:28:09      at Object.<anonymous> (/root/.npm/_npx/38/lib/node_modules/nyc/node_modules/append-transform/index.js:64:4)
11:28:09      at Module.load (internal/modules/cjs/loader.js:653:32) code: 'MODULE_NOT_FOUND' }
11:28:09  [32m[30/04/20 15:26:58 server.js] [INFO][39m Codewind PFE container startup failed
**Steps to reproduce:**

**Workaround:** 

Trigger builds on non-Eclipse provisioned docker-build agents.

**Comment by jgwest** [comment]
Moving to verify, and will close once once it has had a chance to prove that it does not occur in our regular builds.

/pipeline verify

**Comment by jgwest** [comment]
Forgot that it was @josephca that opened this one, thanks @codewind-bot  😛
