### ISSUE TITLE
[Eclipse IDE] Widget disposed exception on app overview update method

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2917]
Getting a widget disposed exception on the app overview update method after deleting a project:

```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4711)
	at org.eclipse.swt.SWT.error(SWT.java:4626)
	at org.eclipse.swt.SWT.error(SWT.java:4597)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:452)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:351)
	at org.eclipse.swt.widgets.Control.getVisible(Control.java:1727)
	at org.eclipse.codewind.ui.internal.editors.ApplicationOverviewEditorPart.update(ApplicationOverviewEditorPart.java:297)
	at org.eclipse.codewind.ui.internal.editors.ApplicationOverviewEditorPart.update(ApplicationOverviewEditorPart.java:284)
	at org.eclipse.codewind.ui.internal.editors.ApplicationOverviewEditorPart.lambda$0(ApplicationOverviewEditorPart.java:260)
	at org.eclipse.codewind.ui.internal.editors.ApplicationOverviewEditorPart$$Lambda$629.0000000014210910.run(Unknown Source)
```

**Comment by eharris369** [comment]
Fixed by PR: https://github.com/eclipse/codewind-eclipse/pull/725
