### ISSUE TITLE
SVT [IntelliJ] 

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#2951]
**Codewind version**: 0.12
**OS**: Windows

**IDE extension version:0.12**
**IDE version:IntelliJ 2019-3-5**

**Description:**
When I install Codewind and create an Appsody Open Liberty project for the first time, the project creates, but I get this popup error message that says 
``` 
An error occurred while starting a build for the apps-op project: Directory cannot be removed..
```
However, if I create another appsody open liberty project, the error message does not show up.
**Steps to reproduce:**
1. Make sure the codewind images are not there before you start.
2. Install Codewind in IntelliJ
3. Create an Appsody Open Liberty project

Screenshot:
<img width="1322" alt="Screen Shot 2020-05-14 at 10 04 59 AM" src="https://user-images.githubusercontent.com/19738071/81955242-d73fa080-95d7-11ea-8f85-cbfde0a2139e.png">

@jagraj

**Comment by jagraj** [comment]
I can not reproduce this problem with Codewind 0.11.0 release. Looks like this is specific to Codewind 0.12.0 release.

**Comment by sujeilyfonseca** [comment]
During our call to debug the issue, we reproduced the problem on my Windows VM. The issue seems to be intermittent and occurs when the `temp` directory is held by a resource, making Codewind unable to delete the directory.

**Notes:**
- I created three Appsody Open Liberty projects, and I got the popup with the first of them. 
- I created three Appsody Quarkus projects, and I got the popup with the first two projects.
- I created other projects, such as Appsody Spring and Default projects, and didn't get the popup.
- The issue seems to occur with Appsody projects and only on Windows.

<img width="1445" alt="Screen Shot 2020-05-14 at 12 19 27 PM" src="https://user-images.githubusercontent.com/49531960/81968163-06f7a400-95ea-11ea-9caf-0b81a4983b2b.png">

<img width="1445" alt="Screen Shot 2020-05-14 at 12 25 30 PM" src="https://user-images.githubusercontent.com/49531960/81968379-52aa4d80-95ea-11ea-80ed-b2a9d898e8b8.png">

```
2020-05-14 12:43:08,908 [1965806]   WARN - e.SetupCodewindProjectRunnable - An error occurred creating project cw-appsody-quarkus-2 
java.io.IOException: Directory cannot be removed.
	at org.eclipse.codewind.intellij.core.FileUtil.deleteDirectory(FileUtil.java:106)
	at org.eclipse.codewind.intellij.ui.module.SetupCodewindProjectRunnable.run(SetupCodewindProjectRunnable.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Log:** [idea.log](https://github.com/eclipse/codewind/files/4630094/idea.log)

**Comment by keithchong** [comment]
Project bind was successful, just before the attempt to delete the temporary folder.  The codewind project is valid.  I can reproduce this issue but it is intermittent.  Users can disregard this error message.
