### ISSUE TITLE
[SVT][IntelliJ] Open Container Shell option not working

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#2952]
**Codewind Version**: 0.12
**OS**: Ubuntu 18.04.4 LTS
**IDE Version**: IntelliJ IDEA 2020.1.1 (Community Edition)
Build #IC-201.7223.91, built on April 30, 2020

Description: Open Container Shell option not working for any project.

In the stacktrace I see:

```
java.lang.NoSuchMethodError: 'org.jetbrains.plugins.terminal.ShellTerminalWidget org.jetbrains.plugins.terminal.TerminalView.createLocalShellWidget(java.lang.String)'
	at org.eclipse.codewind.intellij.ui.actions.OpenContainerShellAction$1.run0(OpenContainerShellAction.java:69)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

[pfe.txt](https://github.com/eclipse/codewind/files/4629578/pfe.txt)
[idea.log](https://github.com/eclipse/codewind/files/4629583/idea.log)

@jagraj

**Comment by DavidG1011** [comment]
Tested on Mac with IntelliJ IDEA 2020.1.1 and the same problem is occurring. Seems to be the new version of IntelliJ that breaks it. This was working prior to upgrading.

**Comment by jopit** [comment]
Open Container Shell function has been broken by a change in the 2020.1 IntelliJ release.  Right now you need to remain on the 2019.3.x versions of IntelliJ for this to work.

**Comment by jopit** [comment]
The fix for this requires updating the minimum supported level of IntelliJ to 2020.1.1

**Comment by sishida** [comment]
@jopit Hi, John, I have created the PR to update the IntelliJ version in the docs: https://github.com/eclipse/codewind-docs/pull/601

**Comment by DavidG1011** [comment]
This is now working with IntelliJ 2020.1.1 and has been documented for users. Thank you @jopit, @sishida

<img width="1368" alt="Screen Shot 2020-05-22 at 11 08 41 AM" src="https://user-images.githubusercontent.com/30476587/82692819-5fecbb00-9c2e-11ea-9b09-3ccf53e7b4f4.png">
