### ISSUE TITLE
Socket won't accept authentication after restarting minikube

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2998]
Steps:

1. Have Codewind working on minikube and connect to it from the IDE
2. Stop minikube and start it again (the IDE can be open or closed)
3. When the IDE tries to reconnect to the minikube Codewind instance, I get an `unauthorized` event after sending the authentication over the socket, with the message body `{ message: "TOKEN_REJECTED" }`.

However I can still do API calls through the gatekeeper with that same auth token. 

After reinstalling Codewind, the new instance works, but if I restart minikube again I see the same issue.

PFE Logs:
```
[22/05/20 00:37:02 socketAuth.js] [INFO] UISocket : [pre-authenticate]
[22/05/20 00:37:02 socketAuth.js] [TRACE] UISocket : [verifySocketUser] - token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0TWRRQU1YQno5aUZwNlpfVG5UWXpLalROWERCREduOFBvZEdBTG9YZkFBIn0.eyJqdGkiOiJjNzY0M2Q4My1kNmJkLTQ5Y2ItYTM1My1iY2U4MzQ3MDA1YzEiLCJleHAiOjE1OTAxOTQyMjEsIm5iZiI6MCwiaWF0IjoxNTkwMTA3ODIxLCJpc3MiOiJodHRwczovL2NvZGV3aW5kLWtleWNsb2FrLWthaGRtNHBoLjE5Mi4xNjguNjQuMi5uaXAuaW8vYXV0aC9yZWFsbXMvY29kZXdpbmQiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiMDk0NzBhZGUtNmI1My00MzAwLWIwM2ItYmRjNTBjZDkxYzM4IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiY29kZXdpbmQta2FoZG00cGgiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiI3Y2EwNGVmMy04ZmNmLTQxOTYtYWUwMy0yNThhNTNkNDVjMjgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vY29kZXdpbmQtZ2F0ZWtlZXBlci1rYWhkbTRwaC4xOTIuMTY4LjY0LjIubmlwLmlvIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJjb2Rld2luZC1rYWhkbTRwaCIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImRldmVsb3BlciIsImdpdmVuX25hbWUiOiIiLCJmYW1pbHlfbmFtZSI6IiJ9.MRjBEgwce1w6Ss7IkrRBGP2h7JrEMAhPOSgJbDR_8uEA00rNyfngC8BlwgdXR4P6Hr9N_iuQk1YnuCPdRMXYUiZG_qkYYNcAhGfxsGRN_V3EmavBtDJm-mlxP05Jb3Y7d85PkU4ER5u9pBvK0JQ0uNXaLk_JlMJlUEzFWkmp9WD-3vjEX6mqFLVkgkdU_W9FUgpgaGinxch1NptpT8X8wSkmsBC1NYqg6ALRd2Hl-xG8UxSQy8Z7h57g0wdGW6J7RMrVWHRWqKY5wFczmQ7gPsMn6A5sfU3CUk517jfYO-StL6GhVmsZWgjqYN-pkrGhGIPXAsNFsKRwHKSxs5ftAg
[22/05/20 00:37:02 socketAuth.js] [TRACE] UISocket : [verifySocketUser] - publickey:
[22/05/20 00:37:02 socketAuth.js] [ERROR] UISocket : [verifySocketUser] - secret or public key must be provideds
[22/05/20 00:37:02 socketAuth.js] [TRACE] { JsonWebTokenError: secret or public key must be provided
    at /portal/node_modules/jsonwebtoken/verify.js:106:19
    at getSecret (/portal/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/portal/node_modules/jsonwebtoken/verify.js:94:10)
    at Promise (/portal/modules/utils/socketAuth.js:23:9)
    at new Promise (<anonymous>)
    at Object.verifySocketUser (/portal/modules/utils/socketAuth.js:20:10)
    at Object.authenticate (/portal/modules/utils/socketAuth.js:101:48)
    at Socket.<anonymous> (/portal/node_modules/socketio-auth/lib/socketio-auth.js:31:14)
    at Socket.emit (events.js:198:13)
    at /portal/node_modules/socket.io/lib/socket.js:528:12
  name: 'JsonWebTokenError',
  message: 'secret or public key must be provided' }
[22/05/20 00:37:02 socketAuth.js] [INFO] UISocket : [authenticate] - /default#r7iu8g5CFWPxPCGMAAAB unauthorized: TOKEN_REJECTED
[22/05/20 00:37:03 socketAuth.js] [INFO] UISocket : [disconnect] - /default#r7iu8g5CFWPxPCGMAAAB disconnected.
```

**Comment by jgwest** [comment]
If you all need a way to quickly setup a minikube-like cluster that can easily be restarted, see `jgwest/k3s-codewind-che` on GHE

**Comment by markcor11** [comment]
Likely solved with fixes to issue 3084
/pipeline Review/QA
