### ISSUE TITLE
Codewind test case failure on ppc64le v0.12.0

### ISSUE THREAD

**Issue by snehlatamohite** [eclipse/codewind#3016]
Hi All,

I have successfully ported the codewind components to work with IBM POWER (arch : ppc64le).

eclipse/codewind-gatekeeper-ppc64le        
econd ago        105MB
eclipse/codewind-keycloak-ppc64le          
seconds ago      648MB
eclipse/codewind-performance-ppc64le       
seconds ago      114MB
eclipse/codewind-pfe-ppc64le               
I am running unit test cases, test.sh script. I have observed below results and please find attached logs for the failing 16 test cases. 

could you please help to resolve the issues please? 

Thanks,
Snehlata Mohite.

**Comment by snehlatamohite** [comment]
Hi All,

Today have observed below changes in test results and also attaching logs.
[codewind-test-log-27-5.txt](https://github.com/eclipse/codewind/files/4687541/codewind-test-log-27-5.txt)
 
Test result today - 
  904 passing (6m)
  29 pending
  11 failing

Thanks,
Snehlata Mohite.

**Comment by malincoln** [comment]
@tobespc I'm adding "priority/hot label" since we need to work through these power issues to make progress.

**Comment by hhellyer** [comment]
I've taken a look at these, checking the 0.12.0 branch out to my machine locally for comparision.

First log (codewind-test-results.txt.txt):

- Failure 1: Extensions API test 
The Apposody extension is disabled on PPC64LE. If I disable it locally on my machine then I get the same failure. 
- Failure 2: Project Types API tests
 I haven't managed to reproduce this. The full logs might give us some more information. if you have them.
- Failures 3-9: Project Metrics tests
 Looks most like a failure to copy the test data into the test project. These failures probably all have the same root cause. The full log might show if the setup code in the before blocks timed out. 
- Failure 10 : Spring project with javametrics-dash
This is the only failure that occurs for me locally when I check out the 0.12.0. I will take a look at this problem more closely. 
- Failure 11 : getAllTemplateStyles()
Ordering error in the test, fixed under https://github.com/eclipse/codewind/issues/2970


Second log (codewind-test-log-27-5.txt):

This log is mainly the same, lots of extra failures but these look likely to be caused by a slow machine or slow internet connection. There's a timeout at the start of that log:

```
  Templates.js
[26/05/20 08:47:22 Templates.js] [WARN] Error accessing template repository 'https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json'. Error: { Error: socket hang up
    at createHangUpError (_http_client.js:332:15)
    at TLSSocket.socketCloseListener (_http_client.js:373:25)
    at TLSSocket.emit (events.js:203:15)
    at _handle.close (net.js:607:12)
    at TCP.done (_tls_wrap.js:400:7) code: 'ECONNRESET' }
[26/05/20 08:47:22 Templates.js] [INFO] Repository list updated.
    16) "before all" hook in "Templates.js"
```

If you have them then the full logs for these test runs as well as the log from the codewind-pfe container would be useful in diagnosing them further.

**Comment by snehlatamohite** [comment]
@hhellyer  - Thanks for initial analysis for the test failures. Could you please help me to understand full logs means , do you want me  to upload file codewind-pfe-test-sh-output.log here or how to capture full logs?

**Comment by snehlatamohite** [comment]
I will work on Failure 11 : getAllTemplateStyles() ans also will have a look at above link. 
Failure 1: Extensions API test  - Do I need to test this by enabling appsody extension on Power , if yes how to enable it and any steps to proceed further?

**Comment by snehlatamohite** [comment]
I have one more observation. Test failures results changes not there are 16 test failures.  I am adding logs. please do let me know if you need any additional information. [
[codewind-pfe-test-sh-output.log](https://github.com/eclipse/codewind/files/4711384/codewind-pfe-test-sh-output.log)
[codewind logs -28-5.txt](https://github.com/eclipse/codewind/files/4711390/codewind.logs.-28-5.txt)

](url)

**Comment by snehlatamohite** [comment]
This log is mainly the same, lots of extra failures but these look likely to be caused by a slow machine or slow internet connection. There's a timeout at the start of that log: - I have started creating codewind setup on high end system , I will share observation.

**Comment by snehlatamohite** [comment]
@hhellyer  - Today I have build v0.12.0 codewind on high configuration system and executed tests on it, still I don't see any changes in test failures.  PFA logs for the same. 
[codewind-pfe-test-sh-output.log](https://github.com/eclipse/codewind/files/4717243/codewind-pfe-test-sh-output.log)
[test-logs-codewind.txt](https://github.com/eclipse/codewind/files/4717244/test-logs-codewind.txt)



  751 passing (6m)
  21 pending
  16 failing

**Comment by snehlatamohite** [comment]
@hhellyer  - I have noticed one thing that ibmcom/codewind-java-project-cache is not multiarch not sure its impact on test failures.  I tried to search dockerfile for so that I can build container locally for Power however I could not found. 

https://hub.docker.com/r/ibmcom/codewind-java-project-cache

docker run -it ibmcom/codewind-java-project-cache
standard_init_linux.go:190: exec user process caused "exec format error"

**Comment by hhellyer** [comment]
@elsony - Do you know where the source for the `codewind-java-project-cache` image lives?
@snehlatamohite - This is quite a specific problem - it may be you need to build that for ppc 
- would you mind breaking it out into a separate issue we can track and fix? (We can assign that to the right squad then.)

**Comment by hhellyer** [comment]
@snehlatamohite - The failing metrics tests will create a NodeJS project and then copy metrics into it to test they get back the expected data.
Could you verify that you are able to create a Codewind NodeJS project? (Most of our tests don't create projects as it takes a long time and leads to erratic test behaviour. This could be why you see issues with the metrics tests with otherwise don't do anything platform specific.)

**Comment by snehlatamohite** [comment]
@hhellyer  -  Can you please tell me how to access codewind UI? 

Please find below logs looks like I am not able to access UI on port 9097

System architecture is:  ppc64le
Host operating system is:  linux
Attempting to find available port
Port 10000 Available
Please wait while containers initialize...
Creating network "codewind_network" with the default driver
Creating codewind-performance ... done
Creating codewind-pfe         ... done
Waiting for Codewind to start
................
HTTP Response Status: 200 OK
Codewind successfully started on http://127.0.0.1:10000

[codewind]# wget http://127.0.0.1:10000
--2020-06-05 07:00:41--  http://127.0.0.1:10000/
Connecting to 127.0.0.1:10000... connected.
HTTP request sent, awaiting response... 200 OK
 
[codewind]# curl localhost:9777
curl: (7) Failed connect to localhost:9777; Connection refused


SUCCESSFULLY STARTED CONTAINERS

Current running codewind containers
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
787f4fbb7697        eclipse/codewind-pfe-ppc64le:latest           "sh -c ' /file-watch…"   29 seconds ago      Up 26 seconds       127.0.0.1:10000->9090/tcp, 127.0.0.1:34000->9777/tcp   codewind-pfe
cd8e6fe6e2e0        eclipse/codewind-performance-ppc64le:latest   "docker-entrypoint.s…"   31 seconds ago      Up 28 seconds       127.0.0.1:9095->9095/tcp                               codewind-performance

Thanks,
Snehlata Mohite.

**Comment by snehlatamohite** [comment]
@hhellyer  - yes will track separately codewind-java-project-cache issue , thought that it might be related to test failures hence updated here.

**Comment by rwalle61** [comment]
fyi - the 10th failure: Spring project with javametrics-dash should have been fixed in 0.12.0 by https://github.com/eclipse/codewind/pull/2942, which is a 0.12.0 backport of https://github.com/eclipse/codewind/pull/2918/

**Comment by snehlatamohite** [comment]
@rwalle61 - Thanks for the information. I will build containers with fix and then test and will share results.

**Comment by hhellyer** [comment]
I can reproduce the metrics test failures by running the API tests in a different timezone:
```
TZ=EST npm run apitest
```
this will cause them all to break.  Now we understand the problem I will break that out to a separate issue to fix.

**Comment by snehlatamohite** [comment]
@hhellyer  - Appriciate your help. could able to test fixed - Failures 3-9: Project Metrics tests successfully with master code.  For rest failures will test with appsody Power binary downloading and placing at required location and also will increase timeouts a bit to test some of the failures and then will share results.

**Comment by hhellyer** [comment]
We have managed to reduce this to two issues, the original Failure 1 and 
Failure 2 above.

Failure 1 is due to the appsody extension not being available.

Failure 2 (project-types API) is because the machine running codewind cannot access https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json (it can access urls on github.com but not githubusercontent.com) @snehlatamohite is going to look into whether this is a firewall issue.

**Comment by snehlatamohite** [comment]
@hhellyer  - Thanks for help. Appreciate it :) We got fixed 6/8 tests failure fixed by increasing the test time out duration.  Failure 2 - I have started talks with infra team on firewall confirmation.

**Comment by tobespc** [comment]
moving to verify as the tests (that we control) are now running
