### ISSUE TITLE
SVT:Remote debugging is failing for appsody open liberty project.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#3113]
**Codewind version:** 0.13.0
**OS:** Windows, Mac

**Che version:**
**IDE extension version:** 0.13.0
**IDE version:** Eclipse 2019-09
**Kubernetes cluster:**
OCP 4.3 cluster.

Eclipse plugin to OCP 4.3 cluster.
**Description:**
Remote debugging is failing for Appsody open liberty project and same issue for appsody microprofile project as well. 

```
Running development environment...
Pulling docker image docker.io/appsody/java-openliberty:0.2
Running command: buildah pull docker.io/appsody/java-openliberty:0.2
93cf6c15bc039a65c79313c9ae8a204b5f7ce3c493fefa1d0d2392b3acbded99
[Warning] Could not stat mount path: /root/.m2/repository
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
[Warning] The stack image does not contain APPSODY_DEPS
[Warning] Could not stat mount path: /root/.m2/repository
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
Attempting to apply resource in Kubernetes ...
Running command: kubectl apply -f /codewind-workspace/appsodyolhybcw013svt/app-deploy.yaml
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/appsody/appsody/cmd.GenServiceYaml(0xc0000fe700, 0x7ffca1429366, 0x2f, 0xc00019b0e0, 0x3, 0x3, 0xc0002fc633, 0x4, 0xc00002a604, 0x28, ...)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/utils.go:1521 +0xe7b
github.com/appsody/appsody/cmd.commonCmd(0xc0000bdc20, 0xb57b25, 0x3, 0xc631a0, 0xc0000ba008)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/dev_common.go:426 +0x1676
github.com/appsody/appsody/cmd.newRunCmd.func1(0xc0001c2c80, 0xc0001c6e70, 0x0, 0x7, 0x0, 0x0)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/run.go:45 +0x16c
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001c2c80, 0xc0001c6e00, 0x7, 0x7, 0xc0001c2c80, 0xc0001c6e00)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00017aa00, 0x5, 0x0, 0xc631a0)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:800
github.com/appsody/appsody/cmd.ExecuteE(0xc5046c, 0x5, 0xc50464, 0x5, 0xc00002a604, 0x28, 0xc631a0, 0xc0000ba008, 0xc631a0, 0xc0000ba010, ...)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/root.go:240 +0x312
github.com/appsody/appsody/cmd.Execute(0xc5046c, 0x5, 0xc50464, 0x5)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/root.go:226 +0x1ab
main.main()
	/home/travis/gopath/src/github.com/appsody/appsody/main.go:27 +0x51
```

**Steps to reproduce:**
1. Install Codewind 0.13.0 from Eclipse plugin.
2. Create remote/hybrid connection to OCP 4.3 cluster.
3. Create appsody open liberty project.
4. After project started in run mode try to start in debug mode.
5. You will get into above failure.

**Workaround:**

**Comment by naveenkaratekid** [comment]
@jagraj I can reproduce this issue too:

```
Running development environment...
Pulling docker image docker.io/appsody/java-openliberty:0.2
Running command: buildah pull docker.io/appsody/java-openliberty:0.2
Getting image source signatures
Copying blob sha256:4d3fb84d4d604d02928b78e2e83e29a8d718d40289469139cfbac1bf4b46b990
Copying blob sha256:9dec387bf2c9c2492902a4f26e4c1c5a43674020cf95ead5ab44899e05c5047d
Copying blob sha256:ee2244abc66ff9c6a4bf50fe19041fec82a95c87d18ee3a3660368cb274927c7
Copying blob sha256:befb03b11956169cf23096fc58081ca35034a6545fc37d63605bf0d200fe5eda
Copying blob sha256:945ac594e05efd3319e50acd1a7c9c64430d327ecddac0465dfe9e9c35ab76ca
Copying blob sha256:8645bb2392a47880ab0f7662f64148701450ed806fa1fe9815ece03b390c6429
Copying blob sha256:b00e275d2e19f00acfe2682b8c3f66011552b358ebc69a850be5467aee927621
Copying blob sha256:ccf00daac438553f611d3b502f5f3515331ee1a8ef108798874717442855868a
Copying blob sha256:0b0c043f6c82b74a6942e67a4de46a4eaff256b168870aa94c258515526b11cf
Copying blob sha256:5f5ac9b5f54cf73194b060e6f5d9f6169feb0b79d3d2a187cb6e16d4e114e43d
Copying blob sha256:bd2a72c9afbab1ea71359b5c37a05650c02d57e96e0391318e725b29e38de6d1
Copying blob sha256:2fd75037f7052cf79476120826cab8fcdd65ccc185093289aecc167e8895970a
Copying blob sha256:1e7f882ae49cddc15604ec1d739c9e793c389ccc3d3439e51fbca9cb5a0ce823
Copying blob sha256:dd77da999c97d744bca0e58f0448c2c462f2003b22b232bf55553d8ba141a83d
Copying blob sha256:9688ac409564f312845bc0ed5b9d56c62ed8a938362331a8d509ae2a50184533
Copying blob sha256:d0aba8033c8559306edca418a6a498f0b63819058f149e97e1be5b409650c0fc
Copying blob sha256:e7e883ba65bb5115ffe6c3bc389ce133c799cfef45afee81885dd2eec6c6b92b
Copying config sha256:93cf6c15bc039a65c79313c9ae8a204b5f7ce3c493fefa1d0d2392b3acbded99
Writing manifest to image destination
Storing signatures
93cf6c15bc039a65c79313c9ae8a204b5f7ce3c493fefa1d0d2392b3acbded99
[Warning] Could not stat mount path: /root/.m2/repository
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
[Warning] The stack image does not contain APPSODY_DEPS
[Warning] Could not stat mount path: /root/.m2/repository
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
Attempting to apply resource in Kubernetes ...
Running command: kubectl apply -f /codewind-workspace/apps-op-def-remote/app-deploy.yaml
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/appsody/appsody/cmd.GenServiceYaml(0xc0000fe700, 0x7ffca73ef955, 0x2a, 0xc0003eb4a0, 0x3, 0x3, 0xc000320673, 0x4, 0xc00002a604, 0x26, ...)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/utils.go:1521 +0xe7b
github.com/appsody/appsody/cmd.commonCmd(0xc0000bdc20, 0xb57b25, 0x3, 0xc631a0, 0xc0000ba008)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/dev_common.go:426 +0x1676
github.com/appsody/appsody/cmd.newRunCmd.func1(0xc0001c2c80, 0xc0001c5260, 0x0, 0x7, 0x0, 0x0)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/run.go:45 +0x16c
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001c2c80, 0xc0001c51f0, 0x7, 0x7, 0xc0001c2c80, 0xc0001c51f0)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00017ca00, 0x5, 0x0, 0xc631a0)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:800
github.com/appsody/appsody/cmd.ExecuteE(0xc5046c, 0x5, 0xc50464, 0x5, 0xc00002a604, 0x26, 0xc631a0, 0xc0000ba008, 0xc631a0, 0xc0000ba010, ...)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/root.go:240 +0x312
github.com/appsody/appsody/cmd.Execute(0xc5046c, 0x5, 0xc50464, 0x5)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/root.go:226 +0x1ab
main.main()
	/home/travis/gopath/src/github.com/appsody/appsody/main.go:27 +0x51

```

**Comment by makandre** [comment]
@neeraj-laad @Kamran64 This looks like the same error in https://github.com/appsody/appsody/pull/994#issuecomment-630802954

We weren't able to reproduce it before but looks like it's popping up again.

**Comment by sujeilyfonseca** [comment]
I have reproduced the problem as well, using VS Code connected to an OCP 4.3 cluster in Mac and Windows.

I see the problem occurs with Appsody Eclipse MicroProfile and Appsody Open Liberty projects.

```
[Warning] Could not stat mount path: /root/.m2/repository
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
[Warning] The stack image does not contain APPSODY_DEPS
[Warning] Could not stat mount path: /root/.m2/repository
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
Attempting to apply resource in Kubernetes ...
Running command: kubectl apply -f /codewind-workspace/cw-013-remote-appsody-liberty-default/app-deploy.yaml
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/appsody/appsody/cmd.GenServiceYaml(0xc0000fe700, 0x7ffd37459292, 0x32, 0xc000387200, 0x3, 0x3, 0xc00023f233, 0x4, 0xc0000285c4, 0x39, ...)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/utils.go:1521 +0xe7b
github.com/appsody/appsody/cmd.commonCmd(0xc0000bdc20, 0xb57b25, 0x3, 0xc631a0, 0xc0000ba008)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/dev_common.go:426 +0x1676
github.com/appsody/appsody/cmd.newRunCmd.func1(0xc0001c8c80, 0xc0001cb3b0, 0x0, 0x7, 0x0, 0x0)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/run.go:45 +0x16c
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001c8c80, 0xc0001cb340, 0x7, 0x7, 0xc0001c8c80, 0xc0001cb340)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000182a00, 0x5, 0x0, 0xc631a0)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:800
github.com/appsody/appsody/cmd.ExecuteE(0xc5046c, 0x5, 0xc50464, 0x5, 0xc0000285c4, 0x39, 0xc631a0, 0xc0000ba008, 0xc631a0, 0xc0000ba010, ...)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/root.go:240 +0x312
github.com/appsody/appsody/cmd.Execute(0xc5046c, 0x5, 0xc50464, 0x5)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/root.go:226 +0x1ab
main.main()
	/home/travis/gopath/src/github.com/appsody/appsody/main.go:27 +0x51
```

**Comment by DavidG1011** [comment]
Codewind version: 0.13.0
OS:  MacOS

IDE extension version: 0.13.0
IDE version: VSCode 1.45.1
Kubernetes cluster: OCP 4.2

Seeing this issue with Appsody Eclipse MicroProfile, Appsody Open Liberty, and Appsody Spring Boot Default projects.

Diagnostics:
[diagnostics.20200609150030.zip](https://github.com/eclipse/codewind/files/4754359/diagnostics.20200609150030.zip)

**Comment by jagraj** [comment]
Here is the appsody issue (https://github.com/appsody/appsody/issues/1002) opened for this problem.

**Comment by jagraj** [comment]
This issue has been resolved with the latest appsody CLI.
