### ISSUE TITLE
[0.14.1] ODO Devfile 0.14.1 not being installed 

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#3217]
From Slack:
Jag:
```
 I am trying to create ODO projects from Che and I see these ODO templates in the list and I can not find any Java projects. I did run ODO setup instructions documented in our docs.
```
![image](https://user-images.githubusercontent.com/17385115/88951231-9c234400-d28d-11ea-9ea2-c5a1fb814bb0.png)

Logs from John Collier:

```
[28/07/20 18:16:17 Turbine] [INFO] The project folder does not exist yet: /file-watcher/fwdata/projects/
[28/07/20 18:16:17 User.js] [INFO] Initialising existing projects for user default
[28/07/20 18:16:17 User.js] [INFO] Projects initialised for user default
[28/07/20 18:16:17 User.js] [INFO] Installing extentions for user default
[28/07/20 18:17:21 /portal/modules/utils/installExtensions.js] [WARN] Failed to install codewind-odo-extension-devfile-0.14.1.zip
[28/07/20 18:17:21 /portal/modules/utils/installExtensions.js] [WARN] { [Error: ENOENT: no such file or directory, rename '/codewind-workspace/.extensions/codewind-odo-extension-devfile-0.14.1' -> '/codewind-workspace/.extensions/codewind-odo-extension-devfile']
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path:
   '/codewind-workspace/.extensions/codewind-odo-extension-devfile-0.14.1',
  dest:
   '/codewind-workspace/.extensions/codewind-odo-extension-devfile' }
[28/07/20 18:17:23 /portal/modules/ExtensionList.js] [INFO] Extension codewind-appsody-extension successfully initialised
[28/07/20 18:17:23 /portal/modules/ExtensionList.js] [INFO] Extension codewind-odo-extension successfully initialised
[28/07/20 18:17:23 /portal/modules/ExtensionList.js] [INFO] Extension codewind-odo-extension-0.14.1-devfile successfully initialised
[28/07/20 18:17:32 Templates.js] [INFO] Repository list updated.
[28/07/20 18:17:51 Templates.js] [INFO] Repository list updated.
[28/07/20 18:17:51 Templates.js] [ERROR] { Error: Command failed: /codewind-workspace/.extensions/codewind-odo-extension-devfile/bin/odo preference set experimental true -f
/bin/sh: /codewind-workspace/.extensions/codewind-odo-extension-devfile/bin/odo: No such file or directory
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
  code: 127,
  signal: null,
  cmd:
   '/codewind-workspace/.extensions/codewind-odo-extension-devfile/bin/odo preference set experimental true -f',
  stdout: '',
  stderr:
   '/bin/sh: /codewind-workspace/.extensions/codewind-odo-extension-devfile/bin/odo: No such file or directory\n' }
[28/07/20 18:17:52 Templates.js] [INFO] Repository list updated.
[28/07/20 18:17:52 User.js] [INFO] Extensions initialised for user default.
[28/07/20 18:17:52 User.js] [INFO] Initialising template repository list
[28/07/20 18:17:52 Templates.js] [ERROR] { Error: Command failed: /codewind-workspace/.extensions/codewind-odo-extension-devfile/bin/odo preference set experimental true -f
/bin/sh: /codewind-workspace/.extensions/codewind-odo-extension-devfile/bin/odo: No such file or directory
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 127,
  signal: null,
  cmd:
   '/codewind-workspace/.extensions/codewind-odo-extension-devfile/bin/odo preference set experimental true -f',
  stdout: '',
  stderr:
   '/bin/sh: /codewind-workspace/.extensions/codewind-odo-extension-devfile/bin/odo: No such file or directory\n' }
```

**Fix**
I found the install extensions script is expecting the unzip'd directory to be `codewind-odo-extension-devfile-0.14.1` (`target + '-' + version`) but it's actually `codewind-odo-extension-0.14.1-devfile`.

I've recreated on Kube, just working on a fix so that it doesn't matter where the version is.

**Comment by jagraj** [comment]
/priority stopship

@james-wallis - Thank you.

**Comment by jagraj** [comment]
@james-wallis @tobespc 
We had a conversation with Elson on this ODO 2.0 support, we suppose to provide two template sources one for ODO 1.x and other one for ODO 2.x. I only see one template source for ODO in the current 0.14.1 release. Once this issue is fixed then we should be able to see both.?

![image](https://user-images.githubusercontent.com/713849/88964983-18ab2800-d278-11ea-84c5-7540a174f2d7.png)

**Comment by james-wallis** [comment]
Yes you should see both (OpenShift and OpenShift Devfiles).

**Comment by james-wallis** [comment]
4 PRs raised for this issue. 2 for each repository of `codewind` and `codewind-odo-extension`. I am off tomorrow but I can monitor Slack in case of any issues.

Fix for the `codewind` repo was to slightly modify the installing of the extensions to use a temp directory rather than guessing what the directory name was after the unzip.

Fix for the `codewind-odo-extension` repo was to use `catalog describe component -o json` as suggested by Elson to make the search for a Git URL more robust.

@jagraj

**Comment by james-wallis** [comment]
PRs merged @jagraj can you please verify as you raised the initial issue on Slack, thanks.

**Comment by jagraj** [comment]
@james-wallis @elsony @johnmcollier 
With the latest builds, we only see ODO 2 devfiles templates but ODO 1 projects templates missing. Are we planning to provide both the options for the users with this release.?

**Comment by elsony** [comment]
yes, we are supposed to see both odo1 and odo2 templates. @james-wallis Why would the odo1 template missing? I thought the odo1 is a different extension.

**Comment by james-wallis** [comment]
odo1 is a different extension, it should be there.

**Comment by johnmcollier** [comment]
@jagraj It shows up fine for me on my cluster, make sure you ran the setup script for the odov1 extension too if you want to use it. https://github.com/eclipse/codewind-odo-extension/blob/master/setup/setup.sh

**Comment by james-wallis** [comment]
Given that the ODO2 templates are now being installed this issue is complete.
