### ISSUE TITLE
SVT: Error loading ODO extension in the PFE log.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#3224]
**Codewind version:** 0.14.1
**OS:** CoreOS

**Che version:** 7.16.1
**IDE extension version:** 0.14.1
**IDE version:** 7.16.1
**Kubernetes cluster:**
OCP 4.3.29

**Description:**
We can not see both ODO 2 and ODO 1 templates in the Template source manager list. Here is the error we are seeing in PFE log.

![image](https://user-images.githubusercontent.com/713849/89673034-ab207c80-d8b3-11ea-90c6-d151f31ee13a.png)

```
> codewind-portal@1.0.0 start /portal
> ./npm-start.sh

Found node environment set to prod. Running in production mode.

> codewind-portal@1.0.0 prod /portal
> node server.js

[07/08/20 17:21:33 server.js] [INFO] Starting Codewind PFE container
[07/08/20 17:21:33 server.js] [INFO] Codewind PFE image version 'x.x.dev' image build time '20200807-142239'
Fri, 07 Aug 2020 17:21:34 GMT kubernetes-client deprecated getInCluster see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md#request-kubeconfig- at server.js:94:61
Fri, 07 Aug 2020 17:21:34 GMT kubernetes-client deprecated Request() without a .kubeconfig option, see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md at server.js:94:40
[07/08/20 17:21:34 server.js] [INFO] Codewind is running in Kubernetes
[07/08/20 17:21:34 server.js] [INFO] Ingress path is "codewind-workspacene2303237m7w3te3-che-che.apps.extols.os.fyre.ibm.com"
Fri, 07 Aug 2020 17:21:34 GMT kubernetes-client deprecated require('kubernetes-client').config, use require('kubernetes-client/backends/request').config. at modules/utils/kubernetesFunctions.js:13:44
Fri, 07 Aug 2020 17:21:34 GMT kubernetes-client deprecated getInCluster see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md#request-kubeconfig- at modules/utils/kubernetesFunctions.js:14:44
Fri, 07 Aug 2020 17:21:34 GMT kubernetes-client deprecated Client({ config }), see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md at modules/utils/kubernetesFunctions.js:14:16
Fri, 07 Aug 2020 17:21:34 GMT kubernetes-client deprecated Request() without a .kubeconfig option, see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md at node_modules/kubernetes-client/lib/swagger-client.js:200:19
[07/08/20 17:21:34 Turbine] [INFO] The current log level is info
[07/08/20 17:21:35 Turbine] [INFO] Initialize application state map
[07/08/20 17:21:35 Turbine] [INFO] Initialize build state map
[07/08/20 17:21:35 Turbine] [INFO] Starting application ping intervals
(node:130) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:130) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:130) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
[07/08/20 17:21:35 Turbine] [INFO] The project folder does not exist yet: /file-watcher/fwdata/projects/
[07/08/20 17:21:35 User.js] [INFO] Initialising existing projects for user default
[07/08/20 17:21:35 User.js] [INFO] Projects initialised for user default
[07/08/20 17:21:35 User.js] [INFO] Installing extentions for user default
[07/08/20 17:21:36 /portal/modules/ExtensionList.js] [INFO] Extension codewind-odo-extension successfully initialised
[07/08/20 17:21:36 /portal/modules/ExtensionList.js] [INFO] Extension codewind-odo-extension-devfile successfully initialised
[07/08/20 17:21:36 /portal/modules/ExtensionList.js] [INFO] Extension codewind-appsody-extension successfully initialised
[07/08/20 17:21:40 Templates.js] [INFO] Repository list updated.
[07/08/20 17:21:41 Templates.js] [ERROR] TypeError: Cannot read property 'map' of undefined
    at Object.getRepositories (/codewind-workspace/.extensions/codewind-odo-extension/templatesProvider.js:39:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[07/08/20 17:21:45 Templates.js] [INFO] Repository list updated.
[07/08/20 17:21:48 Templates.js] [INFO] Repository list updated.
[07/08/20 17:21:48 User.js] [INFO] Extensions initialised for user default.
[07/08/20 17:21:48 User.js] [INFO] Initialising template repository list
[07/08/20 17:21:49 Templates.js] [ERROR] TypeError: Cannot read property 'map' of undefined
    at Object.getRepositories (/codewind-workspace/.extensions/codewind-odo-extension/templatesProvider.js:39:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[07/08/20 17:21:51 Templates.js] [INFO] Repository list updated.
[07/08/20 17:21:51 User.js] [INFO] Initialising template list
[07/08/20 17:21:51 User.js] [INFO] Default templates cached
[07/08/20 17:21:51 Turbine] [INFO] Registered listener: portalListener
[07/08/20 17:21:51 User.js] [INFO] Starting existing projects for user default
[07/08/20 17:21:51 server.js] [INFO] Setting up codewind Express routes
[07/08/20 17:21:52 /portal/controllers/performance.controller.js] [INFO] PerformanceHost: codewind-performance-workspacene2303237m7w3te3
[07/08/20 17:21:52 server.js] [INFO] Express routes configured
[07/08/20 17:21:52 server.js] [INFO] Codewind PFE container startup complete
Fri, 07 Aug 2020 17:22:46 GMT kubernetes-client deprecated getInCluster see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md#request-kubeconfig- at modules/TektonUtils.js:31:62
Fri, 07 Aug 2020 17:22:46 GMT kubernetes-client deprecated Request() without a .kubeconfig option, see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md at modules/TektonUtils.js:31:42
[07/08/20 17:22:46 /portal/modules/TektonUtils.js] [INFO] Looking for services in Tekton namespace 'tekton-pipelines'

```

**Steps to reproduce:**
1. Start codewind 0.14.1 workspace from Che 7.16.1 version.
2. Follow setup instructions for ODO.
3. Missing ODO 1 templates from template source manager.

**Workaround:**

**Comment by james-wallis** [comment]
Any chance you could send the complete template list as well? 

The image shows that the OpenShift 1 templates should be there but nothing about OpenShift 2. Conversely the logs show OpenShift 2 should be OK but OpenShift 1 has a problem.

**Comment by jagraj** [comment]
Hi James,

Here is the screenshot with list of ODO 2 projects. Let me know this is the list you are looking for.?

<img width="685" alt="image" src="https://user-images.githubusercontent.com/713849/89746605-a3fe9780-da88-11ea-83f9-3dd236821e54.png">

**Comment by james-wallis** [comment]
@elsony @johnmcollier In the current release of ODO have the old templates been removed and replaced with the devfile ones? (With experimental turned off)

@jagraj The error your showing in your logs indicates that the ODO output is changed and the templates cannot be parsed (Or for some reason the ODO command failed).

If the templates have changed I think we just need to change the PFE Jenkinsfile to only pull down the ODO Devfile extension.

**Comment by james-wallis** [comment]
So the output of `odo catalog list components -o json` has been changed. instead of returning an `items` object it now returns an `s2iItems` object - content looks the same so I'll push up a change to modify the name.

**Comment by james-wallis** [comment]
With the change above in master I see the correct templates:
![image](https://user-images.githubusercontent.com/17385115/89806891-9f40ee80-db2f-11ea-8ad5-b9d3a7fe79b4.png)

**Comment by james-wallis** [comment]
0.14.1 pr raised.

**Comment by jagraj** [comment]
This issue has been resolved, thanks for the fix. Now I can see both the templates in the source repository.
