### ISSUE TITLE
Codewind (VSCode): Importing existing project with non-existing master branch failed 

### ISSUE THREAD

**Issue by haf-tech** [eclipse/codewind#3236]
**Codewind version:** 0.14.1
**OS:** OpenShift Cluster, CodeReady Workspaces
```
2.4.0.GA :: crw_2.4/19 :: che-dev @ 9348 (19) :: che-parent @ a6dd7f (7.15.0) :: che @ 44fa9 (7.18.3-SNAPSHOT) :: codeready-workspaces @ 597f (2.4.0.GA)
```

**Che version:** 7.18.3-SNAPSHOT
**IDE extension version:** 
**IDE version:**
**Kubernetes cluster:** OpenShift 4.5

CodeReady Workspaces About:
```
Che-Theia@3fd1f44 using Theia@c837b6cba
List of extensions
    @eclipse-che/che-theia-hosted-plugin-manager-extension 7.15.2
    @eclipse-che/theia-about 7.15.2
    @eclipse-che/theia-activity-tracker 7.15.2
    @eclipse-che/theia-cli-endpoint 7.15.2
    @eclipse-che/theia-dashboard-extension 7.15.2
    @eclipse-che/theia-git-provisioner 7.15.2
    @eclipse-che/theia-logging 7.15.2
    @eclipse-che/theia-messaging 7.15.2
    @eclipse-che/theia-plugin-ext 7.15.2
    @eclipse-che/theia-preferences-provider-extension 7.15.2
    @eclipse-che/theia-remote 7.15.2
    @eclipse-che/theia-terminal 7.15.2
```

**Description:**
Importing an existing project with Codewind failed.

The project is a git project with "main" and not "master" as the default branch. "master" does not exist.

**Steps to reproduce:**

- git clone a project which has "main" as default branch
- import this project as "existing project" in Codewind

**Workaround:** 

**Details**

```
Extension-Host:Child process git stderr: fatal: no such branch: 'master'
Extension-Host:Child process "git" exited with code 128
Extension-Host:Error: fatal: no such branch: 'master'

    at ChildProcess.<anonymous> (/tmp/theia-unpacked/eclipse_che_workspace_plugin.theia/lib/exec.js:79:36)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)

...
Extension-Host:TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Function.MessageFactory.request (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:342:166)
    at RPCProtocolImpl.remoteCall (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:169:46)
    at Proxy.target.(anonymous function) (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:143:38)
    at SourceControlImpl.set (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/scm.js:332:24)
    at Repository.statusBar.onDidChange (/default-theia-plugins/vscode-git/extension/out/repository.js:420:75)
    at i (/default-theia-plugins/vscode-git/extension/out/util.js:53:83)
    at /home/theia/node_modules/@theia/core/lib/common/event.js:163:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:178:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:305:29)
Extension-Host:TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Function.MessageFactory.request (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:342:166)
    at RPCProtocolImpl.remoteCall (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:169:46)
    at Proxy.target.(anonymous function) (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:143:38)
    at SourceControlImpl.set (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/scm.js:332:24)
    at Repository.statusBar.onDidChange (/default-theia-plugins/vscode-git/extension/out/repository.js:420:75)
    at i (/default-theia-plugins/vscode-git/extension/out/util.js:53:83)
    at /home/theia/node_modules/@theia/core/lib/common/event.js:163:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:178:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:305:29)
Extension-Host:TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Function.MessageFactory.request (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:342:166)
    at RPCProtocolImpl.remoteCall (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:169:46)
    at Proxy.target.(anonymous function) (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:143:38)
    at SourceControlImpl.set (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/scm.js:332:24)
    at Repository.statusBar.onDidChange (/default-theia-plugins/vscode-git/extension/out/repository.js:420:75)
    at i (/default-theia-plugins/vscode-git/extension/out/util.js:53:83)
    at /home/theia/node_modules/@theia/core/lib/common/event.js:163:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:178:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:305:29)
Extension-Host:Child process git stderr: fatal: no such branch: 'master'
Extension-Host:Child process "git" exited with code 128
Extension-Host:Could not detect git project branch for /projects/kabanero-nodejs-express/
Extension-Host:Error: fatal: no such branch: 'master'
```

Not clear, if this is only a Codewind issue or more a Theia one.

**Comment by haf-tech** [comment]
Not relevant anymore.
