### ISSUE TITLE
SVT : Eclipse Plugin locks up on 13th project

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#379]
**Codewind version:** 0.3
**OS:** MacOS

**Che version:**
**IDE extension version:** 
**IDE version:**
**Kubernetes cluster:**

**Description:**
Shortly after I created a 13th project, and hit refresh to refresh the codewind view,  codewind got into trouble and became unresponsive. 

The codewind view now shows: 

Codewind [Error] check workspace log for more information.

The timestamp for the directory of the last created project was 10.01 and this was the first entry after that in the workspace log:

!ENTRY org.eclipse.codewind.core 4 0 2019-09-05 10:11:25.997
!MESSAGE [ERROR CodewindManager.getInstallStatus:79] Timed out trying to get the installer status
!STACK 0
java.util.concurrent.TimeoutException: Process did not complete and had to be terminated
	at org.eclipse.codewind.core.internal.ProcessHelper.waitForProcess(ProcessHelper.java:114)
	at org.eclipse.codewind.core.internal.InstallUtil.statusCodewind(InstallUtil.java:164)
	at org.eclipse.codewind.core.internal.InstallUtil.getInstallStatus(InstallUtil.java:78)
	at org.eclipse.codewind.core.internal.CodewindManager.getInstallStatus(CodewindManager.java:68)
	at org.eclipse.codewind.ui.internal.views.CodewindNavigatorContentProvider.hasChildren(CodewindNavigatorContentProvider.java:63)
	at org.eclipse.ui.internal.navigator.extensions.SafeDelegateTreeContentProvider.hasChildren(SafeDelegateTreeContentProvider.java:115)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.callNormalHasChildren(NavigatorContentServiceContentProvider.java:445)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.access$4(NavigatorContentServiceContentProvider.java:440)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider$3.run(NavigatorContentServiceContentProvider.java:408)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.hasChildren(NavigatorContentServiceContentProvider.java:393)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.hasChildren(NavigatorContentServiceContentProvider.java:437)
	at org.eclipse.jface.viewers.AbstractTreeViewer.isExpandable(AbstractTreeViewer.java:2152)
	at org.eclipse.jface.viewers.TreeViewer.isExpandable(TreeViewer.java:546)
	at org.eclipse.jface.viewers.AbstractTreeViewer.isExpandable(AbstractTreeViewer.java:2190)
	at org.eclipse.jface.viewers.AbstractTreeViewer.updatePlus(AbstractTreeViewer.java:2874)
	at org.eclipse.jface.viewers.TreeViewer.updatePlus(TreeViewer.java:794)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1913)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1880)
	at org.eclipse.ui.navigator.CommonViewer.internalRefresh(CommonViewer.java:532)
etc....

This log entry is seen multiple times.

Restarting eclipse does not help. 

**Steps to reproduce:**
Create 13 projects and then refresh the codewind view.

**Workaround:** 
None.

**Comment by mmulholl** [comment]
@jagraj @eharris369

**Comment by mmulholl** [comment]
restarted docker to get codewind going again, deleted a project and all is good.
