### ISSUE TITLE
Project ID missing for projects created through API with autobuild: false

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#52]
Richard Waller came across this while trying to unskip `build.test.js`.

Steps to recreate:
1. create a project through the `POST /projects` API with `autobuild: false`
2. request to build the project through the `POST /projects/:projectID/build` API, and receive status `202`
3. the project does not actually build, and I see this error in `pfe` logs:
```
[ERROR Wed Jun 12 13:20:12 GMT 2019 | FileWatcher | File Name: /file-watcher/server/dist/controllers/projectsController.js | Function Name: projectAction | Line Number: 972] An error occurred while executing projectAction:
 {"action":"build","projectID":"cf240f20-8d14-11e9-891c-2f98a83e9317","projectType":"nodejs"}
 404: No project found for project id: cf240f20-8d14-11e9-891c-2f98a83e9317
[12/06/19 13:20:12 User.js] [ERROR] Error in function buildProject
[12/06/19 13:20:12 User.js] [ERROR] { ProjectListError: NOT_FOUND: Project with ID cf240f20-8d14-11e9-891c-2f98a83e9317 not found.
    at handleProjectActionResponse (/portal/modules/FileWatcher.js:567:19)
    at FileWatcher.performProjectActionRequest (/portal/modules/FileWatcher.js:370:5)
  name: 'ProjectListError',
  code: 'NOT_FOUND',
  info:
   { name: 'ProjectListError',
     code: 'NOT_FOUND',
     message:
      'NOT_FOUND: Project with ID cf240f20-8d14-11e9-891c-2f98a83e9317 not found.' } }
      
```

**Comment by johnmcollier** [comment]
Closing as a dupe of https://github.com/eclipse/codewind/issues/54
