### ISSUE TITLE
SVT:Show all logs not enabled for Java project when I right click after importing project into codewind

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#538]
**Codewind version:** 0.4
**OS:** WIndows

**Che version:**
**IDE extension version:** 0.4
**IDE version:** Eclipse 2019-09
**Kubernetes cluster:**

**Description:**
After importing Rogue cloud from (https://github.com/sujeilyfonseca/rogue-cloud-client-codewind) , "Show log Files" option is not enabled. I need to refresh the "Codewind explorer" to get this option. The application started building and I could not get to the logs until I refresh.

**Steps to reproduce:**
1. Install codewind on eclipse.
2. Import existing project (https://github.com/sujeilyfonseca/rogue-cloud-client-codewind).
3. During the build, I do not see option "Show Log Files" option.
4. I need to refresh Codewind explorer manually.

**Workaround:**

**Comment by eharris369** [comment]
This appears to be a problem with PFE.  The interesting thing is that I can only reproduce it after a fresh install of Codewind.  If I remove the project and add it again then the logs are fine.

```
[32m[18/09/19 04:46:19 Turbine] [INFO][39m Fetching logs for project 40a16f10-d9cf-11e9-bd63-2b348e4ccf50
[32m[18/09/19 04:46:19 rogue-cloud-client-codewind] [INFO][39m buildlog path:
 {"origin":"workspace","files":[]}
[32m[18/09/19 04:46:19 rogue-cloud-client-codewind] [INFO][39m Looking for all log files in container cw-roguecloudclientcodewind-40a16f10-d9cf-11e9-bd63-2b348e4ccf50
[91m[18/09/19 04:46:19 Turbine] [ERROR][39m [File Name: /file-watcher/server/dist/projects/logHelper.js | Function Name: getLogFilesFromContainer | Line Number: 132] Failed to get the list of log files from /tmp/liberty/liberty/wlp/usr/servers/defaultServer/logs/
[91m[18/09/19 04:46:19 Turbine] [ERROR][39m [File Name: /file-watcher/server/dist/projects/logHelper.js | Function Name: getLogFilesFromContainer | Line Number: 133] TypeError: logFiles is not iterable
[32m[18/09/19 04:46:19 rogue-cloud-client-codewind] [INFO][39m Looking for file existency for /codewind-workspace/rogue-cloud-client-codewind/mc-target/liberty/wlp/usr/servers/defaultServer/logs/ffdc in container cw-roguecloudclientcodewind-40a16f10-d9cf-11e9-bd63-2b348e4ccf50
[91m[18/09/19 04:46:19 rogue-cloud-client-codewind] [ERROR][39m Error getting docker container exec object
[91m[18/09/19 04:46:19 rogue-cloud-client-codewind] [ERROR][39m Error checking existence for /tmp/liberty/liberty/wlp/usr/servers/defaultServer/logs/ in container cw-roguecloudclientcodewind-40a16f10-d9cf-11e9-bd63-2b348e4ccf50
[91m[18/09/19 04:46:19 rogue-cloud-client-codewind] [ERROR][39m { Error: (HTTP code 404) no such container - No such container: cw-roguecloudclientcodewind-40a16f10-d9cf-11e9-bd63-2b348e4ccf50 
    at /file-watcher/server/node_modules/docker-modem/lib/modem.js:257:17
    at getCause (/file-watcher/server/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/file-watcher/server/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/file-watcher/server/node_modules/docker-modem/lib/modem.js:232:14)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  reason: 'no such container',
  statusCode: 404,
  json:
   { message:
      'No such container: cw-roguecloudclientcodewind-40a16f10-d9cf-11e9-bd63-2b348e4ccf50' } }
```

**Comment by eharris369** [comment]
Full log file: [logs.txt](https://github.com/eclipse/codewind/files/3687836/logs.txt)
