### ISSUE TITLE
[Performance] 0.4.0 Cannot run load test against Microprofile

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#587]
**Codewind version:** 0.4.0
**OS:** Mac

**Che version:**
**IDE extension version:** Eclipse Codewind 0.4.0
**IDE version:** 
**Kubernetes cluster:**

**Description:**
Cannot run load test against Microprofile

**Steps to reproduce:**
On Eclipse Codewind plugin; Right Click on a Microprofile project -> Open Performance Dashboard -> Run Load Test -> Give a name -> Run

**Logs:** 
```
[30/09/19 18:18:43 server.js] [INFO] req.originalUrl = /performance/charts?project=107ccda0-e3ae-11e9-948d-21a684f6f888
[30/09/19 18:18:43 server.js] [INFO] url = http://codewind-performance:9095/performance/charts?project=107ccda0-e3ae-11e9-948d-21a684f6f888
[30/09/19 18:18:43 server.js] [INFO] req.originalUrl = /performance/static/bundle.js
[30/09/19 18:18:43 server.js] [INFO] url = http://codewind-performance:9095/performance/static/bundle.js
[30/09/19 18:18:43 server.js] [INFO] req.originalUrl = /performance/styles/styles.js
[30/09/19 18:18:43 server.js] [INFO] url = http://codewind-performance:9095/performance/styles/styles.js
[30/09/19 18:18:43 server.js] [INFO] req.originalUrl = /performance/main.js
[30/09/19 18:18:43 server.js] [INFO] url = http://codewind-performance:9095/performance/main.js
[30/09/19 18:18:43 server.js] [INFO] req.originalUrl = /performance/static/a12899d4fba68cb1646e2a6212e01b6b.png
[30/09/19 18:18:43 server.js] [INFO] url = http://codewind-performance:9095/performance/static/a12899d4fba68cb1646e2a6212e01b6b.png
[30/09/19 18:18:54 LoadRunner.js] [INFO] beginJavaProfiling: Stopping liberty server
[30/09/19 18:18:56 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:56 test789] [INFO] Application state changed for project: 107ccda0-e3ae-11e9-948d-21a684f6f888 from: started, to: stopping
[30/09/19 18:18:56 test789] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "107ccda0-e3ae-11e9-948d-21a684f6f888",
  "appStatus": "stopping"
}
[30/09/19 18:18:56 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:56 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:56 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:56 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:56 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:56 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:56 test789] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/maven.build.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/docker.build.log"]}
[30/09/19 18:18:56 test789] [INFO] applog path:
{"origin":"workspace","files":["/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/console.log","/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/app.log"]}
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 test789] [INFO] Application state changed for project: 107ccda0-e3ae-11e9-948d-21a684f6f888 from: stopping, to: stopped
[30/09/19 18:18:57 test789] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "107ccda0-e3ae-11e9-948d-21a684f6f888",
  "appStatus": "stopped"
}
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 test789] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/maven.build.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/docker.build.log"]}
[30/09/19 18:18:57 test789] [INFO] applog path:
{"origin":"workspace","files":["/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/console.log","/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/app.log"]}
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:57 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:18:59 LoadRunner.js] [INFO] { Error: connect ECONNREFUSED 192.168.48.6:9080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.48.6',
  port: 9080 }
[30/09/19 18:18:59 LoadRunner.js] [INFO] beginJavaProfiling: Starting liberty server
[30/09/19 18:19:00 test789] [INFO] pingApplications: Application state error message: Error: connect ECONNREFUSED 192.168.48.6:9080
[30/09/19 18:19:04 LoadRunner.js] [INFO] { Error: connect ECONNREFUSED 192.168.48.6:9080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.48.6',
  port: 9080 }
[30/09/19 18:19:16 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:19:16 test789] [INFO] Application state changed for project: 107ccda0-e3ae-11e9-948d-21a684f6f888 from: stopped, to: starting
[30/09/19 18:19:16 test789] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "107ccda0-e3ae-11e9-948d-21a684f6f888",
  "appStatus": "starting"
}
[30/09/19 18:19:16 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:19:16 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:19:16 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:19:16 test789] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/maven.build.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/docker.build.log"]}
[30/09/19 18:19:16 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:19:16 User.js] [INFO] Updating status for project 107ccda0-e3ae-11e9-948d-21a684f6f888.
[30/09/19 18:19:16 test789] [INFO] applog path:
{"origin":"workspace","files":["/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log","/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/console.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/app.log"]}
[30/09/19 18:19:17 Turbine] [INFO] typeof projectHandler.getContainerName is undefined
[30/09/19 18:19:17 test789] [INFO] Application state changed for project: 107ccda0-e3ae-11e9-948d-21a684f6f888 from: starting, to: starting, with message: Pinging http://192.168.48.6:9080/health and http://192.168.48.6:9080/
[30/09/19 18:19:17 test789] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "107ccda0-e3ae-11e9-948d-21a684f6f888",
  "appStatus": "starting",
  "detailedAppStatus": "Pinging http://192.168.48.6:9080/health and http://192.168.48.6:9080/"
}
[30/09/19 18:19:17 Turbine] [INFO] Fetching logs for project 107ccda0-e3ae-11e9-948d-21a684f6f888
[30/09/19 18:19:17 test789] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/maven.build.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/docker.build.log"]}
[30/09/19 18:19:17 test789] [INFO] applog path:
{"origin":"workspace","files":["/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log","/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/console.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/app.log"]}
[30/09/19 18:19:18 test789] [INFO] pingInTransitApplications: Application state error message: Http request is failed due to timeout error
[30/09/19 18:19:19 Turbine] [INFO] typeof projectHandler.getContainerName is undefined
[30/09/19 18:19:19 ProjectList.js] [INFO] Project test789 started (project ID: 107ccda0-e3ae-11e9-948d-21a684f6f888)
[30/09/19 18:19:19 test789] [INFO] pingInTransitApplications: Application state for project 107ccda0-e3ae-11e9-948d-21a684f6f888 has changed from starting to started
[30/09/19 18:19:19 test789] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "107ccda0-e3ae-11e9-948d-21a684f6f888",
  "appStatus": "started",
  "detailedAppStatus": " "
}
[30/09/19 18:19:19 Turbine] [INFO] Fetching logs for project 107ccda0-e3ae-11e9-948d-21a684f6f888
[30/09/19 18:19:19 test789] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/maven.build.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/docker.build.log"]}
[30/09/19 18:19:19 test789] [INFO] applog path:
{"origin":"workspace","files":["/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log","/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/console.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/app.log"]}
[30/09/19 18:19:19 LoadRunner.js] [INFO] httpCheckHealth 200
[30/09/19 18:19:19 LoadRunner.js] [INFO] LibertyServer has responded to /health
[30/09/19 18:19:19 LoadRunner.js] [ERROR] createCollection: unable to create metrics collection: 404
[30/09/19 18:19:20 LoadRunner.js] [INFO] Load run on project 107ccda0-e3ae-11e9-948d-21a684f6f888 started
[30/09/19 18:19:31 test789] [INFO] pingApplications: Application state error message: Http request is failed due to timeout error
[30/09/19 18:19:31 test789] [INFO] pingApplications: Application state for project 107ccda0-e3ae-11e9-948d-21a684f6f888 has changed from started to stopped
[30/09/19 18:19:31 test789] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "107ccda0-e3ae-11e9-948d-21a684f6f888",
  "appStatus": "stopped"
}
[30/09/19 18:19:31 test789] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/maven.build.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/docker.build.log"]}
[30/09/19 18:19:31 test789] [INFO] applog path:
{"origin":"workspace","files":["/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/console.log","/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/app.log"]}
[30/09/19 18:19:32 ProjectList.js] [INFO] Project test789 started (project ID: 107ccda0-e3ae-11e9-948d-21a684f6f888)
[30/09/19 18:19:32 test789] [INFO] pingApplications: Application state for project 107ccda0-e3ae-11e9-948d-21a684f6f888 has changed from stopped to started
[30/09/19 18:19:32 test789] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "107ccda0-e3ae-11e9-948d-21a684f6f888",
  "appStatus": "started"
}
[30/09/19 18:19:32 test789] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/maven.build.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/docker.build.log"]}
[30/09/19 18:19:32 test789] [INFO] applog path:
{"origin":"workspace","files":["/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/console.log","/codewind-workspace/test789/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log","/codewind-workspace/.logs/test789-107ccda0-e3ae-11e9-948d-21a684f6f888/app.log"]}
[30/09/19 18:19:40 LoadRunner.js] [INFO] Load run on project 107ccda0-e3ae-11e9-948d-21a684f6f888 completed
[30/09/19 18:19:40 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/test789/load-test/20190930181854
[30/09/19 18:19:40 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/test789/load-test/20190930181854
[30/09/19 18:19:40 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/test789/load-test/20190930181854
[30/09/19 18:19:40 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/test789/load-test/20190930181854
[30/09/19 18:19:40 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/test789/load-test/20190930181854
[30/09/19 18:19:40 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/test789/load-test/20190930181854
[30/09/19 18:19:40 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/test789/load-test/20190930181854
[30/09/19 18:19:40 /portal/modules/Project.js] [ERROR] No metrics.json found in directory /codewind-workspace/test789/load-test/20190930181854
```

**Comment by maysunfaisal** [comment]
Tried this multiple times with 3 different Microprofile projects, same log stack trace.

**Comment by tobespc** [comment]
umm, getting something similar with vscode as well

**Comment by tobespc** [comment]
After restarting codewind this all works ok.  @maysunfaisal could you try stopping and starting codewind and then starting with a new project please

**Comment by maysunfaisal** [comment]
@tobespc oops I forgot to add, yes I was able to get around it by restarting. But cant do that in a demo infront of customers :)

**Comment by tobespc** [comment]
this is working ok in 0.5.0
