### ISSUE TITLE
NPE in FW CodewindResourceChangeListener when deleting a project

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#61]
Steps to reproduce:
1. Open the Codewind Eclipse IDE on the codewind-workspace folder
2. Create any project from File->New wizard (Can be a general project)
3. Delete the project
--> You'll get an NPE

It looks like FW is watching the entire codewind workspace and not only the projects it knows about.

java.lang.NullPointerException
	at org.eclipse.codewind.filewatchers.eclipse.CodewindResourceChangeListener.resourceChanged(CodewindResourceChangeListener.java:43)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.handleEvent(NotificationManager.java:271)
	at org.eclipse.core.internal.resources.Workspace.broadcastEvent(Workspace.java:374)
	at org.eclipse.core.internal.resources.Resource.broadcastPreDeleteEvent(Resource.java:1826)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:737)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:322)
	at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:158)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:283)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:283)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:260)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:308)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:99)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:219)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by jgwest** [comment]
Likely a dupe of https://github.com/eclipse/codewind-eclipse/issues/156
