### ISSUE TITLE
Turbine tests broken

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#613]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
`npm run unit:test` fails with 

```
/Users/maysun/dev/eclipse/codewind/src/pfe/file-watcher/server

/Users/maysun/dev/eclipse/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:70
     *
                                                                                         ^
TypeError: projectUtil.getAllProjectInfo is not a function
    at initAppStateMap (/Users/maysun/dev/eclipse/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:70:90)
    at Object.<anonymous> (/Users/maysun/dev/eclipse/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:33:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

```

**Steps to reproduce:**
Switching to commit before the ODO PR (`added a test for getting name and description from templates.json`)
```
git checkout f8bde84cb163a5791ca40ca70d037ece6ea8477b
```

-> Ran tests, it was fine.

Adding ODO PR first commit (`odo extension`)
```
git cherry-pick 82be6aaf7725bdf50382051cca695bec44fc2677
```

-> Ran tests, tests broken

you can see the commit hash from here https://github.com/eclipse/codewind/commits/master

**Comment by maysunfaisal** [comment]
I didnt see it in the PFE log, so dont think this is an actual issue with the product

but only on nyc mocha execs:

```
maysuns-mbp:server maysun$ nyc mocha test/functional-test/functional.test.ts

/Users/maysun/dev/eclipse/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:70
     *
                                                                                         ^
TypeError: projectUtil.getAllProjectInfo is not a function
    at initAppStateMap (/Users/maysun/dev/eclipse/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:70:90)
    at Object.<anonymous> (/Users/maysun/dev/eclipse/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:33:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.replacementCompile (/usr/local/lib/
```
```
maysuns-mbp:server maysun$ nyc mocha test/unit-test/unit.test.ts

/Users/maysun/dev/eclipse/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:70
     *
                                                                                         ^
TypeError: projectUtil.getAllProjectInfo is not a function
    at initAppStateMap (/Users/maysun/dev/eclipse/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:70:90)
    at Object.<anonymous> (/Users/maysun/dev/eclipse/codewind/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts:33:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.replacementCompile (/usr/local/lib/node_modules/nyc/node_modules/append-transform/index.js:58:13)

```

**Comment by maysunfaisal** [comment]
Found the issue: 

it is because of https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/utils/kubeutil.ts#L23

Removing that import from the `odo extension` commit `82be6aaf7725bdf50382051cca695bec44fc2677` solves the issue.

However, the PR has two more commits, so those would need to be checked as well

**Comment by rajivnathan** [comment]
@jingfuwang why do we need the project handler to get the app name here? Shouldn't that be in the projectInfo already? If not, should it be added to the projectInfo? Either way, doesn't seem necessary to import `projectExtensions` here?

```
const projectHandler = await projectExtensions.getProjectHandler(projectInfo);
const appName = await projectHandler.getAppName(projectID);
```

**Comment by maysunfaisal** [comment]
I think this is using the odo command to get app name because Turbine's project name is Odo's component name, and here the app name is the actual Odo's app name

**Comment by GeekArthur** [comment]
Maysun's explanation is correct. We run the get app script inside project folder that has its own .odo, so only get the app name for the component.

**Comment by GeekArthur** [comment]
I like Rajiv's suggestion, but that's not related with the `Turbine tests broken`, that's a separate issue.

**Comment by ssh24** [comment]
@maysunfaisal This can be closed now
