### ISSUE TITLE
UnhandledPromiseRejectionWarning when setting an invalid log level

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#627]
**Description:**
From the test logs
```
17:47:29  [91m[05/10/19 21:47:29 Turbine] [ERROR][39m [File Name: /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-554/src/pfe/file-watcher/server/src/utils/logger.ts | Function Name: setLoggingLevel | Line Number: 11] wronglevel is not a valid value, the following log levels are available {"error":"error","warn":"warn","info":"info","debug":"debug","trace":"trace"}
17:47:29  (node:71475) UnhandledPromiseRejectionWarning: Error: wronglevel is not a valid value, the following log levels are available {"error":"error","warn":"warn","info":"info","debug":"debug","trace":"trace"}
17:47:29      at Object.setLoggingLevel (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-554/src/pfe/file-watcher/server/src/utils/logger.ts:11:14)
17:47:29      at Context.it (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-554/src/pfe/file-watcher/server/test/unit-test/tests/logger.module.test.ts:540:24)
17:47:29      at callFn (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-554/src/pfe/file-watcher/server/node_modules/mocha/lib/runnable.js:387:21)
17:47:29      at Test.Runnable.run (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-554/src/pfe/file-watcher/server/node_modules/mocha/lib/runnable.js:379:7)
17:47:29      at Runner.runTest (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-554/src/pfe/file-watcher/server/node_modules/mocha/lib/runner.js:535:10)
17:47:29      at /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-554/src/pfe/file-watcher/server/node_modules/mocha/lib/runner.js:653:12
17:47:29      at next (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-554/src/pfe/file-watcher/server/node_modules/mocha/lib/runner.js:447:14)
17:47:29      at /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-554/src/pfe/file-watcher/server/node_modules/mocha/lib/runner.js:457:7
17:47:29      at next (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-554/src/pfe/file-watcher/server/node_modules/mocha/lib/runner.js:362:14)
17:47:29      at Immediate.<anonymous> (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-554/src/pfe/file-watcher/server/node_modules/mocha/lib/runner.js:425:5)
17:47:29      at runCallback (timers.js:705:18)
17:47:29      at tryOnImmediate (timers.js:676:5)
17:47:29      at processImmediate (timers.js:658:5)
17:47:29  (node:71475) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
17:47:29  (node:71475) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to reproduce:**
This was seen by running the Turbine unit tests but you should be able to reproduce by calling the Turbine setLoggingLevel API with an invalid level.

**Comment by ssh24** [comment]
I only see
```
[07/10/19 16:08:30 Turbine] [ERROR] [File Name: /file-watcher/server/src/utils/logger.ts | Function Name: setLoggingLevel | Line Number: 11] invalid is not a valid value, the following log levels are available {"error":"error","warn":"warn","info":"info","debug":"debug","trace":"trace"}
```
@rajivnathan  Which test did you run to see this?

**Comment by ssh24** [comment]
@rajivnathan Could you please assign this to me?

**Comment by ssh24** [comment]
@rajivnathan This can be verified and closed now

**Comment by rajivnathan** [comment]
Don't see the error in the latest run: https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/PR-554/30/consoleFull
Thanks Sakib!
