### ISSUE TITLE
Liberty projects failing to build on local

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#693]
**Description:**
With the latest master code as of October 16, liberty projects are failing to build. It is failing on the maven build step for extracting the cache
```[16/10/19 14:46:13 mylib] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "62884490-f023-11e9-bea3-0b22d733c7da",
  "buildStatus": "inProgress",
  "detailedBuildStatus": "Compiling application"
}
[16/10/19 14:46:14 mylib] [TRACE] Extracting maven m2 cache to /home/default

[16/10/19 14:46:14 mylib] [TRACE] Triggering log file event for: maven build log

[16/10/19 14:46:14 server.js] [TRACE] GET /internal/api/v1/projects/62884490-f023-11e9-bea3-0b22d733c7da/logs/build called with 
 req.body {}
[16/10/19 14:46:14 /portal/routes/projects/internal.route.js] [DEBUG] Internal API: get new logs
[16/10/19 14:46:14 User.js] [INFO] Check for new log files for project 62884490-f023-11e9-bea3-0b22d733c7da
[16/10/19 14:46:14 FileWatcher.js] [INFO] Check for new build log files for project 62884490-f023-11e9-bea3-0b22d733c7da
[16/10/19 14:46:14 Turbine] [INFO] Fetching logs for project 62884490-f023-11e9-bea3-0b22d733c7da
[16/10/19 14:46:14 mylib] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/mylib-62884490-f023-11e9-bea3-0b22d733c7da/docker.build.log"]}
[16/10/19 14:46:14 mylib] [INFO] applog path:
{"origin":"workspace","files":[]}
[16/10/19 14:46:14 FileWatcher.js] [DEBUG] Received filewatcher module response: 
[16/10/19 14:46:14 FileWatcher.js] [DEBUG] {"statusCode":200}
[16/10/19 14:46:14 server.js] [TRACE] responded to GET /internal/api/v1/projects/62884490-f023-11e9-bea3-0b22d733c7da/logs/build with status 200 and body {}
[16/10/19 14:46:14 server.js] [TRACE] Checking origin host  matches expected host localhost:9090
[16/10/19 14:46:14 server.js] [TRACE] POST /internal/api/v1/projects/updateStatus called with 
 req.body { projectID: '62884490-f023-11e9-bea3-0b22d733c7da',
  buildStatus: 'failed',
  detailedBuildStatus: 'buildApplicationTask.buildFail',
  type: 'buildState' }
```

**Steps to reproduce:**
1. Bring up a latest master codewind build
2. Create a liberty project
3. You will see the liberty project failed to build

Full log
[liberty.local.log](https://github.com/eclipse/codewind/files/3734979/liberty.local.log)

**Comment by maysunfaisal** [comment]
```
[16/10/19 21:03:22 testwed22] [TRACE]  ---> 6d5bf5650909
Step 24/24 : USER default

[16/10/19 21:03:22 testwed22] [TRACE]  ---> Running in 3308c5f94a17

[16/10/19 21:03:22 testwed22] [TRACE] Removing intermediate container 3308c5f94a17
 ---> f8865693bbad

[16/10/19 21:03:22 testwed22] [TRACE] Successfully built f8865693bbad

[16/10/19 21:03:22 testwed22] [TRACE] Successfully tagged cw-testwed22-4958b790-f058-11e9-b2cb-613134cbb16b:latest

[16/10/19 21:03:22 testwed22] [TRACE] Successfully built cw-testwed22-4958b790-f058-11e9-b2cb-613134cbb16b

[16/10/19 21:03:22 testwed22] [TRACE] Container image has been built successfully

[16/10/19 21:03:22 testwed22] [TRACE] Updating build state for project testwed22(4958b790-f058-11e9-b2cb-613134cbb16b) to: inProgress

[16/10/19 21:03:22 server.js] [TRACE] Checking origin host  matches expected host localhost:9090
[16/10/19 21:03:22 server.js] [TRACE] POST /internal/api/v1/projects/updateStatus called with 
 req.body { projectID: '4958b790-f058-11e9-b2cb-613134cbb16b',
  buildStatus: 'inProgress',
  detailedBuildStatus: 'containerBuildTask.containerBuildSuccess',
  appImageLastBuild: '1571259802973',
  type: 'buildState' }
[16/10/19 21:03:22 /portal/routes/projects/internal.route.js] [DEBUG] Internal API: updateStatus
[16/10/19 21:03:22 User.js] [INFO] Updating status for project 4958b790-f058-11e9-b2cb-613134cbb16b.
[16/10/19 21:03:22 Turbine] [TRACE] Key translated. Returning message: Container image has been built successfully
[16/10/19 21:03:22 FileWatcher.js] [DEBUG] Portal's event listener: projectStatusChanged
[16/10/19 21:03:22 FileWatcher.js] [DEBUG] Portal's event listener: {"projectID":"4958b790-f058-11e9-b2cb-613134cbb16b","buildStatus":"inProgress","detailedBuildStatus":"Container image has been built successfully","appImageLastBuild":"1571259802973"}
[16/10/19 21:03:22 FileWatcher.js] [DEBUG] projectStatusChanged: inProgress (project 4958b790-f058-11e9-b2cb-613134cbb16b)
[16/10/19 21:03:22 FileWatcher.js] [TRACE] projectStatusChanged: inProgress (project: {
  "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b",
  "buildStatus": "inProgress",
  "detailedBuildStatus": "Container image has been built successfully",
  "appImageLastBuild": "1571259802973"
})
[16/10/19 21:03:22 FileWatcher.js] [DEBUG] Received filewatcher module response: 
[16/10/19 21:03:22 FileWatcher.js] [DEBUG] {"statusCode":200}
[16/10/19 21:03:22 server.js] [TRACE] responded to POST /internal/api/v1/projects/updateStatus with status 200 and body { projectID: '4958b790-f058-11e9-b2cb-613134cbb16b',
  buildStatus: 'inProgress',
  detailedBuildStatus: 'containerBuildTask.containerBuildSuccess',
  appImageLastBuild: '1571259802973',
  type: 'buildState' }
[16/10/19 21:03:22 testwed22] [INFO] Build state changed for project: 4958b790-f058-11e9-b2cb-613134cbb16b from: inProgress, to: inProgress, with message: containerBuildTask.containerBuildSuccess
[16/10/19 21:03:22 testwed22] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b",
  "buildStatus": "inProgress",
  "detailedBuildStatus": "Container image has been built successfully",
  "appImageLastBuild": "1571259802973"
}
[16/10/19 21:03:22 testwed22] [TRACE] Container built
* Starting container. 
Start the container
Run command to start the container: /file-watcher/idc/artifacts/run_docker.sh cw-testwed22-4958b790-f058-11e9-b2cb-613134cbb16b cw-testwed22-4958b790-f058-11e9-b2cb-613134cbb16b "-p 127.0.0.1::7777 -P" /codewind-workspace/.idc/docker/docker-2311597732d65a7bb80ede993d94298ef9844f13 /codewind-workspace "testwed22-4958b790-f058-11e9-b2cb-613134cbb16b" false

[16/10/19 21:03:23 testwed22] [TRACE] Running codewind app container for /codewind-workspace/testwed22 using container name cw-testwed22-4958b790-f058-11e9-b2cb-613134cbb16b
Application path used for volume mounting is: /codewind-workspace/testwed22
Log path used for volume mounting is: /codewind-workspace/.logs/testwed22-4958b790-f058-11e9-b2cb-613134cbb16b

[16/10/19 21:03:23 testwed22] [TRACE] 4147420355f2e0640b74201f1763bb5d7ebad963b64a7af970025950117c81bb

[16/10/19 21:03:25 testwed22] [TRACE] Stored application container for testwed22: 4147420355f2e0640b74201f1763bb5d7ebad963b64a7af970025950117c81bb

[16/10/19 21:03:25 testwed22] [INFO] Internal port: 9080
[16/10/19 21:03:25 testwed22] [INFO] Exposed port: 32898
[16/10/19 21:03:25 testwed22] [INFO] Internal debug port: 
[16/10/19 21:03:25 testwed22] [INFO] Exposed debug port: 
[16/10/19 21:03:25 testwed22] [INFO] All the exposed container ports: ["7777","9080","9443"]
[16/10/19 21:03:25 testwed22] [INFO] All the host ports: ["32827","32898","32897"]
[16/10/19 21:03:25 testwed22] [INFO] pingApplications: Application state error message: Error: connect ECONNREFUSED 192.168.224.4:9080
[16/10/19 21:03:25 testwed22] [TRACE] Log file name for build: cw-4958b790-f058-11e9-b2cb-613134cbb16b-2311597732d65a7bb80ede993d94298ef9844f13

[16/10/19 21:03:25 testwed22] [TRACE] Compiling application for project testwed22

[16/10/19 21:03:25 testwed22] [TRACE] Updating build state for project testwed22(4958b790-f058-11e9-b2cb-613134cbb16b) to: inProgress

[16/10/19 21:03:25 server.js] [TRACE] Checking origin host  matches expected host localhost:9090
[16/10/19 21:03:25 server.js] [TRACE] POST /internal/api/v1/projects/updateStatus called with 
 req.body { projectID: '4958b790-f058-11e9-b2cb-613134cbb16b',
  buildStatus: 'inProgress',
  detailedBuildStatus: 'buildApplicationTask.compileApplication',
  type: 'buildState' }
[16/10/19 21:03:25 /portal/routes/projects/internal.route.js] [DEBUG] Internal API: updateStatus
[16/10/19 21:03:25 User.js] [INFO] Updating status for project 4958b790-f058-11e9-b2cb-613134cbb16b.
[16/10/19 21:03:25 Turbine] [TRACE] Key translated. Returning message: Compiling application
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] Portal's event listener: projectStatusChanged
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] Portal's event listener: {"projectID":"4958b790-f058-11e9-b2cb-613134cbb16b","buildStatus":"inProgress","detailedBuildStatus":"Compiling application"}
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] projectStatusChanged: inProgress (project 4958b790-f058-11e9-b2cb-613134cbb16b)
[16/10/19 21:03:25 FileWatcher.js] [TRACE] projectStatusChanged: inProgress (project: {
  "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b",
  "buildStatus": "inProgress",
  "detailedBuildStatus": "Compiling application"
})
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] Received filewatcher module response: 
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] {"statusCode":200}
[16/10/19 21:03:25 server.js] [TRACE] responded to POST /internal/api/v1/projects/updateStatus with status 200 and body { projectID: '4958b790-f058-11e9-b2cb-613134cbb16b',
  buildStatus: 'inProgress',
  detailedBuildStatus: 'buildApplicationTask.compileApplication',
  type: 'buildState' }
[16/10/19 21:03:25 testwed22] [INFO] Build state changed for project: 4958b790-f058-11e9-b2cb-613134cbb16b from: inProgress, to: inProgress, with message: buildApplicationTask.compileApplication
[16/10/19 21:03:25 testwed22] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b",
  "buildStatus": "inProgress",
  "detailedBuildStatus": "Compiling application"
}
[16/10/19 21:03:25 testwed22] [TRACE] Triggering log file event for: maven build log

[16/10/19 21:03:25 server.js] [TRACE] GET /internal/api/v1/projects/4958b790-f058-11e9-b2cb-613134cbb16b/logs/build called with 
 req.body {}
[16/10/19 21:03:25 /portal/routes/projects/internal.route.js] [DEBUG] Internal API: get new logs
[16/10/19 21:03:25 User.js] [INFO] Check for new log files for project 4958b790-f058-11e9-b2cb-613134cbb16b
[16/10/19 21:03:25 FileWatcher.js] [INFO] Check for new build log files for project 4958b790-f058-11e9-b2cb-613134cbb16b
[16/10/19 21:03:25 Turbine] [INFO] Fetching logs for project 4958b790-f058-11e9-b2cb-613134cbb16b
[16/10/19 21:03:25 testwed22] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/testwed22-4958b790-f058-11e9-b2cb-613134cbb16b/docker.build.log"]}
[16/10/19 21:03:25 testwed22] [INFO] applog path:
{"origin":"workspace","files":[]}
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] Received filewatcher module response: 
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] {"statusCode":200}
[16/10/19 21:03:25 server.js] [TRACE] responded to GET /internal/api/v1/projects/4958b790-f058-11e9-b2cb-613134cbb16b/logs/build with status 200 and body {}
[16/10/19 21:03:25 testwed22] [ERROR] executeBuildScript : 393 | Application build failed for project testwed22. Please check the log in the build log view for more details

[16/10/19 21:03:25 testwed22] [TRACE] Updating build state for project testwed22(4958b790-f058-11e9-b2cb-613134cbb16b) to: failed

[16/10/19 21:03:25 server.js] [TRACE] Checking origin host  matches expected host localhost:9090
[16/10/19 21:03:25 server.js] [TRACE] POST /internal/api/v1/projects/updateStatus called with 
 req.body { projectID: '4958b790-f058-11e9-b2cb-613134cbb16b',
  buildStatus: 'failed',
  detailedBuildStatus: 'buildApplicationTask.buildFail',
  type: 'buildState' }
[16/10/19 21:03:25 /portal/routes/projects/internal.route.js] [DEBUG] Internal API: updateStatus
[16/10/19 21:03:25 User.js] [INFO] Updating status for project 4958b790-f058-11e9-b2cb-613134cbb16b.
[16/10/19 21:03:25 Turbine] [TRACE] Key translated. Returning message: Application build failed. Please check the log in the build log view for more details.
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] Portal's event listener: projectStatusChanged
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] Portal's event listener: {"projectID":"4958b790-f058-11e9-b2cb-613134cbb16b","buildStatus":"failed","detailedBuildStatus":"Application build failed. Please check the log in the build log view for more details.","lastbuild":1571259805478}
[16/10/19 21:03:25 FileWatcher.js] [ERROR] projectStatusChanged: failed (project: {
  "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b",
  "buildStatus": "failed",
  "detailedBuildStatus": "Application build failed. Please check the log in the build log view for more details.",
  "lastbuild": 1571259805478
})
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] projectStatusChanged: failed (project 4958b790-f058-11e9-b2cb-613134cbb16b)
[16/10/19 21:03:25 FileWatcher.js] [TRACE] projectStatusChanged: failed (project: {
  "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b",
  "buildStatus": "failed",
  "detailedBuildStatus": "Application build failed. Please check the log in the build log view for more details.",
  "lastbuild": 1571259805478
})
[16/10/19 21:03:25 testwed22] [INFO] Validating project using operationId: 7a3bde7da090e798b280efa29d2770f9
[16/10/19 21:03:25 Turbine] [TRACE] {"projectType":"liberty","location":"/codewind-workspace/testwed22","projectID":"4958b790-f058-11e9-b2cb-613134cbb16b"}
[16/10/19 21:03:25 testwed22] [INFO] Checking for required files
[16/10/19 21:03:25 testwed22] [INFO] Checking for required file /Dockerfile | /Dockerfile-lang
[16/10/19 21:03:25 testwed22] [INFO] Build state changed for project: 4958b790-f058-11e9-b2cb-613134cbb16b from: inProgress, to: failed, with message: buildApplicationTask.buildFail
[16/10/19 21:03:25 testwed22] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b",
  "buildStatus": "failed",
  "detailedBuildStatus": "Application build failed. Please check the log in the build log view for more details.",
  "lastbuild": 1571259805478
}
[16/10/19 21:03:25 testwed22] [INFO] Kicking off validation for project: 4958b790-f058-11e9-b2cb-613134cbb16b
[16/10/19 21:03:25 testwed22] [INFO] Checking for required file /Dockerfile-build
[16/10/19 21:03:25 testwed22] [INFO] Checking for required file /pom.xml
[16/10/19 21:03:25 testwed22] [INFO] Checking for required file /src/main/liberty/config/server.xml
[16/10/19 21:03:25 testwed22] [INFO] Sending validation result
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] Portal's event listener: projectValidated
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] Portal's event listener: {"operationId":"7a3bde7da090e798b280efa29d2770f9","projectType":"liberty","location":"/codewind-workspace/testwed22","projectID":"4958b790-f058-11e9-b2cb-613134cbb16b","status":"success","results":[],"operation":{"operationId":"7a3bde7da090e798b280efa29d2770f9","type":"validate","projectInfo":{"projectType":"liberty","location":"/codewind-workspace/testwed22","projectID":"4958b790-f058-11e9-b2cb-613134cbb16b"}}}
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] projectValidated: success (project 4958b790-f058-11e9-b2cb-613134cbb16b)
[16/10/19 21:03:25 FileWatcher.js] [TRACE] projectValidated: success (project: {
  "operationId": "7a3bde7da090e798b280efa29d2770f9",
  "projectType": "liberty",
  "location": "/codewind-workspace/testwed22",
  "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b",
  "status": "success",
  "results": [],
  "operation": {
    "operationId": "7a3bde7da090e798b280efa29d2770f9",
    "type": "validate",
    "projectInfo": {
      "projectType": "liberty",
      "location": "/codewind-workspace/testwed22",
      "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b"
    }
  }
})
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] Received filewatcher module response: 
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] {"statusCode":200}
[16/10/19 21:03:25 server.js] [TRACE] responded to POST /internal/api/v1/projects/updateStatus with status 200 and body { projectID: '4958b790-f058-11e9-b2cb-613134cbb16b',
  buildStatus: 'failed',
  detailedBuildStatus: 'buildApplicationTask.buildFail',
  type: 'buildState' }
[16/10/19 21:03:25 testwed22] [INFO] Emitting event 
 message: projectValidated
 data: {
  "operationId": "7a3bde7da090e798b280efa29d2770f9",
  "projectType": "liberty",
  "location": "/codewind-workspace/testwed22",
  "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b",
  "status": "success",
  "results": [],
  "operation": {
    "operationId": "7a3bde7da090e798b280efa29d2770f9",
    "type": "validate",
    "projectInfo": {
      "projectType": "liberty",
      "location": "/codewind-workspace/testwed22",
      "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b"
    }
  }
}
[16/10/19 21:03:25 testwed22] [ERROR] executeBuildScript : 393 | Application build failed.

[16/10/19 21:03:25 testwed22] [ERROR] [ File Name: /file-watcher/server/dist/projects/projectUtil.js | Function Name: processManager.spawnDetached | Line Number: 398] Error code: 3 - The container failed to start for application /codewind-workspace/testwed22
[16/10/19 21:03:25 Turbine] [TRACE] Key translated. Returning message: Creating image for build failed
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] Portal's event listener: projectStatusChanged
[16/10/19 21:03:25 FileWatcher.js] [DEBUG] Portal's event listener: {"projectID":"4958b790-f058-11e9-b2cb-613134cbb16b","buildStatus":"failed","detailedBuildStatus":"Creating image for build failed","lastbuild":1571259805572}
[16/10/19 21:03:25 FileWatcher.js] [ERROR] projectStatusChanged: failed (project: {
  "projectID": "4958b790-f058-11e9-b2cb-613134cbb16b",
  "buildStatus": "failed",
  "detailedBuildStatus": "Creating image for build failed",
  "lastbuild": 1571259805572
})
```

**Comment by maysunfaisal** [comment]
Looks like `run_docker.sh` is not working. I never see a container even tho it says "success"

```
maysuns-mbp:test maysun$ d ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
416edc6b2151        codewind-pfe-amd64:latest           "sh -c ' /file-watch…"   33 minutes ago      Up 33 minutes       127.0.0.1:9777->9777/tcp, 127.0.0.1:34023->9090/tcp   codewind-pfe
40e3d0d31db6        codewind-performance-amd64:latest   "docker-entrypoint.s…"   33 minutes ago      Up 33 minutes       127.0.0.1:9095->9095/tcp                              codewind-performance
```

Probably the script was messed up with the hybrid change?

**Comment by ssh24** [comment]
I think this could be the issue https://github.com/eclipse/codewind/pull/694

Basically with the hybrid change, the LOCAL_WORKSPACE variable was not safeguarded causing project types like appsody and maybe others to fall to the remote setting value. We can try after 694 lands to see if that fixes it or it is something else.

**Comment by rajivnathan** [comment]
Yeah, the container comes up but then exits right away because the entrypoint can't find the `libertyrepocache.zip` file which means that it's a volume mount issue. So I believe you're right, might be fixed once #694 is fixed.

```
Extracting liberty feature cache to /home/default/artifacts
java.io.FileNotFoundException: /home/default/app/libertyrepocache.zip (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:212)
	at java.io.FileInputStream.<init>(FileInputStream.java:152)
	at java.io.FileInputStream.<init>(FileInputStream.java:104)
	at sun.tools.jar.Main.run(Main.java:319)
	at sun.tools.jar.Main.main(Main.java:1300)
Finished extracting liberty feature cache to /home/default/artifacts
Liberty feature cache is not set up
mkdir: cannot create directory '/home/default/app/mc-target': Permission denied
touch: cannot touch '/home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log': No such file or directory
tail: cannot open '/home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log' for reading: No such file or directory
tail: no files remaining
```

**Comment by maysunfaisal** [comment]
Its also worth noting that we dont see this issue on Win? Because Win Functional tests have been passing.

**Comment by ssh24** [comment]
Interesting. Does Window Liberty have a different source path?

**Comment by ssh24** [comment]
Liberty project is now building fine after #694 went in. Looks like that was the issue.

**Comment by rajivnathan** [comment]
Can this be closed now?

**Comment by maysunfaisal** [comment]
Dont know if you want to keep this open for build issues seen in https://github.com/eclipse/codewind/issues/689#issuecomment-543754342

**Comment by ssh24** [comment]
Closing this as both manual and automated tests have verfied this issue is fixed.

![Screen Shot 2019-10-18 at 2 11 51 PM](https://user-images.githubusercontent.com/15173354/67118592-2bee7a80-f1b3-11e9-9593-2a7fab6653ab.png)
