### ISSUE TITLE
PR builds failing on deployment registry test

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#699]
**Description:**
All current PRs are blocked because the PR build is failing on the portal test.
Example: https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/PR-696/1/console

```
12:03:20    32 passing (50s)
12:03:20    12 pending
12:03:20    2 failing
12:03:20  
12:03:20    1) Deployment Registry route tests
12:03:20         "before all" hook: Create a backup of any existing ${workspace_location}/.config/settings.json file and set the watch status in "Deployment Registry route tests":
12:03:20  
12:03:20        AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 404
12:03:20  (res.text: 'Unable to find project undefined')
12:03:20        + expected - actual
12:03:20  
12:03:20        -404
12:03:20        +200
12:03:20        
12:03:20        at verifyResStatus (modules/request.service.js:54:21)
12:03:20        at makeReq (modules/request.service.js:29:26)
12:03:20        at process._tickCallback (internal/process/next_tick.js:68:7)
12:03:20  
12:03:20    2) Template API tests
12:03:20         GET /api/v1/templates
12:03:20           ?showEnabledOnly=
12:03:20             true
12:03:20               should return only templates from enabled repos:
12:03:20  
12:03:20        AssertionError: expected 18 to equal 17
12:03:20        + expected - actual
12:03:20  
12:03:20        -18
12:03:20        +17
12:03:20        
12:03:20        at Context.<anonymous> (src/API/templates/templates.test.js:101:44)
12:03:20        at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by maysunfaisal** [comment]
With my PR https://github.com/eclipse/codewind/pull/700

I dont see the deployment registry issue anymore

but see the second error of TEmplate API Test

```
1) Template API tests
13:26:08         GET /api/v1/templates
13:26:08           ?showEnabledOnly=
13:26:08             true
13:26:08               should return only templates from enabled repos:
13:26:08  
13:26:08        AssertionError: expected 18 to equal 17
13:26:08        + expected - actual
13:26:08  
13:26:08        -18
13:26:08        +17
13:26:08        
13:26:08        at Context.<anonymous> (src/API/templates/templates.test.js:101:44)
13:26:08        at process._tickCallback (internal/process/next_tick.js:68:7)
````

and also these

```
13:25:30  /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-700/test/src/integration/lifecycle.test.js
13:25:30     15:7   warning  A space is required after '{'                     object-curly-spacing
13:25:30     15:17  warning  A space is required before '}'                    object-curly-spacing
13:25:30     16:7   error    'execAsync' is assigned a value but never used    no-unused-vars
13:25:30     95:25  warning  Unexpected use of undefined                       no-undefined
13:25:30    264:64  error    'appEndpoint' is assigned a value but never used  no-unused-vars
13:25:30    298:58  warning  Operator '*' must be spaced                       space-infix-ops
13:25:30    309:95  warning  A space is required before '}'                    object-curly-spacing
13:25:30    416:17  warning  Expected space(s) after "if"                      keyword-spacing
13:25:30    461:49  warning  Operator '*' must be spaced                       space-infix-ops
13:25:30  
13:25:30  /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-700/test/src/unit/projectInitializer.test.js
13:25:30    16:7   error    'fs' is assigned a value but never used   no-unused-vars
13:25:30    72:23  warning  Async function has no 'await' expression  require-await
13:25:30  
13:25:30  ✖ 16 problems (3 errors, 13 warnings)
```

So its not specifically deployment registry test failure

**Comment by ssh24** [comment]
The test is probably related to https://github.com/eclipse/codewind/issues/704

**Comment by maysunfaisal** [comment]
Ignore my comment related to PR 700 that was for 0.5.0 branch

But my PR https://github.com/eclipse/codewind/pull/701 fixes the second failing test about the template. Had a brief look at the deployment registry test, needs to be debugged.

**Comment by jcockbain** [comment]
@ssh24 has this been resolved? That template test is passing on master, and the /registry route doesn't seem to be being used anymore.

**Comment by ssh24** [comment]
Looks like the tests are not broken anymore. Closing.
