### ISSUE TITLE
Codewind does not work on Eclipse Che (ICP) instance after trying to get the latest version

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#71]
**Environment:**
- **Codewind version:** [Latest](https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/latest/devfile.yaml)
- **ICP version:** 3.2.0
- **OS:** macOS Mojave (10.14.5) 

**Description:**
Codewind does not work on Eclipse Che (ICP) instance after trying to get the latest version.

<img width="1680" alt="Screen Shot 2019-07-31 at 10 21 21 AM" src="https://user-images.githubusercontent.com/49531960/62225606-c2ff1f80-b386-11e9-8a08-23b83e2554c2.png">

<img width="710" alt="Screen Shot 2019-07-31 at 2 28 51 PM" src="https://user-images.githubusercontent.com/49531960/62299729-79c0d580-b443-11e9-9cfd-124b971f424f.png">

@jagraj

**Comment by jagraj** [comment]
Looks like Tekton integration is delivered in latest builds and we can not see palette in eclipse che workspace. Here is the error we are seeing in the logs and it is complaining about RBAC for tekton-pipelines namespace.

```[01/08/19 17:11:46 /portal/routes/environment.route.js] [ERROR] { Error: ingresses.extensions is forbidden: User "system:serviceaccount:eclipse-che:che-workspace" cannot list ingresses.extensions in the namespace "tekton-pipelines": no RBAC policy matched
    at _request (/portal/node_modules/kubernetes-client/lib/backends/request.js:189:25)
    at Request.request [as _callback] (/portal/node_modules/kubernetes-client/lib/backends/request.js:148:14)
    at Request.self.callback (/portal/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/portal/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/portal/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12) code: 403, statusCode: 403 }
[01/08/19 17:11:47 /portal/routes/environment.route.js] [ERROR] { Error: ingresses.extensions is forbidden: User "system:serviceaccount:eclipse-che:che-workspace" cannot list ingresses.extensions in the namespace "tekton-pipelines": no RBAC policy matched
    at _request (/portal/node_modules/kubernetes-client/lib/backends/request.js:189:25)
    at Request.request [as _callback] (/portal/node_modules/kubernetes-client/lib/backends/request.js:148:14)
    at Request.self.callback (/portal/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/portal/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/portal/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)```

**Comment by rajivnathan** [comment]
@sujeilyfonseca @jagraj When I merged John's PR this issue was automatically closed. Please reopen if you find you're still seeing the issue.
