### ISSUE TITLE
[Iterative Dev] Kube Functional Test Registry API Error

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#742]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
```
  0 passing (20s)
  1 failing

  1) PFE - functional test
       "before all" hook: set deployment registry:

      Uncaught AssertionError: expected 500 to equal 200
      + expected - actual

      -500
      +200
      
      at Request.utils.getRegistry [as _callback] (test/functional-test/functional.test.ts:64:40)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Steps to reproduce:**

**Workaround:**

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/666

**Comment by ssh24** [comment]
This can now be closed.
