### ISSUE TITLE
Bind failing (remote architecture)

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#807]
**Codewind version:** latest
**OS:** macos

I'm calling cwctl to bind an existing project, but it's panicking
```
% ./cwctl project bind -name gogo -type docker -language go -path /Users/jsp/codewind-workspace/gogo
panic: invalid character 'N' looking for beginning of value

goroutine 1 [running]:
github.com/eclipse/codewind-installer/utils/project.Bind(0x7ffeefbffa30, 0x22, 0x7ffeefbffa0b, 0x4, 0x7ffeefbffa27, 0x2, 0x7ffeefbffa16, 0x6, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/utils/project/bind.go:99 +0xb5d
github.com/eclipse/codewind-installer/utils/project.BindProject(0xc0000dadc0, 0x1bbce40)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/utils/project/bind.go:54 +0x1ac
github.com/eclipse/codewind-installer/actions.ProjectBind(0xc0000dadc0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/actions/project.go:47 +0x2f
github.com/eclipse/codewind-installer/actions.Commands.func2(0xc0000dadc0, 0x0, 0xc000101dc0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/actions/commands.go:81 +0x2b
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.HandleAction(0x15bda80, 0x16cadd8, 0xc0000dadc0, 0xc0000dadc0, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:514 +0xbe
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.Run(0x16a9004, 0x4, 0x0, 0x0, 0xc0002ce010, 0x1, 0x1, 0x16c3696, 0x3b, 0x0, ...)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:171 +0x4a4
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc0002c6380, 0xc0000dab00, 0x0, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:395 +0x877
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.startApp(0x16aa077, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16b2987, 0x18, 0x0, ...)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:383 +0x808
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.Run(0x16aa077, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16b2987, 0x18, 0x0, ...)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:103 +0x8ef
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.(*App).Run(0xc0002c61c0, 0xc00001c0b0, 0xb, 0xb, 0x0, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:265 +0x70b
github.com/eclipse/codewind-installer/actions.Commands()
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/actions/commands.go:573 +0x4ead
main.main()
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/main.go:21 +0x27
```

I believe the `N` in ` invalid character 'N'` is the `N` from  `Not Found` in a 404 response, because when I try to bind in Eclipse, which is still calling the REST api, I get a `404 Not Found` response.

1. cwctl should handle a 404 response
2. PFE bind should be fixed

**Comment by stalleyj** [comment]
This problem has already been fixed, you should see output below when the path doesn't exist.

cwctl project bind -name gogo -type docker -language go -path /Users/jsp/codewind-workspace/gogo
{"error":"proj_path","error_description":"stat /Users/jsp/codewind-workspace/gogo: no such file or directory"}

**Comment by stalleyj** [comment]
So this isn't the path issue but a 404 return from a PFE route. Need to handle this gracefully and figure out why it's occurring.

**Comment by stalleyj** [comment]
I've added error handling to bind so we should get a sensible message back if either PFE isn't running or the API that cwctl calls isn't present.

**Comment by jopit** [comment]
When I now run with the latest cwct, I get the following:
```
% ./cwctl project bind -name gogo -type docker -language go -path /Users/jsp/codewind-workspace/gogo
{"error":"proj_response","error_description":"unable to find requested resource on Codewind server"}
```
which is better than a panic.  But I still don't know why the call is failing.  Am I doing something wrong or is there a bug in PFE?

**Comment by jopit** [comment]
If I start pfe using `./run.sh`, bind works.  If I shut down the containers, delete the codewind docker volume, and start pfe using `./cwctl start -t latest`, bind fails even though it's using the images created by run.sh.

So the run.sh script itself must be doing something different from cwctl when it starts the containers.

**Comment by tobespc** [comment]
this should now be fixed by the change Julie put in

**Comment by jopit** [comment]
It's now working, thanks.
