### ISSUE TITLE
Turbine Local Functional Tests Failing [Hybrid architecture]

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#816]
**Codewind version:** latest (22-10-2019)
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
Turbine local func tessts are failing after hybrid architecture has been made default in the repo.

Logs at 
[local-functional-test.log](https://github.com/eclipse/codewind/files/3763020/local-functional-test.log)

**Steps to reproduce:**
Run the local turbine functional test

**Workaround:**

**Comment by ssh24** [comment]
@rajivnathan I am looking into this. Could you please assign this to me?

**Comment by maysunfaisal** [comment]
```
  1) PFE - functional test
       Project Specific Suite: go
         create test
           create project:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at waitForCreationEvent (test/functional-test/suites/project/tests/create.ts:112:61)

  2) PFE - functional test
       Project Specific Suite: go
         project test
           getProjectLogs function
             get project logs with valid id:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:54:40)

  3) PFE - functional test
       Project Specific Suite: go
         project test
           checkNewLogFile function
             checking for new build log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  4) PFE - functional test
       Project Specific Suite: go
         project test
           checkNewLogFile function
             checking for new app log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  5) PFE - functional test
       Project Specific Suite: lagom
         create test
           create project:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at waitForCreationEvent (test/functional-test/suites/project/tests/create.ts:112:61)

  6) PFE - functional test
       Project Specific Suite: lagom
         project test
           getProjectLogs function
             get project logs with valid id:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:54:40)

  7) PFE - functional test
       Project Specific Suite: lagom
         project test
           checkNewLogFile function
             checking for new build log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  8) PFE - functional test
       Project Specific Suite: lagom
         project test
           checkNewLogFile function
             checking for new app log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  9) PFE - functional test
       Project Specific Suite: python
         create test
           create project:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at waitForCreationEvent (test/functional-test/suites/project/tests/create.ts:112:61)

  10) PFE - functional test
       Project Specific Suite: python
         project test
           getProjectLogs function
             get project logs with valid id:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:54:40)

  11) PFE - functional test
       Project Specific Suite: python
         project test
           checkNewLogFile function
             checking for new build log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  12) PFE - functional test
       Project Specific Suite: python
         project test
           checkNewLogFile function
             checking for new app log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  13) PFE - functional test
       Project Specific Suite: liberty
         create test
           create project:

      AssertionError: expected 'failed' to equal 'success'
      + expected - actual

      -failed
      +success
      
      at waitForCreationEvent (test/functional-test/suites/project/tests/create.ts:102:54)

  14) PFE - functional test
       Project Specific Suite: liberty
         project test
           projectAction function
             configure project action build
               set project action to build:
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  15) PFE - functional test
       Project Specific Suite: liberty
         project test
           projectAction function
             configure project action restart
               set project action to restart with mode run:
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  16) PFE - functional test
       Project Specific Suite: liberty
         project test
           projectAction function
             configure project action restart
               "after all" hook: after hook: undefined settings test for "set project action to restart with mode run":
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  17) PFE - functional test
       Project Specific Suite: liberty
         project test
           projectAction function
             configure project action restart
               "after all" hook: after hook: undefined settings test for "set project action to restart with mode debug":
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  18) PFE - functional test
       Project Specific Suite: liberty
         project test
           projectAction function
             "after all" hook: set app status to running for "set project action with undefined action type":
     Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  19) PFE - functional test
       Project Specific Suite: liberty
         project test
           updateProjectForNewChange function
             update file with type = modify
               modify file: Dockerfile:
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  20) PFE - functional test
       Project Specific Suite: liberty
         project test
           updateProjectForNewChange function
             update file with type = modify
               modify file: src/main/java/application/rest/v1/Example.java:
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  21) PFE - functional test
       Project Specific Suite: liberty
         project test
           updateProjectForNewChange function
             update file with type = create
               create file: file1:
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  22) PFE - functional test
       Project Specific Suite: liberty
         project test
           getProjectLogs function
             get project logs with valid id:
     AssertionError: expected [ Array(2) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:54:40)

  23) PFE - functional test
       Project Specific Suite: liberty
         project test
           checkNewLogFile function
             checking for new build log file:
     AssertionError: expected [ Array(2) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  24) PFE - functional test
       Project Specific Suite: liberty
         project test
           checkNewLogFile function
             checking for new app log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  25) PFE - functional test
       Project Specific Suite: liberty
         project test
           projectSpecification function
             configure project specifications
               configure internalPort settings
                 "after all" hook: after hook: internalPort settings test | Internal Port Test After Hook: Reset internal port for "config project specification settings internalPort":
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  26) PFE - functional test
       Project Specific Suite: liberty
         project test
           projectSpecification function
             configure project specifications
               configure internalDebugPort settings
                 "after all" hook: after hook: internalDebugPort settings test | Internal debug port test - After hook - Reset internal debug port for "config project specification settings internalDebugPort":
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  27) PFE - functional test
       Project Specific Suite: liberty
         project test
           projectSpecification function
             "after all" hook: restart project liberty for "set project specification with numeric mavenProperties array":
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  28) PFE - functional test
       Project Specific Suite: liberty
         project test
           updateStatus function
             application status update
               "after all" hook: restart project liberty for "update application status to started state":
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  29) PFE - functional test
       Project Specific Suite: liberty
         project test
           updateStatus function
             build status update
               "after all" hook: restart project liberty for "update build status to failed state":
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/file-watcher/server/test/functional-test/functional.test.ts)
  

  30) PFE - functional test
       Project Specific Suite: nodejs
         create test
           create project:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at waitForCreationEvent (test/functional-test/suites/project/tests/create.ts:112:61)

  31) PFE - functional test
       Project Specific Suite: nodejs
         project test
           getProjectLogs function
             get project logs with valid id:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:54:40)

  32) PFE - functional test
       Project Specific Suite: nodejs
         project test
           checkNewLogFile function
             checking for new build log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  33) PFE - functional test
       Project Specific Suite: nodejs
         project test
           checkNewLogFile function
             checking for new app log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  34) PFE - functional test
       Project Specific Suite: spring
         create test
           create project:
     AssertionError: expected [ Array(2) ] to have own property 'origin'
      at waitForCreationEvent (test/functional-test/suites/project/tests/create.ts:112:61)

  35) PFE - functional test
       Project Specific Suite: spring
         project test
           getProjectLogs function
             get project logs with valid id:
     AssertionError: expected [ Array(2) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:54:40)

  36) PFE - functional test
       Project Specific Suite: spring
         project test
           checkNewLogFile function
             checking for new build log file:
     AssertionError: expected [ Array(2) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  37) PFE - functional test
       Project Specific Suite: spring
         project test
           checkNewLogFile function
             checking for new app log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  38) PFE - functional test
       Project Specific Suite: swift
         create test
           create project:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at waitForCreationEvent (test/functional-test/suites/project/tests/create.ts:112:61)

  39) PFE - functional test
       Project Specific Suite: swift
         project test
           getProjectLogs function
             get project logs with valid id:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:54:40)

  40) PFE - functional test
       Project Specific Suite: swift
         project test
           checkNewLogFile function
             checking for new build log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

  41) PFE - functional test
       Project Specific Suite: swift
         project test
           checkNewLogFile function
             checking for new app log file:
     AssertionError: expected [ Array(1) ] to have own property 'origin'
      at Context.it (test/functional-test/suites/project/tests/logs.ts:126:47)

```

Log on Oct 30

**Comment by ssh24** [comment]
@maysunfaisal I am looking into that failure as part of https://github.com/eclipse/codewind/issues/908
