### ISSUE TITLE
[local hybrid] portal error spamming the log

### ISSUE THREAD

**Issue by yangcao77** [eclipse/codewind#832]
**Codewind version:** master
**OS:** mac

**Che version:**
**IDE extension version:** master
**IDE version:**
**Kubernetes cluster:**

**Description:**
Seeing this portal error spamming the log.
looks like portal trying to set header after the res has been sent. 
```
[23/10/19 20:24:05 /portal/routes/projects/remoteBind.route.js] [ERROR] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
    at ServerResponse.contentType (/portal/node_modules/express/lib/response.js:599:15)
    at ServerResponse.sendStatus (/portal/node_modules/express/lib/response.js:357:8)
    at router.post (/portal/routes/projects/remoteBind.route.js:277:11)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/portal/node_modules/express/lib/router/layer.js:95:5)
    at next (/portal/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/portal/node_modules/express/lib/router/route.js:112:3)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
[23/10/19 20:24:05 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'Error [ERR_HTTP_HEADERS_SENT]',
     message: 'Cannot set headers after they are sent to the client' } }
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/portal/node_modules/express/lib/response.js:170:12)
    at handleErrors (/portal/middleware/errorHandler.js:8:26)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/portal/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/portal/node_modules/express/lib/router/index.js:315:13)
    at /portal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
    at next (/portal/node_modules/express/lib/router/index.js:275:10)
[23/10/19 20:24:05 /portal/routes/projects/remoteBind.route.js] [ERROR] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
    at ServerResponse.contentType (/portal/node_modules/express/lib/response.js:599:15)
    at ServerResponse.sendStatus (/portal/node_modules/express/lib/response.js:357:8)
    at router.post (/portal/routes/projects/remoteBind.route.js:277:11)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/portal/node_modules/express/lib/router/layer.js:95:5)
    at next (/portal/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/portal/node_modules/express/lib/router/route.js:112:3)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
[23/10/19 20:24:05 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'Error [ERR_HTTP_HEADERS_SENT]',
     message: 'Cannot set headers after they are sent to the client' } }
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/portal/node_modules/express/lib/response.js:170:12)
    at handleErrors (/portal/middleware/errorHandler.js:8:26)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/portal/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/portal/node_modules/express/lib/router/index.js:315:13)
    at /portal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
    at next (/portal/node_modules/express/lib/router/index.js:275:10)
```

**Steps to reproduce:**

**Workaround:**

**Comment by james-wallis** [comment]
@tobespc assign please

**Comment by yangcao77** [comment]
Verified not seeing this issue any more with the latest master code.
