### ISSUE TITLE
Turbine Functional Test deployment registry error

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#840]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
```
[24/10/19 02:02:35 Turbine] [INFO] Registered listener: PFE Functional Test Listener

  Non-test failures
      1) "before all" hook: set deployment registry

  Suite duration: 0.001 s, Tests: 1

  0 passing (20s)
  1 failing

  1) PFE - functional test
       "before all" hook: set deployment registry:

      Uncaught AssertionError: expected 500 to equal 200
      + expected - actual

      -500
      +200
      
      at Request.utils.getRegistry [as _callback] (test/functional-test/functional.test.ts:64:40)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at endReadableNT (_stream_readable.js:1143:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

seems to be failing with devfile: 
`DEFAULT_DEVFILE="https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/latest/devfile.yaml"`

**Steps to reproduce:**

**Workaround:**

**Comment by maysunfaisal** [comment]
Closing this now as this seems not to be happening
