### ISSUE TITLE
New microprofile project fails to build (remote architecture)

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#864]
**Codewind version:** latest
**OS:** macOS Catalina

In the Eclipse IDE, I created a new `WebSphere Liberty Microprofile®` project.  The initial build failed `[Build failed: Creating image for build failed]`

Here are the pfe logs:
[pfe.txt](https://github.com/eclipse/codewind/files/3772772/pfe.txt)

**Comment by ssh24** [comment]
@jopit Can't see the error with the current log setting. Can you turn on the trace level and send the log again?

To set the trace level exec into the PFE container and run:
```
curl -d '{"level": "trace"}' -H "Content-Type: application/json" -X PUT http://localhost:9090/api/v1/logging -k
```

**Comment by ssh24** [comment]
Actually the error might be because of

```
java.io.FileNotFoundException: /home/default/app/localm2cache.zip (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)

[91m[25/10/19 15:34:28 liberty2] [ERROR][39m executeBuildScript : 393 | 	at java.io.FileInputStream.open(FileInputStream.java:212)

[91m[25/10/19 15:34:28 liberty2] [ERROR][39m executeBuildScript : 393 | 	at java.io.FileInputStream.<init>(FileInputStream.java:152)

[91m[25/10/19 15:34:28 liberty2] [ERROR][39m executeBuildScript : 393 | 	at java.io.FileInputStream.<init>(FileInputStream.java:104)

[91m[25/10/19 15:34:28 liberty2] [ERROR][39m executeBuildScript : 393 | 	at sun.tools.jar.Main.run(Main.java:319)

[91m[25/10/19 15:34:28 liberty2] [ERROR][39m executeBuildScript : 393 | 	at sun.tools.jar.Main.main(Main.java:1300)
```

**Comment by GeekArthur** [comment]
The issue shouldn't related with `localm2cache.zip`, by design if the cache is not there build will continue from scratch (not use cache). Also the error is `Build failed: Creating image for build failed`, it failed on image build stage. localm2cache.zip is used for maven build not image build

**Comment by maysunfaisal** [comment]
Just built one, I dont see any issue with my Liberty except it was disabled on creation and then went to the other status and eventually, to started

**Comment by jopit** [comment]
Here's the log with the trace level set
[pfe.txt](https://github.com/eclipse/codewind/files/3773197/pfe.txt)

**Comment by rajivnathan** [comment]
Looks like the error is due to the pom.xml missing from `/home/default/app` in the app container. Does the pom.xml exist in your pfe container? @jopit 

```
[34m[25/10/19 17:53:44 liberty2] [TRACE][39m [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

[34m[25/10/19 17:53:44 liberty2] [TRACE][39m [INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.110 s

[34m[25/10/19 17:53:44 liberty2] [TRACE][39m [INFO] Finished at: 2019-10-25T17:53:44Z

[34m[25/10/19 17:53:44 liberty2] [TRACE][39m [INFO] ------------------------------------------------------------------------

[34m[25/10/19 17:53:44 liberty2] [TRACE][39m [ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/default/app). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 

[34m[25/10/19 17:53:44 liberty2] [TRACE][39m [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[34m[25/10/19 17:53:44 liberty2] [TRACE][39m [ERROR] 

[34m[25/10/19 17:53:44 liberty2] [TRACE][39m [ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
```

**Comment by jopit** [comment]
```
% docker exec -ti codewind-pfe /bin/bash
[root@989df3786fab /]# ls -l codewind-workspace/liberty2/
total 220584
-rw-rwxr-- 1 1001 root       607 Oct 25 19:17 Dockerfile
-rw-rwxr-- 1 1001 root      2664 Oct 25 19:17 Dockerfile-build
-rw-rwxr-- 1 1001 root       366 Oct 25 19:17 Dockerfile-tools
-rw-rwxr-- 1 1001 root        97 Oct 25 19:16 Jenkinsfile
-rw-rwxr-- 1 1001 root      2751 Oct 25 19:17 README.md
drwxrwxr-x 3 1001 root      4096 Oct 25 19:16 chart
-rw-rwxr-- 1 1001 root  61314717 Jun 18 20:58 libertyrepocache.zip
-rw-rwxr-- 1 1001 root 164499767 Aug 28 19:56 localm2cache.zip
-rw-rwxr-- 1 1001 root     22844 Oct 25 19:17 pom.xml
drwxrwxr-x 4 1001 root      4096 Oct 25 19:16 src
drwxrwxr-x 3 1001 root      4096 Oct 25 19:16 target
```

**Comment by jopit** [comment]
For the app container
```
% docker exec -ti cw-liberty2-f819dd40-f75b-11e9-86ea-6b79b5cbc49c /bin/bash
default@41f6da2fd8d1:/$ ls -al /home/default/app/
total 4
drwxr-xr-x 3 default root   96 Oct 25 14:16 .
drwxrwxr-x 1 default root 4096 Oct 25 19:17 ..
drwxr-xr-x 3 default root   96 Oct 25 14:16 mc-target
```

**Comment by rajivnathan** [comment]
So it looks like the pom.xml is missing in the app container (where the maven build actually takes place). I believe this is a sync problem. @tobespc Seems to be an issue with syncing to the app container?

**Comment by elsony** [comment]
Changing this to stopship to match the SVT defect #904 that get closed as a dup of this one.

**Comment by stalleyj** [comment]
@jopit This is working fine for me on the latest code, could you retest please.

**Comment by jopit** [comment]
@stalleyj still fails for me.  Using latest eclipse, latest cli, started codewind via eclipse, not via `run.sh`

**Comment by jopit** [comment]
Here's something:  when I use `run.sh` to start the codewind containers, the build succeeds.  When I start the containers using `cwctl start -t latest`, it fails as described above.

Is this maybe another case of `run.sh` still specifying the REMOTE_MODE flag and changing the behaviour of the containers when they are started?

**Comment by jagraj** [comment]
I created open liberty project and I see this in the pfe log. It is not able to copy as part of the docker build.

```
[31/10/19 17:52:07 olcwlatestsvt] [ERROR] containerBuildAndRun : 1442 | | The command /file-watcher/scripts/dockerScripts/docker-build.sh build --label builtBy=codewind -t cw-olcwlatestsvt-1b0f29e0-fc07-11e9-9517-5d162b6abaa9,/codewind-workspace/olcwlatestsvt,/codewind-workspace/.logs/olcwlatestsvt-1b0f29e0-fc07-11e9-9517-5d162b6abaa9/docker.build.log,1b0f29e0-fc07-11e9-9517-5d162b6abaa9 failed with exit code 1
[31/10/19 17:52:07 olcwlatestsvt] [ERROR] Build image stage failed for olcwlatestsvt
[31/10/19 17:52:07 olcwlatestsvt] [ERROR] Error output:
Touching container build log file: /codewind-workspace/.logs/olcwlatestsvt-1b0f29e0-fc07-11e9-9517-5d162b6abaa9/docker.build.log
Triggering log file event for: container build log
Running docker container build command: docker build --label builtBy=codewind -t cw-olcwlatestsvt-1b0f29e0-fc07-11e9-9517-5d162b6abaa9 /codewind-workspace/olcwlatestsvt |& tee /codewind-workspace/.logs/olcwlatestsvt-1b0f29e0-fc07-11e9-9517-5d162b6abaa9/docker.build.log
OKSending build context to Docker daemon  569.9kB
Step 1/14 : FROM maven:3.5.4-jdk-8-alpine AS builder
 ---> fb4bb0d89941
Step 2/14 : COPY pom.xml .
 ---> Using cache
 ---> 48c5cbf2e795
Step 3/14 : COPY src src/
COPY failed: stat /var/lib/docker/tmp/docker-builder116849972/src: no such file or directory

[31/10/19 17:52:07 olcwlatestsvt] [INFO] Build state changed for project: 1b0f29e0-fc07-11e9-9517-5d162b6abaa9 from: inProgress, to: failed, with message: buildscripts.buildFail
```

**Comment by jopit** [comment]
@jagraj I'm not seeing those particular errors in my scenario, that may be a separate problem.

**Comment by jopit** [comment]
@stalleyj I'm guessing this is the root cause
https://github.com/eclipse/codewind/blob/7e2c88aadc6e2ece6223afb69f49a90764730227/src/pfe/portal/routes/projects/fileChanges.route.js#L78
but I don't know why blindly returning status 200 would fix the problem.  @tobespc could probably explain.

**Comment by jopit** [comment]
I verified that this now works with the latest code
