### ISSUE TITLE
[Remote] Local Project Update Fails

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#867]
**Codewind version:** Latest Oct 25
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:** Latest Oct 25
**Kubernetes cluster:**

**Description:**
Cannot update a Liberty proejct:

```
[25/10/19 17:18:34 /portal/routes/projects/fileChanges.route.js] [INFO] Watch status for projectID 121ead30-f5ca-11e9-a8dd-4522d78bd958: success
[25/10/19 17:18:34 pppp] [INFO] Extension absolute path is: undefined
[25/10/19 17:18:34 Turbine] [INFO] Fetching logs for project 121ead30-f5ca-11e9-a8dd-4522d78bd958
[25/10/19 17:18:34 Turbine] [INFO] Fetching logs for project 171300c0-f74b-11e9-b953-15c18527dfa3
[25/10/19 17:18:34 pppp] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/pppp-121ead30-f5ca-11e9-a8dd-4522d78bd958/docker.build.log"]}
[25/10/19 17:18:34 test123] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/test123-171300c0-f74b-11e9-b953-15c18527dfa3/docker.build.log"]}
[25/10/19 17:18:34 pppp] [INFO] applog path:
{"origin":"workspace","files":["/codewind-workspace/.logs/pppp-121ead30-f5ca-11e9-a8dd-4522d78bd958/app.log"]}
[25/10/19 17:18:34 test123] [INFO] applog path:
{"origin":"workspace","files":["/codewind-workspace/.logs/test123-171300c0-f74b-11e9-b953-15c18527dfa3/app.log","/codewind-workspace/test123/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log"]}
[25/10/19 17:18:34 /portal/routes/projects/fileChanges.route.js] [INFO] Watch status for projectID 171300c0-f74b-11e9-b953-15c18527dfa3: success
[25/10/19 17:18:34 /portal/routes/projects/remoteBind.route.js] [INFO] Temporary project directory doesn't exist, not syncing any files
[25/10/19 17:18:35 /portal/routes/projects/remoteBind.route.js] [INFO] Temporary project directory doesn't exist, not syncing any files
[25/10/19 17:19:06 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',
     message: 'request entity too large' } }
[25/10/19 17:19:06 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',
     message: 'request entity too large' } }
[25/10/19 17:19:11 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',
     message: 'request entity too large' } }
[25/10/19 17:19:11 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',
     message: 'request entity too large' } }
[25/10/19 17:19:23 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',
     message: 'request entity too large' } }
[25/10/19 17:19:23 /portal/middleware/errorHandler.js] [ERROR] { error:
```

**Steps to reproduce:**
update a java file

**Workaround:**

**Comment by maysunfaisal** [comment]
Was able to reproduce it twice. Think this is stop ship as well. Dont know if it regressed this week.

**Comment by maysunfaisal** [comment]
Could be the related change - https://github.com/eclipse/codewind/pull/837/files

**Comment by stalleyj** [comment]
This should be fixed, will test.

**Comment by stalleyj** [comment]
@maysunfaisal Can you please retest on the latest code as this all seems to be working here.

**Comment by maysunfaisal** [comment]
Still seems an issue, I see multiple things happening:

1. Before project is started:
```
[28/10/19 21:51:04 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src/test/java/it/HealthEndpointIT.java projectRoot is /home/default/app
[28/10/19 21:51:04 FileWatcher.js] [ERROR] Error: project update 400 Bad request. projectID, timestamp, chunk, chunk_total and eventArray are required.
    at FileWatcher.projectFileChanged (/portal/modules/FileWatcher.js:395:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:85) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/liibbbb/src/main/java/application/HealthEndpoint.java undefined:/home/default/app/src/main/java/application/HealthEndpoint.java
Error: No such container:path: undefined:/home/default/app/src/main/java/application

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:85) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:85) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:85) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/liibbbb/chart/javamicroprofiletemplate/values.yaml undefined:/home/default/app/chart/javamicroprofiletemplate/values.yaml
Error: No such container:path: undefined:/home/default/app/chart/javamicroprofiletemplate

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:85) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:85) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/liibbbb/chart/javamicroprofiletemplate/templates/service.yaml undefined:/home/default/app/chart/javamicroprofiletemplate/templates/service.yaml
Error: No such container:path: undefined:/home/default/app/chart/javamicroprofiletemplate/templates
```
```
[28/10/19 21:51:08 /portal/routes/projects/remoteBind.route.js] [ERROR] { Error: Command failed: cp -R /codewind-workspace/cw-temp/liibbbb /codewind-workspace/
cp: cannot stat '/codewind-workspace/cw-temp/liibbbb': No such file or directory

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'cp -R /codewind-workspace/cw-temp/liibbbb /codewind-workspace/',
  stdout: '',
  stderr:
   'cp: cannot stat \'/codewind-workspace/cw-temp/liibbbb\': No such file or directory\n' }
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
[28/10/19 21:51:08 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'Error [ERR_HTTP_HEADERS_SENT]',
     message: 'Cannot set headers after they are sent to the client' } }
    at ServerResponse.send (/portal/node_modules/express/lib/response.js:170:12)
    at handleErrors (/portal/middleware/errorHandler.js:8:26)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/portal/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/portal/node_modules/express/lib/router/index.js:315:13)
    at /portal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
    at next (/portal/node_modules/express/lib/router/index.js:275:10)
[28/10/19 21:51:22 liibbbb] [INFO] pingInTransitApplications: Application state error message: Http request is failed due to timeout error
[28/10/19 21:51:23 User.js] [INFO] Check for new log files for project e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80
[28/10/19 21:51:23 FileWatcher.js] [INFO] Check for new app log files for project e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80
[28/10/19 21:51:23 liibbbb] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/liibbbb-e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80/docker.build.log"]}
[28/10/19 21:51:23 liibbbb] [INFO] applog path:
{"origin":"workspace","files":["/codewind-workspace/liibbbb/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log"]}
[28/10/19 21:51:23 liibbbb] [INFO] The container was started successfully for application /codewind-workspace/liibbbb
[28/10/19 21:51:23 liibbbb] [INFO] Looking up container information for cw-liibbbb-e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80
[28/10/19 21:51:23 liibbbb] [INFO] Internal port: 9080
[28/10/19 21:51:23 liibbbb] [INFO] Exposed port: 32775
[28/10/19 21:51:23 liibbbb] [INFO] Internal debug port: 
[28/10/19 21:51:23 liibbbb] [INFO] Exposed debug port: 
[28/10/19 21:51:23 liibbbb] [INFO] All the exposed container ports: ["7777","9080","9443"]
[28/10/19 21:51:23 liibbbb] [INFO] All the host ports: ["32771","32775","32774"]
[28/10/19 21:51:23 liibbbb] [INFO] Found container information: {"containerId":"d7abcfc081515366f7ae18d3ffa601b05d9f9df6ce87630272b49870e99f3079","ip":"172.21.0.4","serviceName":"","exposedPort":"32775","internalPort":"9080","exposedDebugPort":"","internalDebugPort":"","containerPorts":["7777","9080","9443"],"hostPorts":["32771","32775","32774"]}
[28/10/19 21:51:23 liibbbb] [INFO] buildlog path:
 {"origin":"workspace","files":["/codewind-workspace/.logs/liibbbb-e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80/docker.build.log"]}
[28/10/19 21:51:23 liibbbb] [INFO] applog path:
{"origin":"workspace","files":["/codewind-workspace/.logs/liibbbb-e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80/app.log","/codewind-workspace/liibbbb/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log"]}
[28/10/19 21:51:23 liibbbb] [INFO] Emitted event: projectCreation
{"operationId":"e9b60de0a4d93f7c5c0871ea3549b74a","projectID":"e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80","ignoredPaths":["/.project","/Dockerfile-tools","/target","/mc-target","/cli-config.yml","/README.md","/Jenkinsfile","/.cfignore","/load-test*","*/node_modules*","*/.git/*","*/.DS_Store","*/*.swp","*/*.swx","*/4913","*/.dockerignore","*/.gitignore","*/*~","/.settings","/localm2cache.zip","/libertyrepocache.zip","/chart"],"isHttps":false,"status":"success","host":"172.21.0.4","ports":{"exposedPort":"32775","internalPort":"9080","internalDebugPort":"7777"},"containerId":"d7abcfc081515366f7ae18d3ffa601b05d9f9df6ce87630272b49870e99f3079","logs":{"build":{"origin":"workspace","files":["/codewind-workspace/.logs/liibbbb-e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80/docker.build.log"]},"app":{"origin":"workspace","files":["/codewind-workspace/.logs/liibbbb-e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80/app.log","/codewind-workspace/liibbbb/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log"]}}}
[28/10/19 21:51:23 User.js] [INFO] Check for new log files for project e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80
[28/10/19 21:51:23 FileWatcher.js] [INFO] Check for new app log files for project e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80
[28/10/19 21:51:23 liibbbb] [INFO] Emitting event 
 message: projectCreation
 data: {
  "operationId": "e9b60de0a4d93f7c5c0871ea3549b74a",
  "projectID": "e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80",
  "ignoredPaths": [
    "/.project",
    "/Dockerfile-tools",
    "/target",
    "/mc-target",
    "/cli-config.yml",
    "/README.md",
    "/Jenkinsfile",
    "/.cfignore",
    "/load-test*",
    "*/node_modules*",
    "*/.git/*",
    "*/.DS_Store",
    "*/*.swp",
    "*/*.swx",
    "*/4913",
    "*/.dockerignore",
    "*/.gitignore",
    "*/*~",
    "/.settings",
    "/localm2cache.zip",
    "/libertyrepocache.zip",
    "/chart"
  ],
  "isHttps": false,
  "status": "success",
  "host": "172.21.0.4",
  "ports": {
    "exposedPort": "32775",
    "internalPort": "9080",
    "internalDebugPort": "7777"
  },
  "containerId": "d7abcfc081515366f7ae18d3ffa601b05d9f9df6ce87630272b49870e99f3079",
  "logs": {
    "build": {
      "origin": "workspace",
      "files": [
        "/codewind-workspace/.logs/liibbbb-e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80/docker.build.log"
      ]
    },
    "app": {
      "origin": "workspace",
      "files": [
        "/codewind-workspace/.logs/liibbbb-e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80/app.log",
        "/codewind-workspace/liibbbb/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log"
      ]
    }
  }
}
```

2. On File update:
```
[28/10/19 21:52:23 /portal/routes/projects/remoteBind.route.js] [INFO] Temporary project directory doesn't exist, not syncing any files
[28/10/19 21:52:40 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',
     message: 'request entity too large' } }
[28/10/19 21:52:41 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',
     message: 'request entity too large' } }
[28/10/19 21:52:46 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',
     message: 'request entity too large' } }
[28/10/19 21:52:46 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',
     message: 'request entity too large' } }
```
```
[28/10/19 21:53:30 /portal/routes/projects/remoteBind.route.js] [INFO] Removing locally deleted files from project: liibbbb, ID: e2b52e00-f9cc-11e9-ae8e-cd4d755b4c80 - 
[28/10/19 21:53:30 /portal/routes/projects/remoteBind.route.js] [ERROR] { Error: Command failed: cp -R /codewind-workspace/cw-temp/liibbbb /codewind-workspace/
cp: cannot stat '/codewind-workspace/cw-temp/liibbbb/target/liberty/wlp/lib/features/l10n/com.ibm.websphere.appserver.jsp-2.3_pt_BR.properties': No such file or directory
cp: cannot stat '/codewind-workspace/cw-temp/liibbbb/target/liberty/wlp/lib/features/l10n/com.ibm.websphere.appserver.jsonp-1.0_ko.properties': No such file or directory
cp: cannot stat '/codewind-workspace/cw-temp/liibbbb/target/liberty/wlp/lib/features/l10n/com.ibm.websphere.appserver.restConnector-1.0_hu.properties': No such file or directory
cp: cannot stat '/codewind-workspace/cw-temp/liibbbb/target/liberty/wlp/lib/features/l10n/com.ibm.websphere.appserver.bluemixUtility-1.0_pt_BR.properties': No such file or directory
cp: cannot stat '/codewind-workspace/cw-temp/liibbbb/target/liberty/wlp/lib/features/l10n/com.ibm.websphere.appserver.ldapRegistry-3.0_ro.properties': No such file or directory
cp: cannot stat '/codewind-workspace/cw-temp/liibbbb/target/liberty/wlp/lib/features/l10n/com.ibm.websphere.appserver.jdbc-4.1_zh_TW.properties': No such file or directory
cp: cannot stat '/codewind-workspace/cw-temp/liibbbb/target/liberty/wlp/lib/features/l10n/com.ibm.websphere.appserver.mpRestClient-1.0_zh.properties': No such file or directory

```
```
[28/10/19 21:53:30 /portal/routes/projects/remoteBind.route.js] [ERROR] { Error: Command failed: rm -fr /codewind-workspace/cw-temp/liibbbb
rm: cannot remove '/codewind-workspace/cw-temp/liibbbb': Directory not empty

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'rm -fr /codewind-workspace/cw-temp/liibbbb',
  stdout: '',
  stderr:
   'rm: cannot remove \'/codewind-workspace/cw-temp/liibbbb\': Directory not empty\n' }
[28/10/19 21:53:30 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'Error [ERR_HTTP_HEADERS_SENT]',
     message: 'Cannot set headers after they are sent to the client' } }
[28/10/19 21:53:30 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'Error [ERR_HTTP_HEADERS_SENT]',
     message: 'Cannot set headers after they are sent to the client' } }
[28/10/19 21:53:33 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',
     message: 'request entity too large' } }
[28/10/19 21:53:33 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',
     message: 'request entity too large' } }
[28/10/19 21:53:38 /portal/middleware/errorHandler.js] [ERROR] { error:
   { name: 'PayloadTooLargeError',

```

and some more stuff

I think Portal should not sync the target dir, not sure if that is what is causing the sync faillure. There should be some sort of ignoredFiles list like what Codewind local currently has?

**Comment by stalleyj** [comment]
@maysunfaisal Correct, the target dir should not be being updated and the fact that it is indicates you don't have an up to date cli.

**Comment by stalleyj** [comment]
@maysunfaisal We do only sync the updated files from user disk to the volume.  We then also sync to the build container and it looks like the logic isn't quite right so we will investigate.

**Comment by rajivnathan** [comment]
Update still doesn't work for me on local using the latest PFE and vscode extension as of this comment. I've tried microprofile and nodejs and both don't work. Not sure what's different between my environment and Maysun's.

**Comment by rajivnathan** [comment]
Appeared to be a problem with the vscode extension update but project update on local is now working for me.

**Comment by tobespc** [comment]
ok, closing this issue as local update is now fixed.  Will investigate the delta change separately
