### ISSUE TITLE
[Remote] Not able to get microprofile project's console log and message log

### ISSUE THREAD

**Issue by yangcao77** [eclipse/codewind#963]
**Codewind version:** master
**OS:** MacOS

**Che version:** 7.2.0
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** OKD

**Description:**
Unable to get microprofile project's console log and message log on che. 
![image](https://user-images.githubusercontent.com/22285490/68152497-c66bef00-ff11-11e9-8c03-bebe95094f6b.png)
![image](https://user-images.githubusercontent.com/22285490/68152502-cb30a300-ff11-11e9-9fdc-3536aa6064b7.png)

Also see this error when I click "Show all logs"
![image](https://user-images.githubusercontent.com/22285490/68152534-dbe11900-ff11-11e9-98f7-cee37065bd70.png)

```
[04/11/19 19:49:50 libertytest123] [INFO] Looking for all log files in container cw-libertytest123-f3747d60-ff38-11e9-a564
[04/11/19 19:49:51 libertytest123] [INFO] Running kube command: kubectl exec,-i,cw-libertytest123-f3747d60-ff38-11e9-a564-75d9c96d7d-t9trq,--,sh,-c,ls --full-time /home/default/logs | tail -n +2
[04/11/19 19:49:51 Turbine] [INFO] At least one file was found
[04/11/19 19:49:51 libertytest123] [INFO] buildlog path:
 [{"origin":"workspace","files":["/codewind-workspace/.logs/libertytest123-f3747d60-ff38-11e9-a564-ab4923f52fb9/docker.build.log"]}]
[04/11/19 19:49:51 libertytest123] [INFO] Looking for all log files in container cw-libertytest123-f3747d60-ff38-11e9-a564
[04/11/19 19:49:51 libertytest123] [INFO] Running kube command: kubectl exec,-i,cw-libertytest123-f3747d60-ff38-11e9-a564-75d9c96d7d-t9trq,--,sh,-c,ls --full-time /home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs | tail -n +2
[04/11/19 19:49:51 libertytest123] [INFO] Looking for all log files in container cw-libertytest123-f3747d60-ff38-11e9-a564
[04/11/19 19:49:51 libertytest123] [INFO] Running kube command: kubectl exec,-i,cw-libertytest123-f3747d60-ff38-11e9-a564-75d9c96d7d-t9trq,--,sh,-c,ls --full-time /home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs | tail -n +2
[04/11/19 19:49:51 libertytest123] [INFO] Looking for all log files in container cw-libertytest123-f3747d60-ff38-11e9-a564
[04/11/19 19:49:51 libertytest123] [INFO] Running kube command: kubectl exec,-i,cw-libertytest123-f3747d60-ff38-11e9-a564-75d9c96d7d-t9trq,--,sh,-c,ls --full-time /home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs | tail -n +2
[04/11/19 19:49:52 libertytest123] [INFO] applog path:
[{"origin":"workspace","files":["/codewind-workspace/.logs/libertytest123-f3747d60-ff38-11e9-a564-ab4923f52fb9/app.log"]},{"origin":"container","files":["/home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs/console.log","/home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log"],"podName":"cw-libertytest123-f3747d60-ff38-11e9-a564-75d9c96d7d-t9trq"}]
[04/11/19 19:49:52 /portal/routes/projects/logStream.route.js] [ERROR] TypeError: cwUtils.spawnContainerProcess is not a function
    at ContainerFileLogStream.streamLog (/portal/modules/LogStream.js:239:31)
    at Project.startStreamingLog (/portal/modules/Project.js:536:15)
    at startStreamingAll (/portal/routes/projects/logStream.route.js:60:23)

```

**Steps to reproduce:**
1. create a microprofile project from template on che
2. Right click the project and select "show all logs"

**Workaround:**

**Comment by yangcao77** [comment]
Also not able to get logs for Spring projects. 
Same pfe error:
```
[04/11/19 21:10:30 springtest123] [INFO] buildlog path:
 [{"origin":"container","files":["/root/logs/maven.build.log"],"podName":"cw-springtest123-35582200-ff47-11e9-a564-7c888566-c6rl5"},{"origin":"workspace","files":["/codewind-workspace/.logs/springtest123-35582200-ff47-11e9-a564-ab4923f52fb9/docker.build.log"]}]
[04/11/19 21:10:30 springtest123] [INFO] applog path:
[{"origin":"workspace","files":["/codewind-workspace/.logs/springtest123-35582200-ff47-11e9-a564-ab4923f52fb9/app.log"]}]
[04/11/19 21:10:30 /portal/routes/projects/logStream.route.js] [ERROR] TypeError: cwUtils.spawnContainerProcess is not a function
    at ContainerFileLogStream.streamLog (/portal/modules/LogStream.js:239:31)
    at Project.startStreamingLog (/portal/modules/Project.js:536:15)
    at startStreamingAll (/portal/routes/projects/logStream.route.js:60:23)
```

**Comment by ssh24** [comment]
@yangcao77 Just tried it out and it is working for me. Do you have the latest?

![Screen Shot 2019-11-04 at 4 26 03 PM](https://user-images.githubusercontent.com/15173354/68159492-d985bb80-ff1f-11e9-9f08-0a748bd3033c.png)

**Comment by yangcao77** [comment]
Reinstalled latest che today 2p.m. from `codewind-che-plugin` and codewind master image from `https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/latest/devfile.yaml`

**Comment by ssh24** [comment]
Oh, this was on che. I just tried it out and I am also able to see it as well
```
[04/11/19 22:41:27 /portal/routes/projects/logStream.route.js] [ERROR] TypeError: cwUtils.spawnContainerProcess is not a function
    at ContainerFileLogStream.streamLog (/portal/modules/LogStream.js:239:31)
    at Project.startStreamingLog (/portal/modules/Project.js:536:15)
    at startStreamingAll (/portal/routes/projects/logStream.route.js:60:23)
```

**Comment by hhellyer** [comment]
I've fixed the unimplemented method. The logs will now stream once the container running the app is up and running. There may still be a bug in that the logs appear in the list of possible logs before the container is running and at that point starting streaming them will fail. You need to start streaming the logs once the container is up and the project is running. (This can mean waiting quite a long time for a liberty project to build.)

The list of logs is returned by Turbine so if there is a problem with those logs being listed as available before the container is up and they really are then we will need to look at the Turbine code that returns the log list.

**Comment by yangcao77** [comment]
Verified the issue has been fixed in latest master branch. Closing this issue.
