### ISSUE TITLE
Node project fails to start

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#972]
**Codewind version:** latest
**OS:** macOS Catalina

Using Eclipse plugin codewind-0.5.0-201911041925 I created a nodejs application.  It built but fails to start.

[pfe.txt](https://github.com/eclipse/codewind/files/3806281/pfe.txt)

Grepping the log for errors shows this:
```
% grep ERROR pfe.txt
[04/11/19 21:44:08 Turbine] [ERROR] [File Name: /file-watcher/server/dist/controllers/projectsController.js | Function Name: getProjectInfoFromFile | Line Number: 773] Failed to find project information related to file /file-watcher/fwdata/projects/3ab4de00-ff4c-11e9-a217-8b3cb04e612b/3ab4de00-ff4c-11e9-a217-8b3cb04e612b.json
[04/11/19 21:44:30 node1] [ERROR] executeBuildScript : 393 | + set +x
[04/11/19 21:44:34 FileWatcher.js] [ERROR] Error: project update 400 Bad request. projectID, timestamp, chunk, chunk_total and eventArray are required.
[04/11/19 21:44:42 node1] [ERROR] getContainerStatus : 166 | | The command docker exec,cw-node1-3ab4de00-ff4c-11e9-a217-8b3cb04e612b,/scripts/noderun.sh,isActive failed with exit code 1
```

**Comment by yangcao77** [comment]
I can take a look at this issue. 
One thing I want to mention is that for this error message. It's logged from portal, and I'm seeing this error for all project types on che. Can we have portal team to take a look at this one?
```
[91m[04/11/19 21:44:34 FileWatcher.js] [ERROR][39m Error: project update 400 Bad request. projectID, timestamp, chunk, chunk_total and eventArray are required.
    at FileWatcher.projectFileChanged (/portal/modules/FileWatcher.js:395:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[32m[04/11/19 21:44:35 node1] [INFO][39m Build completed for 3ab4de00-ff4c-11e9-a217-8b3cb04e612b
```

**Comment by yangcao77** [comment]
@jopit Is this always reproducable? I'm build pfe from latest master branch and installed latest vscode plugin. I'm not able to reproduce. 
However, from the log, it does look like there is something wrong with the `noderun.sh`

I have checked our code, only 2 places `exit 1` in `noderun.sh`. It's either nodemon is not running, or there's no node process running.

If you can reproduce it, can you turn on Turbine trace log and attach a full pfe log within this issue?
`PUT`  `http://localhost:<pfe_exposed_port>/api/v1/logging`
```
{
  "level":"trace"
}
```

**Comment by jopit** [comment]
This is another problem that works if you start PFE using `run.sh` or `start.sh`, but fails if you start it up using `cwctl` or through the IDEs.
