### ISSUE TITLE
[Che] Toggling Logs failed on Che latest

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#976]
**Codewind version:** latest
**OS:**

**Che version:** 7.2.0
**IDE extension version:**latest
**IDE version:**
**Kubernetes cluster:** OKD 3.11

**Description:**
![Screen Shot 2019-11-05 at 11 10 27 AM](https://user-images.githubusercontent.com/31771087/68224636-00de9600-ffbd-11e9-8253-7a7b43a6b13a.png)

```
[05/11/19 16:09:54 /portal/routes/projects/logStream.route.js] [INFO] Stopped streaming logs for 3a8529f0-ffe5-11e9-a7f8-4195111c186e
[05/11/19 16:09:59 Turbine] [INFO] Fetching logs for project 3a8529f0-ffe5-11e9-a7f8-4195111c186e
[05/11/19 16:09:59 tuelib1] [INFO] Looking for all log files in container cw-tuelib1-3a8529f0-ffe5-11e9-a7f8
[05/11/19 16:09:59 tuelib1] [INFO] Running kube command: kubectl exec,-i,cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb,--,sh,-c,ls --full-time /home/default/logs | tail -n +2
[05/11/19 16:09:59 Turbine] [INFO] At least one file was found
[05/11/19 16:09:59 tuelib1] [INFO] buildlog path:
 [{"origin":"container","files":["/home/default/logs/maven.build.log"],"podName":"cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb"},{"origin":"workspace","files":["/codewind-workspace/.logs/tuelib1-3a8529f0-ffe5-11e9-a7f8-4195111c186e/docker.build.log"]}]
[05/11/19 16:09:59 tuelib1] [INFO] Looking for all log files in container cw-tuelib1-3a8529f0-ffe5-11e9-a7f8
[05/11/19 16:09:59 tuelib1] [INFO] Running kube command: kubectl exec,-i,cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb,--,sh,-c,ls --full-time /home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs | tail -n +2
[05/11/19 16:09:59 tuelib1] [INFO] Looking for all log files in container cw-tuelib1-3a8529f0-ffe5-11e9-a7f8
[05/11/19 16:09:59 tuelib1] [INFO] Running kube command: kubectl exec,-i,cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb,--,sh,-c,ls --full-time /home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs | tail -n +2
[05/11/19 16:10:00 tuelib1] [INFO] Looking for all log files in container cw-tuelib1-3a8529f0-ffe5-11e9-a7f8
[05/11/19 16:10:00 tuelib1] [INFO] Running kube command: kubectl exec,-i,cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb,--,sh,-c,ls --full-time /home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs | tail -n +2
[05/11/19 16:10:00 tuelib1] [INFO] applog path:
[{"origin":"container","files":["/home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs/console.log","/home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log"],"podName":"cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb"},{"origin":"workspace","files":["/codewind-workspace/.logs/tuelib1-3a8529f0-ffe5-11e9-a7f8-4195111c186e/app.log"]}]
[05/11/19 16:10:00 /portal/routes/projects/logStream.route.js] [ERROR] TypeError: cwUtils.spawnContainerProcess is not a function
    at ContainerFileLogStream.streamLog (/portal/modules/LogStream.js:239:31)
    at Project.startStreamingLog (/portal/modules/Project.js:536:15)
    at startStreamingAll (/portal/routes/projects/logStream.route.js:60:23)
[05/11/19 16:10:09 Turbine] [INFO] Fetching logs for project 3a8529f0-ffe5-11e9-a7f8-4195111c186e
[05/11/19 16:10:09 tuelib1] [INFO] Looking for all log files in container cw-tuelib1-3a8529f0-ffe5-11e9-a7f8
[05/11/19 16:10:09 tuelib1] [INFO] Running kube command: kubectl exec,-i,cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb,--,sh,-c,ls --full-time /home/default/logs | tail -n +2
[05/11/19 16:10:09 Turbine] [INFO] At least one file was found
[05/11/19 16:10:09 tuelib1] [INFO] buildlog path:
 [{"origin":"container","files":["/home/default/logs/maven.build.log"],"podName":"cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb"},{"origin":"workspace","files":["/codewind-workspace/.logs/tuelib1-3a8529f0-ffe5-11e9-a7f8-4195111c186e/docker.build.log"]}]
[05/11/19 16:10:09 tuelib1] [INFO] Looking for all log files in container cw-tuelib1-3a8529f0-ffe5-11e9-a7f8
[05/11/19 16:10:09 tuelib1] [INFO] Running kube command: kubectl exec,-i,cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb,--,sh,-c,ls --full-time /home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs | tail -n +2
[05/11/19 16:10:10 tuelib1] [INFO] Looking for all log files in container cw-tuelib1-3a8529f0-ffe5-11e9-a7f8
[05/11/19 16:10:10 tuelib1] [INFO] Running kube command: kubectl exec,-i,cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb,--,sh,-c,ls --full-time /home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs | tail -n +2
[05/11/19 16:10:10 tuelib1] [INFO] Looking for all log files in container cw-tuelib1-3a8529f0-ffe5-11e9-a7f8
[05/11/19 16:10:10 tuelib1] [INFO] Running kube command: kubectl exec,-i,cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb,--,sh,-c,ls --full-time /home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs | tail -n +2
[05/11/19 16:10:10 tuelib1] [INFO] applog path:
[{"origin":"container","files":["/home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs/console.log","/home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log"],"podName":"cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb"},{"origin":"workspace","files":["/codewind-workspace/.logs/tuelib1-3a8529f0-ffe5-11e9-a7f8-4195111c186e/app.log"]}]
[05/11/19 16:10:10 /portal/routes/projects/logStream.route.js] [ERROR] TypeError: cwUtils.spawnContainerProcess is not a function
    at ContainerFileLogStream.streamLog (/portal/modules/LogStream.js:239:31)
    at Project.startStreamingLog (/portal/modules/Project.js:536:15)
    at startStreamingAll (/portal/routes/projects/logStream.route.js:60:23)


```

**Steps to reproduce:**
IDE->Show all logs

**Comment by maysunfaisal** [comment]
```
[05/11/19 16:09:46 tuelib1] [INFO] Emitting event 
 message: projectChanged
 data: {
  "operationId": "a7f1fb4b156ee3c3d535e9331807948e",
  "projectID": "3a8529f0-ffe5-11e9-a7f8-4195111c186e",
  "ignoredPaths": [
    "/.project",
    "/Dockerfile-tools",
    "/target",
    "/mc-target",
    "/cli-config.yml",
    "/README.md",
    "/Jenkinsfile",
    "/.cfignore",
    "/load-test*",
    "*/node_modules*",
    "*/.git/*",
    "*/.DS_Store",
    "*/*.swp",
    "*/*.swx",
    "*/4913",
    "*/.dockerignore",
    "*/.gitignore",
    "*/*~",
    "/.settings",
    "/localm2cache.zip",
    "/libertyrepocache.zip"
  ],
  "isHttps": false,
  "status": "success",
  "ports": {
    "exposedPort": "32309",
    "internalPort": "9080"
  },
  "podName": "cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb",
  "logs": {
    "build": [
      {
        "origin": "container",
        "files": [
          "/home/default/logs/maven.build.log"
        ],
        "podName": "cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb"
      },
      {
        "origin": "workspace",
        "files": [
          "/codewind-workspace/.logs/tuelib1-3a8529f0-ffe5-11e9-a7f8-4195111c186e/docker.build.log"
        ]
      }
    ],
    "app": [
      {
        "origin": "container",
        "files": [
          "/home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs/console.log",
          "/home/default/app/mc-target/liberty/wlp/usr/servers/defaultServer/logs/messages.log"
        ],
        "podName": "cw-tuelib1-3a8529f0-ffe5-11e9-a7f8-b76fc7f4b-dzhzb"
      },
      {
        "origin": "workspace",
        "files": [
          "/codewind-workspace/.logs/tuelib1-3a8529f0-ffe5-11e9-a7f8-4195111c186e/app.log"
        ]
      }
    ]
  }
}
```

**Comment by maysunfaisal** [comment]
dup of #963
