### ISSUE TITLE
Cannot Bind Project on Win VS Code Latest

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#993]
**Codewind version:** latest
**OS:** Win

**Che version:**
**IDE extension version:** latest
**IDE version:**
**Kubernetes cluster:**

**Description:**
When trying to debug #960 I hit:

### FYI, I cannot create projects on Windows using VS Code latest

I made sure the PFE container spun up by VS Code had the code commits as of Nov 5..

```
[05/11/19 17:49:42 Turbine] [INFO] The current log level is trace
[05/11/19 17:49:42 /portal/routes/logging.route.js] [INFO] logging level set to trace
[05/11/19 17:49:42 server.js] [TRACE] responded to PUT /api/v1/logging with status 200 and body { level: 'trace' }
[05/11/19 17:50:13 server.js] [TRACE] GET /api/v1/projects/watchlist called with
 req.body {}
[05/11/19 17:50:13 User.js] [DEBUG] The watch list: {"projects":[{"pathToMonitor":"/c/codewind-data/.config","projectID":"c6ecfe5835adf90002d0a58ac47d0f30","ignoredPaths":[],"projectWatchStateId":"badc4a4648eeb17bca722e49b3481373","type":"non-project"}]}
[05/11/19 17:50:13 server.js] [TRACE] responded to GET /api/v1/projects/watchlist with status 200 and body {}
[05/11/19 17:50:19 server.js] [TRACE] GET /api/v1/templates called with
 req.body {}, and
 req.query { showEnabledOnly: 'true' }
[05/11/19 17:50:23 Templates.js] [INFO] Repository list updated.
[05/11/19 17:50:25 server.js] [TRACE] responded to GET /api/v1/templates with status 200 and body {}
[05/11/19 17:50:50 server.js] [TRACE] GET /api/v1/extensions called with
 req.body {}
[05/11/19 17:50:50 server.js] [TRACE] responded to GET /api/v1/extensions with status 200 and body {}
[05/11/19 17:50:51 server.js] [TRACE] Checking origin host  matches expected host 127.0.0.1:10000
[05/11/19 17:50:51 server.js] [TRACE] POST /api/v1/projects/bind/start called with
 req.body { language: 'java',
  projectType: 'liberty',
  name: 'libertywin1',
  path:
   'c:\\Users\\Administrator\\Downloads\\maysunworkspace\\libertywin1' }
[05/11/19 17:50:51 server.js] [TRACE] responded to POST /api/v1/projects/bind/start with status 404 and body { language: 'java',
  projectType: 'liberty',
  name: 'libertywin1',
  path:
   'c:\\Users\\Administrator\\Downloads\\maysunworkspace\\libertywin1' }
[05/11/19 17:51:32 server.js] [TRACE] GET /api/v1/templates called with
 req.body {}, and
 req.query { showEnabledOnly: 'true' }
```

![Screen Shot 2019-11-05 at 12 51 26 PM](https://user-images.githubusercontent.com/31771087/68232763-c9c3b100-ffcb-11e9-85a7-7f3ac379fbb0.png)

**Comment by maysunfaisal** [comment]
cwctl command from the Codewind output stream (thanks @tetchel)

```
[1BWaiting for Codewind to start
......................
HTTP Response Status: 200 OK
Codewind successfully started on http://127.0.0.1:10000
==> End cwctl.exe --json start -t latest
==> Run cwctl.exe --json --insecure status
{"status":"started","url":"http://127.0.0.1:10000","installed-versions":["latest","0.5.0"],"started":["latest"]}
==> End cwctl.exe --json --insecure status
==> Run cwctl.exe --json --insecure project create c:\Users\Administrator\Downloads\maysunworkspace\libertywin1 --url https://github.com/microclimate-dev2ops/javaMicroProfileTemplate
2019/11/05 12:50:50 Downloaded file from 'https://codeload.github.com/microclimate-dev2ops/javaMicroProfileTemplate/legacy.zip/master' to 'C:\Users\ADMINI~1\AppData\Local\Temp/_2019-11-05T12-50-50-05-00.zip'
2019/11/05 12:50:50 Extracted file from 'C:\Users\ADMINI~1\AppData\Local\Temp/_2019-11-05T12-50-50-05-00.zip' to 'c:\Users\Administrator\Downloads\maysunworkspace\libertywin1'
{"status":"success","projectPath":"c:\\Users\\Administrator\\Downloads\\maysunworkspace\\libertywin1","result":{"language":"java","projectType":"liberty"}}
==> End cwctl.exe --json --insecure project create c:\Users\Administrator\Downloads\maysunworkspace\libertywin1 --url https://github.com/microclimate-dev2ops/javaMicroProfileTemplate
==> Run cwctl.exe --json --insecure project bind --conid local --name libertywin1 --language java --type liberty --path c:\Users\Administrator\Downloads\maysunworkspace\libertywin1
{"error":"proj_response","error_description":"unable to find requested resource on Codewind server"}
==> End cwctl.exe --json --insecure project bind --conid local --name libertywin1 --language java --type liberty --path c:\Users\Administrator\Downloads\maysunworkspace\libertywin1
```

**Comment by maysunfaisal** [comment]
this is a stop ship because I cannot create projects on Win using VS Code latest

**Comment by mattcolegate** [comment]
Taking a look

**Comment by mattcolegate** [comment]
We've tested using the latest VSCode plugin (https://download.eclipse.org/codewind/codewind-vscode/master/166/) with CW_TAG=latest, and we sucessfully created a Microprofile java project. It came up successfully, and when we made a change to the v1/example it rebuilt and came back up with the change present. Suspect this was fixed by https://github.com/eclipse/codewind-installer/pull/189 making it into the build.

**Comment by mattcolegate** [comment]
@maysunfaisal Please re-test on latest IDE/Installer and images

**Comment by maysunfaisal** [comment]
project create now fails on validation:

```
PS C:\Users\Administrator> docker logs -f 1e5e9f3edf02
Creating workspace config directory
codewind-pfe container started Thu Nov  7 16:51:53 UTC 2019

> codewind-portal@1.0.0 start /portal
> ./npm-start.sh

Found node environment set to prod. Running in production mode.

> codewind-portal@1.0.0 prod /portal
> node server.js

[07/11/19 16:51:55 server.js] [INFO] Codewind does not appear to be running in k8s
[07/11/19 16:51:55 server.js] [INFO] Codewind is running locally
[07/11/19 16:51:55 Turbine] [INFO] The current log level is info
[07/11/19 16:51:56 Turbine] [INFO] Initialize application state map
[07/11/19 16:51:56 Turbine] [INFO] Initialize build state map
[07/11/19 16:51:56 Turbine] [INFO] Starting application ping intervals
(node:70) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:70) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:70) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
[07/11/19 16:51:56 Turbine] [INFO] The project folder does not exist yet: /file-watcher/fwdata/projects/
[07/11/19 16:51:56 Turbine] [INFO] Registered listener: portalListener
[07/11/19 16:51:56 server.js] [INFO] PerformanceHost: codewind-performance
[07/11/19 16:51:56 server.js] [INFO] Setting up codewind Express routes
[07/11/19 16:51:56 LoadRunner.js] [INFO] Loadrunner has connected
[07/11/19 18:41:32 /portal/modules/Project.js] [INFO] Project thulib1 initializing (project type: liberty, projectID: 380dbe30-018e-11ea-ae8c-09c73706acfb)
[07/11/19 18:41:32 /portal/routes/projects/remoteBind.route.js] [INFO] Project thulib1 (380dbe30-018e-11ea-ae8c-09c73706acfb) opened.
[07/11/19 18:41:32 /portal/routes/projects/remoteBind.route.js] [INFO] Successfully created project - name: thulib1, ID: 380dbe30-018e-11ea-ae8c-09c73706acfb
[07/11/19 18:41:33 User.js] [INFO] Building project 380dbe30-018e-11ea-ae8c-09c73706acfb (thulib1)
[07/11/19 18:41:33 FileWatcher.js] [INFO] Calling createProject() for project thulib1 {"projectID":"380dbe30-018e-11ea-ae8c-09c73706acfb","projectType":"liberty","startMode":"run","location":"/codewind-workspace/thulib1","settings":{"contextRoot":"","internalPort":"","healthCheck":"","internalDebugPort":"","isHttps":false,"ignoredPaths":[""],"mavenProfiles":[""],"mavenProperties":[""]},"language":"java"}
[07/11/19 18:41:33 Turbine] [INFO] Creating project logs directory
[07/11/19 18:41:33 Turbine] [INFO] 380dbe30-018e-11ea-ae8c-09c73706acfb: Project Settings: {"contextRoot":"","internalPort":"","healthCheck":"","internalDebugPort":"","isHttps":false,"ignoredPaths":[""],"mavenProfiles":[""],"mavenProperties":[""]}
[07/11/19 18:41:33 Turbine] [INFO] Log directory created at: /codewind-workspace/.logs/thulib1-380dbe30-018e-11ea-ae8c-09c73706acfb
[07/11/19 18:41:33 Turbine] [ERROR] [File Name: /file-watcher/server/dist/controllers/projectsController.js | Function Name: getProjectInfoFromFile | Line Number: 773] Failed to find project information related to file /file-watcher/fwdata/projects/380dbe30-018e-11ea-ae8c-09c73706acfb/380dbe30-018e-11ea-ae8c-09c73706acfb.json
[07/11/19 18:41:33 thulib1] [INFO] Creating project /codewind-workspace/thulib1
[07/11/19 18:41:33 thulib1] [INFO] Project data directory: /file-watcher/fwdata/projects/
[07/11/19 18:41:33 thulib1] [INFO] Initial start mode for project 380dbe30-018e-11ea-ae8c-09c73706acfb is: run
[07/11/19 18:41:33 thulib1] [INFO] Setting isHttps from the project settings
[07/11/19 18:41:33 thulib1] [INFO] The ignoredPaths array is empty, File-watcher will ignore the setting
[07/11/19 18:41:33 thulib1] [INFO] At least one of the element is empty, File-watcher will ignore the setting mavenProfiles
[07/11/19 18:41:33 thulib1] [INFO] At least one of the element is empty, File-watcher will ignore the setting mavenProperties
[07/11/19 18:41:33 Turbine] [INFO] 380dbe30-018e-11ea-ae8c-09c73706acfb: ignoredPaths after removed any empty strings:
[07/11/19 18:41:33 thulib1] [INFO] operationId: 843369e907d980a8568943363aa12f15
[07/11/19 18:41:33 thulib1] [INFO] Pushing project to build queue
[07/11/19 18:41:33 thulib1] [INFO] Checking for required files
[07/11/19 18:41:33 thulib1] [INFO] Checking for required file /Dockerfile | /Dockerfile-lang
[07/11/19 18:41:33 /portal/routes/projects/remoteBind.route.js] [INFO] Successfully created project - name: thulib1, ID: 380dbe30-018e-11ea-ae8c-09c73706acfb
[07/11/19 18:41:33 thulib1] [INFO] Checking for required file /Dockerfile-build
[07/11/19 18:41:33 thulib1] [INFO] Checking for required file /pom.xml
[07/11/19 18:41:33 thulib1] [INFO] Checking for required file /src/main/liberty/config/server.xml
[07/11/19 18:41:33 thulib1] [INFO] Beginning build for 380dbe30-018e-11ea-ae8c-09c73706acfb
[07/11/19 18:41:33 thulib1] [ERROR] [ File Name: /file-watcher/server/dist/projects/Validator.js | Function Name: validateRequiredFiles | Line Number: 125] Missing file: /src/main/liberty/config/server.xml
[07/11/19 18:41:33 FileWatcher.js] [ERROR] projectStatusChanged: failed (project: {
  "projectID": "380dbe30-018e-11ea-ae8c-09c73706acfb",
  "buildStatus": "failed",
  "detailedBuildStatus": "The build failed because required files are missing. See validation results for details.",
  "lastbuild": 1573152093182
})
[07/11/19 18:41:33 thulib1] [INFO] Validating project using operationId: d69483ac8ccd385550b890b8a1d14ee6
[07/11/19 18:41:33 thulib1] [INFO] Checking for required files
[07/11/19 18:41:33 thulib1] [INFO] Checking for required file /Dockerfile | /Dockerfile-lang
[07/11/19 18:41:33 thulib1] [INFO] Checking for required file /Dockerfile-build
[07/11/19 18:41:33 thulib1] [INFO] Checking for required file /pom.xml
[07/11/19 18:41:33 thulib1] [INFO] Build state changed for project: 380dbe30-018e-11ea-ae8c-09c73706acfb from: unknown, to: failed, with message: buildscripts.buildFailMissingFile
[07/11/19 18:41:33 thulib1] [INFO] Emitting event
 message: projectStatusChanged
 data: {
  "projectID": "380dbe30-018e-11ea-ae8c-09c73706acfb",
  "buildStatus": "failed",
  "detailedBuildStatus": "The build failed because required files are missing. See validation results for details.",
  "lastbuild": 1573152093182
}
[07/11/19 18:41:33 thulib1] [INFO] Kicking off validation for project: 380dbe30-018e-11ea-ae8c-09c73706acfb
[07/11/19 18:41:33 thulib1] [INFO] Checking for required file /src/main/liberty/config/server.xml
[07/11/19 18:41:33 thulib1] [ERROR] server.xml not found at: /codewind-workspace/thulib1/src/main/liberty/config/server.xml
[07/11/19 18:41:33 thulib1] [INFO] buildlog path:
 []
[07/11/19 18:41:33 thulib1] [INFO] Looking for all log files in container cw-thulib1-380dbe30-018e-11ea-ae8c-09c73706acfb
[07/11/19 18:41:33 thulib1] [INFO] applog path:
[]
[07/11/19 18:41:33 thulib1] [INFO] Writing to build log in container cw-thulib1-380dbe30-018e-11ea-ae8c-09c73706acfb at [object Object] :

[ERROR] The Liberty server configuration file was not found at /codewind-workspace/thulib1/src/main/liberty/config/server.xml.
        Please move the server.xml to this location, or copy one in from another Microprofile project.
[07/11/19 18:41:33 thulib1] [INFO] Sending validation result
[07/11/19 18:41:33 FileWatcher.js] [ERROR] projectValidated: failed (project: {
  "operationId": "d69483ac8ccd385550b890b8a1d14ee6",
  "projectType": "liberty",
  "location": "/codewind-workspace/thulib1",
  "projectID": "380dbe30-018e-11ea-ae8c-09c73706acfb",
  "status": "failed",
  "results": [
    {
      "severity": "error",
      "filename": "server.xml",
      "filepath": "thulib1/src/main/liberty/config/server.xml",
      "type": "missing",
      "label": "Missing required file",
      "details": "server.xml is required but was not found.",
      "quickfix": {
        "fixID": "generateMissingFiles",
        "name": "Generate missing files",
        "description": "Generate missing required files."
      }
    }
  ],
  "operation": {
    "operationId": "d69483ac8ccd385550b890b8a1d14ee6",
    "type": "validate",
    "projectInfo": {
      "projectType": "liberty",
      "location": "/codewind-workspace/thulib1",
      "projectID": "380dbe30-018e-11ea-ae8c-09c73706acfb"
    }
  }
})
[07/11/19 18:41:33 Turbine] [INFO] Fetching logs for project 380dbe30-018e-11ea-ae8c-09c73706acfb
[07/11/19 18:41:33 thulib1] [INFO] Emitting event
 message: projectValidated
 data: {
  "operationId": "d69483ac8ccd385550b890b8a1d14ee6",
  "projectType": "liberty",
  "location": "/codewind-workspace/thulib1",
  "projectID": "380dbe30-018e-11ea-ae8c-09c73706acfb",
  "status": "failed",
  "results": [
    {
      "severity": "error",
      "filename": "server.xml",
      "filepath": "thulib1/src/main/liberty/config/server.xml",
      "type": "missing",
      "label": "Missing required file",
      "details": "server.xml is required but was not found.",
      "quickfix": {
        "fixID": "generateMissingFiles",
        "name": "Generate missing files",
        "description": "Generate missing required files."
      }
    }
  ],
  "operation": {
    "operationId": "d69483ac8ccd385550b890b8a1d14ee6",
    "type": "validate",
    "projectInfo": {
      "projectType": "liberty",
      "location": "/codewind-workspace/thulib1",
      "projectID": "380dbe30-018e-11ea-ae8c-09c73706acfb"
    }
  }
}
[07/11/19 18:41:33 thulib1] [INFO] buildlog path:
 []
[07/11/19 18:41:33 thulib1] [INFO] Looking for all log files in container cw-thulib1-380dbe30-018e-11ea-ae8c-09c73706acfb
[07/11/19 18:41:33 thulib1] [INFO] applog path:
[]
[07/11/19 18:41:37 thulib1] [INFO] Build completed for 380dbe30-018e-11ea-ae8c-09c73706acfb
[07/11/19 18:41:58 /portal/routes/projects/fileChanges.route.js] [INFO] Watch status for projectID 380dbe30-018e-11ea-ae8c-09c73706acfb: success
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] Removing locally deleted files from project: thulib1, ID: 380dbe30-018e-11ea-ae8c-09c73706acfb -
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is .cw-settings projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is .dockerignore projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is .gitignore projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is Dockerfile projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is Dockerfile-build projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is Dockerfile-tools projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is README.md projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart\javamicroprofiletemplate\Chart.yaml projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart\javamicroprofiletemplate\bindings.yaml projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart\javamicroprofiletemplate\templates\basedeployment.yaml projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart\javamicroprofiletemplate\templates\deployment.yaml projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart\javamicroprofiletemplate\templates\hpa.yaml projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart\javamicroprofiletemplate\templates\istio.yaml projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart\javamicroprofiletemplate\templates\service.yaml projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is chart\javamicroprofiletemplate\values.yaml projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is pom.xml projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src\main\java\application\HealthEndpoint.java projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src\main\java\application\rest\JaxrsApplication.java projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src\main\java\application\rest\RootEndpoint.java projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src\main\java\application\rest\v1\Example.java projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src\main\liberty\config\jvm.options projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src\main\liberty\config\jvmbx.options projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src\main\liberty\config\server.xml projectRoot is /home/default/app
[07/11/19 18:41:59 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src\main\resources\index.html projectRoot is /home/default/app
[07/11/19 18:42:00 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src\main\webapp\WEB-INF\beans.xml projectRoot is /home/default/app
[07/11/19 18:42:00 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src\main\webapp\WEB-INF\ibm-web-ext.xml projectRoot is /home/default/app
[07/11/19 18:42:00 /portal/routes/projects/remoteBind.route.js] [INFO] project is [object Object] file is src\test\java\it\HealthEndpointIT.java projectRoot is /home/default/app
[07/11/19 18:42:00 FileWatcher.js] [ERROR] Error: project update 400 Bad request. projectID, timestamp, chunk, chunk_total and eventArray are required.
    at FileWatcher.projectFileChanged (/portal/modules/FileWatcher.js:395:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:70) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/thulib1/src\main\liberty\config\server.xml undefined:/home/default/app/src\main\liberty\config\server.xml
lstat /codewind-workspace/thulib1/srcmainlibertyconfigserver.xml: no such file or directory

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:70) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:70) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/thulib1/src\main\liberty\config\jvmbx.options undefined:/home/default/app/src\main\liberty\config\jvmbx.options
lstat /codewind-workspace/thulib1/srcmainlibertyconfigjvmbx.options: no such file or directory

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:70) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/thulib1/src\main\liberty\config\jvm.options undefined:/home/default/app/src\main\liberty\config\jvm.options
lstat /codewind-workspace/thulib1/srcmainlibertyconfigjvm.options: no such file or directory

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:70) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:70) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/thulib1/src\main\java\application\rest\v1\Example.java undefined:/home/default/app/src\main\java\application\rest\v1\Example.java
lstat /codewind-workspace/thulib1/srcmainjavaapplicationrestv1Example.java: no such file or directory

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:
```

**Comment by maysunfaisal** [comment]
I think the above issue could be tracked with https://github.com/eclipse/codewind/issues/960 since bind is now working

**Comment by mattcolegate** [comment]
Testing on Windows 10, VSCode plugin from https://download.eclipse.org/codewind/codewind-vscode/master/177/, CW_TAG=latest, no docker containers running before starting. Microprofile liberty template selected.

Unable to recreate. App built, started and is running. Some strange filewatcher messages in the log though, will attach.

**Comment by mattcolegate** [comment]
[993PFELogLibertyProjCreate.txt](https://github.com/eclipse/codewind/files/3821471/993PFELogLibertyProjCreate.txt)

**Comment by rajivnathan** [comment]
@mattcolegate What is your pfe image id? I'm unable to reproduce as well but it looks like Maysun has a newer image ID than I do. I'm going to removing my image and pulling the latest one.

**Comment by mattcolegate** [comment]
@rajivnathan codewind-0.6.0-201911071811.vsix

**Comment by jgwest** [comment]
@mattcolegate I think Rajiv was looking for your PFE container image id (sha256 hash)

**Comment by mattcolegate** [comment]
Ah right - `codewind-pfe-amd64                                   latest                 sha256:c641dd7f23b7f422d5d1c02caf6e7073d5bb7883fd333c4156bda12f187f6ec3   2 hours ago         781MB`

**Comment by maysunfaisal** [comment]
even tho i had the latest vsix and my PFE was the same as Matt; it was using an older cache of cwctl.

The way I resolved it was rename my vsix to `Maysun.vsix` and reinstalled IDE extension again and everything seemed to work. No idea why VS Code is using cached cwctl.

I have a video proof of it for anyone interested. 😂 

verified, closing
